select case when CreationDate is NULL then GETDATE()
	else CreationDate end as Forward_insert_timestamp
, concat('FR',VacancyUniqID) as Forward_JobExtID
, concat_ws(char(10), concat('Unique ID: ', UniqueID)
	, concat('Candidate Unique ID: ', CandidateUniqID)
	, concat('Vacancy Unique ID: ', VacancyUniqID)
	, coalesce('Creation Date: ' + convert(varchar(10),CreationDate,120),'')
	, coalesce('Interview Date: ' + convert(varchar(10),InterviewDate,120),'')
	, coalesce('InterviewTime: ' + convert(varchar(10),InterviewTime,120),'')
	, coalesce('Consultant: ' + case Consultant
	when 'ADM' then concat(Consultant, ' - ', 'Admin',' - ','No email adress - admin login')
	when 'ADMT' then concat(Consultant, ' - ', 'Staff Training Login')
	when 'AH' then concat(Consultant, ' - ', 'Alison Hart',' - ','alison@forwardrolerecruitment.com')
	when 'AM' then concat(Consultant, ' - ', 'Adam Miller',' - ','adam@forwardrolerecruitment.com')
	when 'ARAL' then concat(Consultant, ' - ', 'Arif Ali',' - ','arif@forwardrole.com')
	when 'BJ' then concat(Consultant, ' - ', 'Brian Johnson',' - ','brian@forwardrole.com')
	when 'BRTO' then concat(Consultant, ' - ', 'Brad Thomas',' - ','brad@forwardrole.com')
	when 'BS' then concat(Consultant, ' - ', 'Becky Smith',' - ','becky@forwardrole.com')
	when 'CP' then concat(Consultant, ' - ', 'Camilla Purdy',' - ','camilla@forwardrole.com (ADMIN) ')
	when 'CT' then concat(Consultant, ' - ', 'Chris Thomason',' - ','chris@forwardrolerecruitment.com')
	when 'DAHA' then concat(Consultant, ' - ', 'Danielle Harvey',' - ','danielle@forwardrolerecruitment.com')
	when 'DAHY' then concat(Consultant, ' - ', 'Dan Haydon',' - ','danh@forwardrole.com')
	when 'DANO' then concat(Consultant, ' - ', 'David Nottage',' - ','david@forwardrolerecruitment.com')
	when 'DETO' then concat(Consultant, ' - ', 'Desislava Torodova',' - ','desi@forwardrole.com')
	when 'DM' then concat(Consultant, ' - ', 'Dan Middlebrook',' - ','dan@forwardrole.com')
	when 'DS' then concat(Consultant, ' - ', 'Dominic Scales',' - ','dominic@forwardrolerecruitment.com')
	when 'EMME' then concat(Consultant, ' - ', 'Emma Melling',' - ','emma@forwardrole.com')
	when 'GRBO' then concat(Consultant, ' - ', 'Grant Bodie',' - ','grant@forwardrole.com')
	when 'GW' then concat(Consultant, ' - ', 'Guy Walker',' - ','guy@forwardrole.com')
	when 'HB' then concat(Consultant, ' - ', 'Henna Baig',' - ','henna@forwardrolerecruitment.com')
	when 'HC' then concat(Consultant, ' - ', 'Helen Colley',' - ','helen@forwardrole.com')
	when 'IL' then concat(Consultant, ' - ', 'Ian Lenahan',' - ','ian@forwardrolerecruitment.com')
	when 'IZKH' then concat(Consultant, ' - ', 'Izzy Khan',' - ','izzy@forwardrole.com')
	when 'JH' then concat(Consultant, ' - ', 'Jack Harrison',' - ','jack@forwardrolerecruitment.com')
	when 'JOPE' then concat(Consultant, ' - ', 'Josh Pepper',' - ','josh@forwardrole.com')
	when 'JS' then concat(Consultant, ' - ', 'Jon Saxon',' - ','jon@forwardrolerecruitment.com')
	when 'KM' then concat(Consultant, ' - ', 'Katrina McCafferty',' - ','katrina@forwardrolerecruitment.com')
	when 'LK' then concat(Consultant, ' - ', 'Lucy Ketley',' - ','lucy@forwardrolerecruitment.com')
	when 'MABO' then concat(Consultant, ' - ', 'Matthew Borthwick',' - ','mattb@forwardrole.com')
	when 'MD' then concat(Consultant, ' - ', 'Matt Darwell',' - ','matt@forwardrole.com')
	when 'MIRH' then concat(Consultant, ' - ', 'Mike Rhodes',' - ','mike@forwardrole.com')
	when 'NAYO' then concat(Consultant, ' - ', 'Nathan Young',' - ','nathan@forwardrole.com')
	when 'PAMC' then concat(Consultant, ' - ', 'Patrick McMahon',' - ','patrick@forwardrole.com')
	when 'PAWE' then concat(Consultant, ' - ', 'Paddy Wells',' - ','paddy@forwardrole.com')
	when 'PHST' then concat(Consultant, ' - ', 'Phill Stott',' - ','phill@forwardrole.com')
	when 'RADA' then concat(Consultant, ' - ', 'Rachel Davies',' - ','rachel@forwardrole.com')
	when 'RAWH' then concat(Consultant, ' - ', 'Rachel Wheeler',' - ','rachelw@forwardrole.com')
	when 'RF' then concat(Consultant, ' - ', 'Ricardo Facchin')
	when 'RYDO' then concat(Consultant, ' - ', 'Ryan Dolan',' - ','ryan@forwardrole.com')
	when 'SASH' then concat(Consultant, ' - ', 'Sam Shinners',' - ','sam@forwardrolere.com')
	when 'SOPA' then concat(Consultant, ' - ', 'Sophie Page',' - ','sophie@forwardrole.com')
	when 'ST' then concat(Consultant, ' - ', 'Steve Thompson',' - ','steve@forwardrole.com')
	when 'TOBY' then concat(Consultant, ' - ', 'Tom Byrne',' - ','tom@forwardrole.com')
	when 'TP' then concat(Consultant, ' - ', 'Thea Parry',' - ','thea@forwardrolerecruitment.com')
	when 'WIVE' then concat(Consultant, ' - ', 'Will Velios',' - ','will@forwardrolerecruitment.com')
	else Consultant end,'')
	, coalesce('Status: ' + nullif(Status,''),'')
	, coalesce('Interview Contact: ' + nullif(InterviewContact,''),'')
	, coalesce('Interview Contact Role: ' + nullif(IViewContactRole,''),'')
	, coalesce('Interview Address House No: ' + nullif(IViewAddrHseNo,''),'')
	, coalesce('Interview Address: ' + nullif(IViewAddress,''),'')
	, coalesce('Interview Address Line 1: ' + nullif(IViewAddrLine1,''),'')
	, coalesce('Interview Address Line 2: ' + nullif(IViewAddrLine2,''),'')
	, coalesce('Interview Address Line 3: ' + nullif(IViewAddrLine3,''),'')
	, coalesce('Interview Address Line 4: ' + nullif(IViewAddrLine4,''),'')
	, coalesce('Interview Address Line 5: ' + nullif(IViewAddrLine5,''),'')
	, coalesce('Interview Address Line 6: ' + nullif(IViewAddrLine6,''),'')
	, coalesce('Interview Post: ' + nullif(IViewPost,''),'')
	, coalesce('Site Unique ID: ' + nullif(convert(varchar(max),SiteUniqueID),''),'')
	, coalesce('Report To: ' + nullif(convert(varchar(max),ReportToUniq),''),'')
	, coalesce('Booked Yes/No: ' + nullif(BookedYN,''),'')
	, coalesce('Attended Yes/No: ' + nullif(AttendedYN,''),'')
	, coalesce('Interviewer 1: ' + nullif(Interviewers001,''),'')
	, coalesce('Interviewer 2: ' + nullif(Interviewers002,''),'')
	, coalesce('Interviewer 3: ' + nullif(Interviewers003,''),'')
	, coalesce('Interviewer 4: ' + nullif(Interviewers004,''),'')
	, coalesce('Interviewer 5: ' + nullif(Interviewers005,''),'')
	, coalesce('Interviewer Role 1: ' + nullif(InterviewerRoles001,''),'')
	, coalesce('Interviewer Role 2: ' + nullif(InterviewerRoles002,''),'')
	, coalesce('Interviewer Role 3: ' + nullif(InterviewerRoles003,''),'')
	, coalesce('Interviewer Role 4: ' + nullif(InterviewerRoles004,''),'')
	, coalesce('Interviewer Role 5: ' + nullif(InterviewerRoles005,''),'')
	) as Forward_comment_activities
, -10 as Forward_user_account_id
, 'comment' as Forward_category
, 'job' as Forward_type
from Matches
order by VacancyUniqID

--total: 74905