
--select current_timestamp

insert into vertical(name,insert_timestamp) values ('Third Sector / Charity',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Call Centre',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Construction',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Consultancy / Technical Consultancy',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Digital Agency',current_timestamp);
insert into vertical(name,insert_timestamp) values ('eCommerce',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Education',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Finance',current_timestamp);
insert into vertical(name,insert_timestamp) values ('FMCG',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Logistics',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Manufacturing',current_timestamp);
insert into vertical(name,insert_timestamp) values ('NHS',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Oil and Gas / Energy',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Pharma',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Public',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Retail',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Software',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Utilities',current_timestamp);
insert into vertical(name,insert_timestamp) values ('.Net',current_timestamp);
insert into vertical(name,insert_timestamp) values ('1st Line',current_timestamp);
insert into vertical(name,insert_timestamp) values ('ADO.Net',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Agile',current_timestamp);
insert into vertical(name,insert_timestamp) values ('AJAX',current_timestamp);
insert into vertical(name,insert_timestamp) values ('AS400',current_timestamp);
insert into vertical(name,insert_timestamp) values ('ASP.Net',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Automated Testing',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Business Analyst',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Business Intelligence',current_timestamp);
insert into vertical(name,insert_timestamp) values ('C',current_timestamp);
insert into vertical(name,insert_timestamp) values ('C#',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Cisco',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Cisco (Gen)',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Cloud',current_timestamp);
insert into vertical(name,insert_timestamp) values ('CMS (Gen)',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Cobol',current_timestamp);
insert into vertical(name,insert_timestamp) values ('CRM',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Database Adminstrator',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Database Specialist',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Developer',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Developer/Programmer',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Digital',current_timestamp);
insert into vertical(name,insert_timestamp) values ('ERP',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Glovia',current_timestamp);
insert into vertical(name,insert_timestamp) values ('J2EE',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Java',current_timestamp);
insert into vertical(name,insert_timestamp) values ('jQuery',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Lean/6 Sigma',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Manufacturing',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Microsoft & SQL Server',current_timestamp);
insert into vertical(name,insert_timestamp) values ('OO',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Oracle',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Retail',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Salesforce',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Sittikarn',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Software Developer',current_timestamp);
insert into vertical(name,insert_timestamp) values ('SQL',current_timestamp);
insert into vertical(name,insert_timestamp) values ('SQL Server',current_timestamp);
insert into vertical(name,insert_timestamp) values ('SQL Server 2000',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Storage',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Systems Analyst',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Systems Testing',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Tester',current_timestamp);
insert into vertical(name,insert_timestamp) values ('T-SQL',current_timestamp);
insert into vertical(name,insert_timestamp) values ('UI',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Unit Testing',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Virtualisation',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Visual Basic',current_timestamp);
insert into vertical(name,insert_timestamp) values ('WCF',current_timestamp);
insert into vertical(name,insert_timestamp) values ('Windows Server',current_timestamp);
insert into vertical(name,insert_timestamp) values ('WPF',current_timestamp);
insert into vertical(name,insert_timestamp) values ('XML',current_timestamp);
insert into vertical(name,insert_timestamp) values ('XPATH',current_timestamp);
insert into vertical(name,insert_timestamp) values ('XSLT',current_timestamp);
