
--delete from functional_expertise where insert_timestamp is null

insert into functional_expertise(name) values ('.Net 3.0');
insert into functional_expertise(name) values ('1st Line');
insert into functional_expertise(name) values ('Access');
insert into functional_expertise(name) values ('Actuate');
insert into functional_expertise(name) values ('Agile');
insert into functional_expertise(name) values ('AIX');
insert into functional_expertise(name) values ('Apple');
insert into functional_expertise(name) values ('Architect');
insert into functional_expertise(name) values ('Arcplan');
insert into functional_expertise(name) values ('AS400');
insert into functional_expertise(name) values ('Automated Testing');
insert into functional_expertise(name) values ('.Net 4.0');
insert into functional_expertise(name) values ('2G');
insert into functional_expertise(name) values ('.Net mobile');
insert into functional_expertise(name) values ('Ab Initio');
insert into functional_expertise(name) values ('AV');
insert into functional_expertise(name) values ('Azure');
insert into functional_expertise(name) values ('Blackberry');
insert into functional_expertise(name) values ('Bsm');
insert into functional_expertise(name) values ('Business Development / Sales');
insert into functional_expertise(name) values ('Business Intelligence');
insert into functional_expertise(name) values ('Call Centre');
insert into functional_expertise(name) values ('CCNA');
insert into functional_expertise(name) values ('CCSP');
insert into functional_expertise(name) values ('CEO');
insert into functional_expertise(name) values ('Change Manager');
insert into functional_expertise(name) values ('Chief Operations Officer');
insert into functional_expertise(name) values ('CIO');
insert into functional_expertise(name) values ('Citirx (Gen)');
insert into functional_expertise(name) values ('Classic ASP');
insert into functional_expertise(name) values ('Cloud');
insert into functional_expertise(name) values ('CMS (Gen)');
insert into functional_expertise(name) values ('Crystal Reports');
insert into functional_expertise(name) values ('Datastage');
insert into functional_expertise(name) values ('Development');
insert into functional_expertise(name) values ('DHTML');
insert into functional_expertise(name) values ('DirectX');
insert into functional_expertise(name) values ('Django');
insert into functional_expertise(name) values ('Drupal');
insert into functional_expertise(name) values ('Dynamics (Gen)');
insert into functional_expertise(name) values ('Dynamics Crm');
insert into functional_expertise(name) values ('Dynamics Nav');
insert into functional_expertise(name) values ('Dynamics Sl');
insert into functional_expertise(name) values ('Edinburgh');
insert into functional_expertise(name) values ('EJB');
insert into functional_expertise(name) values ('Embedded C++');
insert into functional_expertise(name) values ('Epicor');
insert into functional_expertise(name) values ('ERP Consultant');
insert into functional_expertise(name) values ('ETL');
insert into functional_expertise(name) values ('EXTGWT');
insert into functional_expertise(name) values ('F#');
insert into functional_expertise(name) values ('Front End Web');
insert into functional_expertise(name) values ('Glasgow');
insert into functional_expertise(name) values ('Gnu');
insert into functional_expertise(name) values ('Handheld');
insert into functional_expertise(name) values ('Helpdesk Manager');
insert into functional_expertise(name) values ('HSE');
insert into functional_expertise(name) values ('IIS');
insert into functional_expertise(name) values ('Ingress');
insert into functional_expertise(name) values ('Italian');
insert into functional_expertise(name) values ('ITIL');
insert into functional_expertise(name) values ('J2SE');
insert into functional_expertise(name) values ('Jaspersoft');
insert into functional_expertise(name) values ('JavaScript');
insert into functional_expertise(name) values ('JDBC');
insert into functional_expertise(name) values ('Jidapa');
insert into functional_expertise(name) values ('Joomla');
insert into functional_expertise(name) values ('JWT');
insert into functional_expertise(name) values ('Kernel');
insert into functional_expertise(name) values ('Kimball');
insert into functional_expertise(name) values ('Korn Shell');
insert into functional_expertise(name) values ('Lamp');
insert into functional_expertise(name) values ('LoadRunner');
insert into functional_expertise(name) values ('Manager');
insert into functional_expertise(name) values ('Manual Testing');
insert into functional_expertise(name) values ('Mapics');
insert into functional_expertise(name) values ('Matlab');
insert into functional_expertise(name) values ('mba');
insert into functional_expertise(name) values ('Mercury');
insert into functional_expertise(name) values ('Netezza');
insert into functional_expertise(name) values ('Netware');
insert into functional_expertise(name) values ('NHS');
insert into functional_expertise(name) values ('Nosql');
insert into functional_expertise(name) values ('Novell (Gen)');
insert into functional_expertise(name) values ('Oracle 8i');
insert into functional_expertise(name) values ('Oracle 9i');
insert into functional_expertise(name) values ('Oracle Application Server');
insert into functional_expertise(name) values ('Oracle Designer');
insert into functional_expertise(name) values ('Pascal');
insert into functional_expertise(name) values ('Pegasus');
insert into functional_expertise(name) values ('Pentaho');
insert into functional_expertise(name) values ('PHP');
insert into functional_expertise(name) values ('PHP5');
insert into functional_expertise(name) values ('Process Safety');
insert into functional_expertise(name) values ('Prognoz');
insert into functional_expertise(name) values ('Project Manager');
insert into functional_expertise(name) values ('Python');
insert into functional_expertise(name) values ('QA');
insert into functional_expertise(name) values ('RAD');
insert into functional_expertise(name) values ('Radio');
insert into functional_expertise(name) values ('RedHat');
insert into functional_expertise(name) values ('Ruby');
insert into functional_expertise(name) values ('RUP');
insert into functional_expertise(name) values ('Sage');
insert into functional_expertise(name) values ('SAP');
insert into functional_expertise(name) values ('SAP ABAP');
insert into functional_expertise(name) values ('SAP CRM Web');
insert into functional_expertise(name) values ('SAP FICO');
insert into functional_expertise(name) values ('SAS');
insert into functional_expertise(name) values ('Sharepoint');
insert into functional_expertise(name) values ('SiteCore');
insert into functional_expertise(name) values ('Solaris');
insert into functional_expertise(name) values ('SQL Server');
insert into functional_expertise(name) values ('SQL Server 2005');
insert into functional_expertise(name) values ('SSIS');
insert into functional_expertise(name) values ('Sun Certified');
insert into functional_expertise(name) values ('Swing');
insert into functional_expertise(name) values ('Sybase');
insert into functional_expertise(name) values ('Symfony');
insert into functional_expertise(name) values ('Systems Analyst');
insert into functional_expertise(name) values ('Team Leader');
insert into functional_expertise(name) values ('Technical Consultancy');
insert into functional_expertise(name) values ('Testing');
insert into functional_expertise(name) values ('TETRA Telecoms');
insert into functional_expertise(name) values ('Third Sector');
insert into functional_expertise(name) values ('UTRAN');
insert into functional_expertise(name) values ('Virtualisation');
insert into functional_expertise(name) values ('Voice');
insert into functional_expertise(name) values ('W3C');
insert into functional_expertise(name) values ('Wamp');
insert into functional_expertise(name) values ('Web Designer');
insert into functional_expertise(name) values ('WF');
insert into functional_expertise(name) values ('Windows Server');
insert into functional_expertise(name) values ('WLAN');
insert into functional_expertise(name) values ('WPF');
insert into functional_expertise(name) values ('Xamarin');
insert into functional_expertise(name) values ('Xendesktop');
insert into functional_expertise(name) values ('XML');
insert into functional_expertise(name) values ('XPATH');
insert into functional_expertise(name) values ('2nd Line');
insert into functional_expertise(name) values ('3G');
insert into functional_expertise(name) values ('3rd Line');
insert into functional_expertise(name) values ('Account Manager');
insert into functional_expertise(name) values ('Actionscript 2.0');
insert into functional_expertise(name) values ('Active Directory');
insert into functional_expertise(name) values ('ADA');
insert into functional_expertise(name) values ('ADF');
insert into functional_expertise(name) values ('Adobe Flash');
insert into functional_expertise(name) values ('Agresso');
insert into functional_expertise(name) values ('Analogue');
insert into functional_expertise(name) values ('Application Support');
insert into functional_expertise(name) values ('ASP.Net');
insert into functional_expertise(name) values ('Benjaporn');
insert into functional_expertise(name) values ('BI Consultant');
insert into functional_expertise(name) values ('Birst');
insert into functional_expertise(name) values ('Biz Dev');
insert into functional_expertise(name) values ('Borders');
insert into functional_expertise(name) values ('Bus. Intelligence');
insert into functional_expertise(name) values ('Business Objects');
insert into functional_expertise(name) values ('CAT5');
insert into functional_expertise(name) values ('CCA');
insert into functional_expertise(name) values ('CCDP');
insert into functional_expertise(name) values ('CCI');
insert into functional_expertise(name) values ('Change Analyst');
insert into functional_expertise(name) values ('Chief Financial Officer');
insert into functional_expertise(name) values ('CISM');
insert into functional_expertise(name) values ('Cognos');
insert into functional_expertise(name) values ('ColdFusion');
insert into functional_expertise(name) values ('CS Core');
insert into functional_expertise(name) values ('CSS');
insert into functional_expertise(name) values ('Database Adminstrator');
insert into functional_expertise(name) values ('Database Specialist');
insert into functional_expertise(name) values ('Developer');
insert into functional_expertise(name) values ('Development Manager');
insert into functional_expertise(name) values ('DHTMLX');
insert into functional_expertise(name) values ('Dundee');
insert into functional_expertise(name) values ('Dynamics');
insert into functional_expertise(name) values ('Eclipse');
insert into functional_expertise(name) values ('Elastic Search');
insert into functional_expertise(name) values ('Ericsson');
insert into functional_expertise(name) values ('Exchange');
insert into functional_expertise(name) values ('FMCG');
insert into functional_expertise(name) values ('French');
insert into functional_expertise(name) values ('Games Developer');
insert into functional_expertise(name) values ('Hadoop');
insert into functional_expertise(name) values ('Informatica');
insert into functional_expertise(name) values ('Infrastructure');
insert into functional_expertise(name) values ('Infrastructure Manager');
insert into functional_expertise(name) values ('Infrastructure Project Manager');
insert into functional_expertise(name) values ('Interest In Big Data');
insert into functional_expertise(name) values ('iPhone');
insert into functional_expertise(name) values ('ISO20071');
insert into functional_expertise(name) values ('IT Director');
insert into functional_expertise(name) values ('J2EE');
insert into functional_expertise(name) values ('J2ME');
insert into functional_expertise(name) values ('Java');
insert into functional_expertise(name) values ('JBoss');
insert into functional_expertise(name) values ('jQuery');
insert into functional_expertise(name) values ('JSPHP');
insert into functional_expertise(name) values ('Knitr');
insert into functional_expertise(name) values ('Linux');
insert into functional_expertise(name) values ('Load testing');
insert into functional_expertise(name) values ('Logistics');
insert into functional_expertise(name) values ('Lotus');
insert into functional_expertise(name) values ('Lotus Domino');
insert into functional_expertise(name) values ('Lync');
insert into functional_expertise(name) values ('Magento');
insert into functional_expertise(name) values ('MAN');
insert into functional_expertise(name) values ('Managing Director');
insert into functional_expertise(name) values ('Mandarin');
insert into functional_expertise(name) values ('Manufacturing');
insert into functional_expertise(name) values ('Masters  Level');
insert into functional_expertise(name) values ('Maximo');
insert into functional_expertise(name) values ('Mcdoogs');
insert into functional_expertise(name) values ('MCITP');
insert into functional_expertise(name) values ('MCP');
insert into functional_expertise(name) values ('MCPD');
insert into functional_expertise(name) values ('MCSE');
insert into functional_expertise(name) values ('MCTP');
insert into functional_expertise(name) values ('Microsoft & SQL Server');
insert into functional_expertise(name) values ('Microsoft Partner');
insert into functional_expertise(name) values ('Microstrategy');
insert into functional_expertise(name) values ('Microwave');
insert into functional_expertise(name) values ('Mobile');
insert into functional_expertise(name) values ('Mura');
insert into functional_expertise(name) values ('NetBeans');
insert into functional_expertise(name) values ('Netsuite');
insert into functional_expertise(name) values ('OBIEE');
insert into functional_expertise(name) values ('Oltp');
insert into functional_expertise(name) values ('Oracle BI');
insert into functional_expertise(name) values ('Oracle Collaboration');
insert into functional_expertise(name) values ('Oracle Crm');
insert into functional_expertise(name) values ('Oracle DataGuard');
insert into functional_expertise(name) values ('Oracle ERP');
insert into functional_expertise(name) values ('Oracle Lite');
insert into functional_expertise(name) values ('Oracle OCP');
insert into functional_expertise(name) values ('Oracle RAC');
insert into functional_expertise(name) values ('Oracle RMAN');
insert into functional_expertise(name) values ('Outlook');
insert into functional_expertise(name) values ('OWB');
insert into functional_expertise(name) values ('PeopleSoft');
insert into functional_expertise(name) values ('Performance Point');
insert into functional_expertise(name) values ('Pharawi');
insert into functional_expertise(name) values ('PHD Level');
insert into functional_expertise(name) values ('PL/SQL');
insert into functional_expertise(name) values ('Procurement');
insert into functional_expertise(name) values ('Progress');
insert into functional_expertise(name) values ('Publisher');
insert into functional_expertise(name) values ('QTP');
insert into functional_expertise(name) values ('RCN');
insert into functional_expertise(name) values ('Reports');
insert into functional_expertise(name) values ('RF');
insert into functional_expertise(name) values ('Russian');
insert into functional_expertise(name) values ('SAP CRM Marketing');
insert into functional_expertise(name) values ('SAP MM');
insert into functional_expertise(name) values ('SAP PP');
insert into functional_expertise(name) values ('SAP QM');
insert into functional_expertise(name) values ('SCCM');
insert into functional_expertise(name) values ('Scrum');
insert into functional_expertise(name) values ('Server Support');
insert into functional_expertise(name) values ('Servlets');
insert into functional_expertise(name) values ('Shell Script');
insert into functional_expertise(name) values ('Software');
insert into functional_expertise(name) values ('Software Developer');
insert into functional_expertise(name) values ('Software Project Manager');
insert into functional_expertise(name) values ('Spanish');
insert into functional_expertise(name) values ('SQL Server 2000');
insert into functional_expertise(name) values ('Sun Accounts');
insert into functional_expertise(name) values ('Tapestry');
insert into functional_expertise(name) values ('TCP/IP');
insert into functional_expertise(name) values ('Tomcat');
insert into functional_expertise(name) values ('UI');
insert into functional_expertise(name) values ('Unix (Gen)');
insert into functional_expertise(name) values ('VBA');
insert into functional_expertise(name) values ('Verilog');
insert into functional_expertise(name) values ('Visual Basic');
insert into functional_expertise(name) values ('VPN');
insert into functional_expertise(name) values ('Waterfall');
insert into functional_expertise(name) values ('WIFI');
insert into functional_expertise(name) values ('WiMAX');
insert into functional_expertise(name) values ('WordPress');
insert into functional_expertise(name) values ('XAML');
insert into functional_expertise(name) values ('XSL');
insert into functional_expertise(name) values ('YUI');
insert into functional_expertise(name) values ('Zend');
insert into functional_expertise(name) values ('Adobe Flex');
insert into functional_expertise(name) values ('Alteryx');
insert into functional_expertise(name) values ('Android');
insert into functional_expertise(name) values ('Back Up');
insert into functional_expertise(name) values ('Business Analyst');
insert into functional_expertise(name) values ('C');
insert into functional_expertise(name) values ('C#');
insert into functional_expertise(name) values ('CakePHP');
insert into functional_expertise(name) values ('Cantonese');
insert into functional_expertise(name) values ('CCIA');
insert into functional_expertise(name) values ('CCIE');
insert into functional_expertise(name) values ('CCNP');
insert into functional_expertise(name) values ('CIO / CTO');
insert into functional_expertise(name) values ('Cisco');
insert into functional_expertise(name) values ('CISSP');
insert into functional_expertise(name) values ('Clojure');
insert into functional_expertise(name) values ('CMOS');
insert into functional_expertise(name) values ('Construction');
insert into functional_expertise(name) values ('Council');
insert into functional_expertise(name) values ('CRM');
insert into functional_expertise(name) values ('Data Science');
insert into functional_expertise(name) values ('Database Developer');
insert into functional_expertise(name) values ('DataCentre');
insert into functional_expertise(name) values ('Digital');
insert into functional_expertise(name) values ('Director');
insert into functional_expertise(name) values ('Dynamics Ax');
insert into functional_expertise(name) values ('Dynamics Gp');
insert into functional_expertise(name) values ('Dynatrace');
insert into functional_expertise(name) values ('efacs');
insert into functional_expertise(name) values ('Essbase');
insert into functional_expertise(name) values ('Excel');
insert into functional_expertise(name) values ('EXTJS');
insert into functional_expertise(name) values ('Firewall');
insert into functional_expertise(name) values ('Forms');
insert into functional_expertise(name) values ('Fortran');
insert into functional_expertise(name) values ('Functional Testing');
insert into functional_expertise(name) values ('Glovia');
insert into functional_expertise(name) values ('Government');
insert into functional_expertise(name) values ('Groupwise');
insert into functional_expertise(name) values ('Hibernate');
insert into functional_expertise(name) values ('HTML');
insert into functional_expertise(name) values ('IBM');
insert into functional_expertise(name) values ('Infor');
insert into functional_expertise(name) values ('Ipython');
insert into functional_expertise(name) values ('IT Manager');
insert into functional_expertise(name) values ('Jd Edwards E1');
insert into functional_expertise(name) values ('JD Edwards World');
insert into functional_expertise(name) values ('JSP');
insert into functional_expertise(name) values ('Languages');
insert into functional_expertise(name) values ('LINQ');
insert into functional_expertise(name) values ('LTE');
insert into functional_expertise(name) values ('Mahout');
insert into functional_expertise(name) values ('Maven');
insert into functional_expertise(name) values ('MCDBA');
insert into functional_expertise(name) values ('MCTS');
insert into functional_expertise(name) values ('Microsoft');
insert into functional_expertise(name) values ('MRP');
insert into functional_expertise(name) values ('Ms Bi Developer');
insert into functional_expertise(name) values ('MySQL');
insert into functional_expertise(name) values ('Network Engineer');
insert into functional_expertise(name) values ('Network Manager');
insert into functional_expertise(name) values ('nHibernate');
insert into functional_expertise(name) values ('Ods');
insert into functional_expertise(name) values ('OpenSUSE');
insert into functional_expertise(name) values ('Operations Manager');
insert into functional_expertise(name) values ('Oracle');
insert into functional_expertise(name) values ('Oracle OEM');
insert into functional_expertise(name) values ('OSS');
insert into functional_expertise(name) values ('Panda');
insert into functional_expertise(name) values ('Product Manager');
insert into functional_expertise(name) values ('Regression Testing');
insert into functional_expertise(name) values ('Salient');
insert into functional_expertise(name) values ('Sap Crm');
insert into functional_expertise(name) values ('SAP CRM (Gen)');
insert into functional_expertise(name) values ('SAP HR');
insert into functional_expertise(name) values ('Script.aculo.us');
insert into functional_expertise(name) values ('Security Testing');
insert into functional_expertise(name) values ('Selenium');
insert into functional_expertise(name) values ('Server Engineer');
insert into functional_expertise(name) values ('Sittikarn');
insert into functional_expertise(name) values ('SQL Server 2008');
insert into functional_expertise(name) values ('SQL Server 2012');
insert into functional_expertise(name) values ('SQL Server 2014');
insert into functional_expertise(name) values ('SSRS');
insert into functional_expertise(name) values ('Storage');
insert into functional_expertise(name) values ('Struts');
insert into functional_expertise(name) values ('Syspro');
insert into functional_expertise(name) values ('Tableau');
insert into functional_expertise(name) values ('Targit');
insert into functional_expertise(name) values ('Test Director');
insert into functional_expertise(name) values ('Traffic');
insert into functional_expertise(name) values ('Trainer');
insert into functional_expertise(name) values ('UMTS');
insert into functional_expertise(name) values ('UX');
insert into functional_expertise(name) values ('VB.Net');
insert into functional_expertise(name) values ('WAN');
insert into functional_expertise(name) values ('XenServer');
insert into functional_expertise(name) values ('XHTML');
insert into functional_expertise(name) values ('XQuery');
insert into functional_expertise(name) values ('XSLT');
insert into functional_expertise(name) values ('.Net');
insert into functional_expertise(name) values ('.Net 2.0');
insert into functional_expertise(name) values ('.Net 3.5');
insert into functional_expertise(name) values ('Aberdeen');
insert into functional_expertise(name) values ('Actionscript 3.0');
insert into functional_expertise(name) values ('ADO.Net');
insert into functional_expertise(name) values ('AJAX');
insert into functional_expertise(name) values ('Baan');
insert into functional_expertise(name) values ('Bash');
insert into functional_expertise(name) values ('Board International');
insert into functional_expertise(name) values ('C++');
insert into functional_expertise(name) values ('CAT6');
insert into functional_expertise(name) values ('CCEE');
insert into functional_expertise(name) values ('Chaiwat');
insert into functional_expertise(name) values ('Change');
insert into functional_expertise(name) values ('Chief Technical Officer');
insert into functional_expertise(name) values ('Cisco (Gen)');
insert into functional_expertise(name) values ('Citrix');
insert into functional_expertise(name) values ('Cobol');
insert into functional_expertise(name) values ('Coins');
insert into functional_expertise(name) values ('CSS3');
insert into functional_expertise(name) values ('Cucumber');
insert into functional_expertise(name) values ('Databases');
insert into functional_expertise(name) values ('Datawarehouse');
insert into functional_expertise(name) values ('DB2');
insert into functional_expertise(name) values ('Delphi');
insert into functional_expertise(name) values ('Developer/Programmer');
insert into functional_expertise(name) values ('Discoverer');
insert into functional_expertise(name) values ('Document Controller');
insert into functional_expertise(name) values ('DOJO');
insert into functional_expertise(name) values ('Dplyr');
insert into functional_expertise(name) values ('Embedded C');
insert into functional_expertise(name) values ('ERP');
insert into functional_expertise(name) values ('Fedora');
insert into functional_expertise(name) values ('Fife');
insert into functional_expertise(name) values ('Financial Director');
insert into functional_expertise(name) values ('FMEA');
insert into functional_expertise(name) values ('German');
insert into functional_expertise(name) values ('GIS');
insert into functional_expertise(name) values ('Group Policy');
insert into functional_expertise(name) values ('HAZOP');
insert into functional_expertise(name) values ('HPUX');
insert into functional_expertise(name) values ('HP-UX');
insert into functional_expertise(name) values ('HR');
insert into functional_expertise(name) values ('HTML5');
insert into functional_expertise(name) values ('Hyperion');
insert into functional_expertise(name) values ('IFS');
insert into functional_expertise(name) values ('Iterative');
insert into functional_expertise(name) values ('JDeveloper');
insert into functional_expertise(name) values ('JSF');
insert into functional_expertise(name) values ('JUnit');
insert into functional_expertise(name) values ('Jython');
insert into functional_expertise(name) values ('LAN');
insert into functional_expertise(name) values ('Lean/6 Sigma');
insert into functional_expertise(name) values ('Microsoft BI');
insert into functional_expertise(name) values ('Mobile Development');
insert into functional_expertise(name) values ('Monitoring');
insert into functional_expertise(name) values ('MooTools');
insert into functional_expertise(name) values ('Movex');
insert into functional_expertise(name) values ('MVC');
insert into functional_expertise(name) values ('NetAct');
insert into functional_expertise(name) values ('NetScaler');
insert into functional_expertise(name) values ('Networking');
insert into functional_expertise(name) values ('NSN');
insert into functional_expertise(name) values ('Oil And Gas');
insert into functional_expertise(name) values ('Olap');
insert into functional_expertise(name) values ('OO');
insert into functional_expertise(name) values ('Oracle 10g');
insert into functional_expertise(name) values ('Oracle 11g');
insert into functional_expertise(name) values ('Oracle 11gR2');
insert into functional_expertise(name) values ('Oracle Dev (Gen)');
insert into functional_expertise(name) values ('Oracle Flashback');
insert into functional_expertise(name) values ('Oracle OCA');
insert into functional_expertise(name) values ('Panorama');
insert into functional_expertise(name) values ('Performance Testing');
insert into functional_expertise(name) values ('Perl');
insert into functional_expertise(name) values ('Perth');
insert into functional_expertise(name) values ('Pharma');
insert into functional_expertise(name) values ('PHP (General)');
insert into functional_expertise(name) values ('PMO');
insert into functional_expertise(name) values ('Prairie');
insert into functional_expertise(name) values ('Programme Manager');
insert into functional_expertise(name) values ('PS Core');
insert into functional_expertise(name) values ('Qlikview');
insert into functional_expertise(name) values ('Retail');
insert into functional_expertise(name) values ('Ruby on Rails');
insert into functional_expertise(name) values ('Salesforce');
insert into functional_expertise(name) values ('Samba');
insert into functional_expertise(name) values ('SAP BI');
insert into functional_expertise(name) values ('SAP CRM Interaction Centre');
insert into functional_expertise(name) values ('SAP Financials');
insert into functional_expertise(name) values ('SBS');
insert into functional_expertise(name) values ('Scala');
insert into functional_expertise(name) values ('Service Delivery Manager');
insert into functional_expertise(name) values ('Siebel');
insert into functional_expertise(name) values ('Siebel BI');
insert into functional_expertise(name) values ('Silverlight');
insert into functional_expertise(name) values ('Spring');
insert into functional_expertise(name) values ('SQL');
insert into functional_expertise(name) values ('SQL Server Compact');
insert into functional_expertise(name) values ('SSAS');
insert into functional_expertise(name) values ('Stirling');
insert into functional_expertise(name) values ('Sugar');
insert into functional_expertise(name) values ('Systems Testing');
insert into functional_expertise(name) values ('Test Manager');
insert into functional_expertise(name) values ('Tester');
insert into functional_expertise(name) values ('TFS');
insert into functional_expertise(name) values ('Tibco');
insert into functional_expertise(name) values ('T-SQL');
insert into functional_expertise(name) values ('UAT');
insert into functional_expertise(name) values ('Unit Testing');
insert into functional_expertise(name) values ('Unix Dev (Gen)');
insert into functional_expertise(name) values ('UNIX/LINUX');
insert into functional_expertise(name) values ('Utilities');
insert into functional_expertise(name) values ('VMODEL');
insert into functional_expertise(name) values ('WCF');
insert into functional_expertise(name) values ('Windows Desktop');
insert into functional_expertise(name) values ('XenApp');
insert into functional_expertise(name) values ('Yellowfin');
