--/
CREATE FUNCTION FN_SUBSTRING_INDEX 
    (
       @TEXTO NVARCHAR(200),
      @SUBSTRING_INDEX NVARCHAR(10),
       @DESPLAZAMIENTO INT
    )
    RETURNS NVARCHAR(200)
    AS

    BEGIN


        DECLARE @indiceSubstring INT
        DECLARE @RESULTADO NVARCHAR(200)
        SELECT @indiceSubstring = CHARINDEX(@SUBSTRING_INDEX,@TEXTO)

        IF @DESPLAZAMIENTO > 0
        BEGIN
            SELECT @RESULTADO=SUBSTRING(@TEXTO,@indiceSubstring+@DESPLAZAMIENTO+1,LEN(@TEXTO))
        END 
        ELSE
        BEGIN
            SELECT @RESULTADO=SUBSTRING(@TEXTO,0,@indiceSubstring-@DESPLAZAMIENTO-1)
        END 

    RETURN @RESULTADO
    END

/
