/****** Object:  Table [dbo].[VC_Countries]    Script Date: 12/22/2016 11:34:12 AM ******/
DROP TABLE if exists [dbo].[VC_Countries]
GO
/****** Object:  Table [dbo].[VC_Countries]    Script Date: 12/22/2016 11:34:12 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[VC_Countries](
	[COUNTRY] [varchar](50) NULL,
	[ABBREVIATION] [varchar](50) NULL,
	[CODE] [varchar](50) NULL
) --ON [BULLHORN_DATA]

GO
SET ANSI_PADDING OFF
GO
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'United States', N'US', N'1')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Afghanistan', N'AF', N'2185')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Albania', N'AL', N'2186')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Algeria', N'DZ', N'2187')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Andorra', N'AD', N'2188')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Angola', N'AO', N'2189')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Antartica', N'AQ', N'2190')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Antigua and Barbuda', N'AG', N'2191')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Argentina', N'AR', N'2192')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Armenia', N'AM', N'2193')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Australia', N'AU', N'2194')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Austria', N'AT', N'2195')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Azerbaijan', N'AZ', N'2196')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Bahamas', N'BS', N'2197')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Bahrain', N'BH', N'2198')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Bangladesh', N'BD', N'2199')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Barbados', N'BB', N'2200')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Belarus', N'BY', N'2201')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Belgium', N'BE', N'2202')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Belize', N'BZ', N'2203')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Benin', N'BJ', N'2204')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Bhutan', N'BT', N'2205')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Bolivia', N'BO', N'2206')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Bosnia Hercegovina', N'BA', N'2207')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Botswana', N'BW', N'2208')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Brazil', N'BR', N'2209')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Brunei Darussalam', N'BN', N'2210')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Bulgaria', N'BG', N'2211')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Burkina Faso', N'BF', N'2212')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Burundi', N'BI', N'2213')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Cambodia', N'KH', N'2214')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Cameroon', N'CM', N'2215')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Canada', N'CA', N'2216')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Cape Verde', N'CV', N'2217')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Central African Republic', N'CF', N'2218')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Chad', N'TD', N'2219')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Chile', N'CL', N'2220')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'China', N'CN', N'2221')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Columbia', N'CO', N'2222')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Comoros', N'KM', N'2223')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Costa Rica', N'CR', N'2226')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Cote d''Ivoire', N'CO', N'2227')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Croatia', N'HR', N'2228')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Cuba', N'CU', N'2229')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Cyprus', N'CY', N'2230')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Czech Republic', N'CZ', N'2231')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Denmark', N'DK', N'2232')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Djibouti', N'DJ', N'2233')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Dominica', N'DM', N'2234')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Dominican Republic', N'DO', N'2235')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Ecuador', N'EC', N'2236')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Egypt', N'EG', N'2237')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'El Salvador', N'SV', N'2238')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Equatorial Guinea', N'GQ', N'2239')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Eritrea', N'ER', N'2240')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Estonia', N'EE', N'2241')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Ethiopia', N'ET', N'2242')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Fiji', N'FJ', N'2243')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Finland', N'FI', N'2244')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'France', N'FR', N'2245')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Gabon', N'GA', N'2246')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Georgia', N'GE', N'2248')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Germany', N'DE', N'2249')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Ghana', N'GH', N'2250')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Greece', N'GR', N'2251')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Greenland', N'GL', N'2252')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Grenada', N'GD', N'2253')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Guinea', N'GN', N'2255')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Guinea-Bissau', N'GW', N'2256')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Guyana', N'GY', N'2257')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Haiti', N'HT', N'2258')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Honduras', N'HN', N'2259')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Hungary', N'HU', N'2260')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Iceland', N'IS', N'2261')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'India', N'IN', N'2262')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Indonesia', N'ID', N'2263')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Iran', N'IR', N'2264')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Iraq', N'IQ', N'2265')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Ireland', N'IE', N'2266')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Israel', N'IL', N'2267')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Italy', N'IT', N'2268')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Jamaica', N'JM', N'2269')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Japan', N'JP', N'2270')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Jordan', N'JO', N'2271')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Kazakhstan', N'KZ', N'2272')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Kenya', N'KE', N'2273')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Korea; Democratic People''s Republic Of (North)', N'KP', N'2274')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Korea; Republic Of (South)', N'KR', N'2275')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Kuwait', N'KW', N'2276')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Kyrgyzstan', N'KG', N'2277')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Lao People''s Democratic Republic', N'LA', N'2278')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Latvia', N'LV', N'2279')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Lebanon', N'LB', N'2280')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Lesotho', N'LS', N'2281')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Liberia', N'LR', N'2282')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Liechtenstein', N'LI', N'2284')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Lithuania', N'LT', N'2285')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Luxembourg', N'LU', N'2286')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Macau', N'MO', N'2287')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Macedonia', N'MK', N'2288')
GO
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Madagascar', N'MG', N'2289')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Malawi', N'MW', N'2290')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Malaysia', N'MY', N'2291')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Mali', N'ML', N'2292')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Malta', N'MT', N'2293')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Mauritania', N'MR', N'2294')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Mauritius', N'MU', N'2295')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Mexico', N'MX', N'2296')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Micronesia; Federated States of', N'FM', N'2297')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Monaco', N'MC', N'2299')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Mongolia', N'MN', N'2300')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Morocco', N'MA', N'2301')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Mozambique', N'MZ', N'2302')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Myanmar', N'MM', N'2303')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Namibia', N'NA', N'2304')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Nepal', N'NP', N'2305')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Netherlands', N'NL', N'2306')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'New Zealand', N'NZ', N'2307')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Nicaragua', N'NI', N'2308')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Niger', N'NE', N'2309')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Nigeria', N'NG', N'2310')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Norway', N'NO', N'2311')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Oman', N'OM', N'2312')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Pakistan', N'PK', N'2313')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Palau', N'PW', N'2314')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Panama', N'PA', N'2315')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Papua New Guinea', N'PG', N'2316')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Paraguay', N'PY', N'2317')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Peru', N'PE', N'2318')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Philippines', N'PH', N'2319')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Poland', N'PL', N'2320')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Portugal', N'PT', N'2321')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Qatar', N'QA', N'2322')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Romania', N'RO', N'2323')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Russian Federation', N'RU', N'2324')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Rwanda', N'RW', N'2325')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Saint Lucia', N'LC', N'2326')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'San Marino', N'SM', N'2327')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Saudi Arabia', N'SA', N'2328')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Senegal', N'SN', N'2329')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Seychelles', N'SC', N'2331')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Sierra Leone', N'SL', N'2332')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Singapore', N'SG', N'2333')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Slovakia', N'SK', N'2334')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Slovenia', N'SI', N'2335')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Solomon Islands', N'SB', N'2336')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Somalia', N'SO', N'2337')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'South Africa', N'ZA', N'2338')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Spain', N'ES', N'2339')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Sri Lanka', N'LK', N'2340')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Sudan', N'SD', N'2341')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Suriname', N'SR', N'2342')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Swaziland', N'SZ', N'2343')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Sweden', N'SE', N'2344')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Switzerland', N'CH', N'2345')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Tajikistan', N'TJ', N'2348')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Tanzania', N'TZ', N'2349')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Thailand', N'TH', N'2350')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Togo', N'TG', N'2351')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Trinidad and Tobago', N'TT', N'2352')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Tunisia', N'TN', N'2353')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Turkey; Republic of', N'TR', N'2354')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Turkmenistan', N'TM', N'2355')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Uganda', N'UG', N'2356')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Ukraine', N'UA', N'2357')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'United Arab Emirates', N'AE', N'2358')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'United Kingdom', N'GB', N'2359')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Uruguay', N'UY', N'2360')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Uzbekistan', N'UZ', N'2361')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Vatican City', N'VA', N'2362')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Venezuela', N'VE', N'2363')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Vietnam', N'VN', N'2364')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Yugoslavia', N'YU', N'2367')
--INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Zaire', N'ZR', N'2368')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Zambia', N'ZM', N'2369')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Zimbabwe', N'ZW', N'2370')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Guatemala', N'GT', N'2371')
--INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Bermuda', N'BU', N'2372')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Aruba', N'AB', N'2373')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Puerto Rico', N'PR', N'2374')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Taiwan', N'TW', N'2375')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Guam', N'GU', N'2376')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Hong Kong SAR', N'', N'2377')
--INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'None Specified', N'', N'2378')
INSERT [dbo].[VC_Countries] ([COUNTRY], [ABBREVIATION], [CODE]) VALUES (N'Cayman Islands', N'KY', N'2379')
