--CREATE COMPANY
CREATE TABLE [dbo].[Company] (
[LastModifiedDate] datetime,
[LeadStatus] nvarchar(max),
[CompanyID] int PRIMARY KEY,
[PostalCode] nvarchar(max),
[CompanyDomainName] nvarchar(max),
[RecentDealCloseDate] date,
[TimeofLastSession] datetime,
[CloseDate] datetime,
[OfficeModel] nvarchar(max),
[AssociatedDeals] int,
[RecentDealAmount] float,
[FirstConversionDate] datetime,
[OriginalSourceType] nvarchar(max),
[FirstDealCreatedDate] datetime,
[OtherSource] nvarchar(max),
[FacebookCompanyPage] nvarchar(max),
[CreateDate] datetime,
[LinkedInBio] nvarchar(max),
[FirstConversion] nvarchar(max),
[City] nvarchar(max),
[Name] nvarchar(max),
[Numberofchildcompanies] int,
[PhoneNumber] nvarchar(max),
[HubSpotOwner] nvarchar(max),
[AboutUs] nvarchar(max),
[LastActivityDate] datetime,
[NextActivityDate] datetime,
[State_Region] nvarchar(max),
[LinkedInCompanyPage] nvarchar(max),
[RecentConversionDate] datetime,
[LifecycleStage] nvarchar(max),
[LastContacted] datetime,
[StreetAddress] nvarchar(max),
[RecentConversion] nvarchar(max),
[HubSpotTeam] nvarchar(max),
[TwitterBio] nvarchar(max),
[WebTechnologies] nvarchar(max),
[Country] nvarchar(max),
[FTE] nvarchar(max),
[OfficeLocation] nvarchar(max),
[FirstContactCreateDate] datetime,
[TimeZone] nvarchar(max),
[AssignedBDM] nvarchar(max),
[WebsiteURL] nvarchar(max),
[YearFounded] int,
[TwitterHandle] nvarchar(max),
[GooglePlusPage] nvarchar(max),
[Description] nvarchar(max),
[AnnualRevenue] int,
[Industry] nvarchar(max),
[StreetAddress2] nvarchar(max),
[IsPublic] nvarchar(max),
[ParentCompany] nvarchar(max),
[CompanyStatus] nvarchar(max)
)

--CREATE CONTACT
CREATE TABLE [dbo].[Contact] (
[FirstName] nvarchar(max),
[LastName] nvarchar(max),
[Fullname] nvarchar(max),
[ContactID] int PRIMARY KEY,
[Lastemailname] nvarchar(max),
[EmailsOpened] int,
[LeadStatus] nvarchar(max),
[TotalRevenue] float,
[PostalCode] nvarchar(max),
[RecentDealCloseDate] datetime,
[NumberofPageviews] int,
[BecameaMarketingQualifiedLeadDate] datetime,
[SkypeID] nvarchar(max),
[LastMeetingBookedCampaign] nvarchar(max),
[CloseDate] datetime,
[Message] nvarchar(max),
[AssociatedDeals] int,
[OurThinkingSubscription] nvarchar(max),
[RecentDealAmount] float,
[DefaultHubSpotBlogSubscription] nvarchar(max),
[Numberoftimescontacted] int,
[NumberofSalesActivities] int,
[FirstConversionDate] datetime,
[RecentSalesEmailClickedDate] datetime,
[RecentSalesEmailOpenedDate] datetime,
[OriginalSource] nvarchar(max),
[Position] nvarchar(max),
[FirstDealCreatedDate] datetime,
[Currentlyinworkflow] nvarchar(max),
[LastMeetingBookedMedium] nvarchar(max),
[CreateDate] datetime,
[LinkedInBio] nvarchar(max),
[FirstConversion] nvarchar(max),
[BecameaSalesQualifiedLeadDate] datetime,
[LastMeetingBooked] datetime,
[City] nvarchar(max),
[MobilePhoneNumber] nvarchar(max),
[Numberofeventcompletions] int,
[PhoneNumber] nvarchar(max),
[BecameaSubscriberDate] datetime,
[EmailConfirmationStatus] nvarchar(max),
[HubSpotOwner] nvarchar(max),
[EventRevenue] int,
[LastActivityDate] datetime,
[NextActivityDate] datetime,
[LastMeetingBookedSource] nvarchar(max),
[State_Region] nvarchar(max),
[BecameanOpportunityDate] datetime,
[Lastemailopendate] datetime,
[Optedoutofallemail] nvarchar(max),
[OriginalSourceDrill_Down1] nvarchar(max),
[Lastemailsenddate] datetime,
[RecentConversionDate] datetime,
[BecameanOtherLifecycleDate] datetime,
[OriginalSourceDrill_Down2] nvarchar(max),
[LifecycleStage] nvarchar(max),
[LastContacted] datetime,
[StreetAddress] nvarchar(max),
[RecentConversion] nvarchar(max),
[Country] nvarchar(max),
[LinkedInConnections] int,
[Persona] nvarchar(max),
[Salutation] nvarchar(max),
[SendsSinceLastEngagement] int,
[BecameaCustomerDate] datetime,
[BecameaLeadDate] datetime,
[RecentSalesEmailRepliedDate] datetime,
[WebsiteURL] nvarchar(max),
[JobTitle] nvarchar(max),
[HubSpotScore] int,
[TwitterUsername] nvarchar(max),
[FirstReferringSite] nvarchar(max),
[LastReferringSite] nvarchar(max),
[TwitterProfilePhoto] nvarchar(max),
[DaysToClose] int,
[Email] nvarchar(max),
[CompanyName] nvarchar(max),
[AnnualRevenue] int,
[FaxNumber] nvarchar(max),
[Industry] nvarchar(max),
[Firstemailsenddate] datetime,
[EmailAddressQuarantined] nvarchar(max),
[NumberofEmployees] int,
[EmailsBounced] int,
[AssociatedCompanyID] int,
[AssociatedCompany] nvarchar(max),
[ContactStatus] nvarchar(max)
)

--CREATE DEALSALES
CREATE TABLE [dbo].[DealSales] (
[DealID] int PRIMARY KEY,
[ClosedWonReason] nvarchar(max),
[LastModifiedDate] datetime,
[Pipeline] nvarchar(max),
[CloseDate] datetime,
[DealType] nvarchar(max),
[OfficeModel] nvarchar(max),
[OriginalSourceType] nvarchar(max),
[CreateDate] datetime,
[ClosedLostReason] nvarchar(max),
[HubSpotOwner] nvarchar(max),
[LastActivityDate] datetime,
[OwnerAssignedDate] datetime,
[DealStage] nvarchar(max),
[NumberofContacts] int,
[OriginalSourceData1] nvarchar(max),
[OriginalSourceData2] nvarchar(max),
[HubSpotTeam] nvarchar(max),
[DealName] nvarchar(max),
[FTE] nvarchar(max),
[Amount] float,
[OfficeLocation] nvarchar(max),
[AssignedBDM] nvarchar(max),
[DealDescription] nvarchar(max),
[AssociatedCompanyID] int,
[AssociatedCompany] nvarchar(max),
[AssociatedContactID] int,
[AssociatedContacts] nvarchar(max)
)

--Create matched DB with production companies (company.csv)
CREATE TABLE [dbo].[MatchedPRODCompany] (
[DBCompanyID] int PRIMARY KEY,
[CompanyName] nvarchar(max),
[PRODVCID] int
)

--Create matched DB with production contacts (contact.csv)
CREATE TABLE [dbo].[AssignPRODContact] (
[AssignContactID] int PRIMARY KEY,
[AssociatedCompanyID] int,
[CompanyName] nvarchar(max),
[Fullname] nvarchar(max),
[MatchedVCId] int,
[ContactStatus] nvarchar(max)
)

--Create new contact added based on DealSales -> NewcontactAdded sheet
CREATE TABLE [dbo].[NewContactAdded] (
[DealID] int,
[ClosedWonReason] nvarchar(max),
[LastModifiedDate] datetime,
[Pipeline] nvarchar(max),
[CloseDate] datetime,
[DealType] nvarchar(max),
[OfficeModel] nvarchar(max),
[OriginalSourceType] nvarchar(max),
[CreateDate] datetime,
[ClosedLostReason] nvarchar(max),
[HubSpotOwner] nvarchar(max),
[LastActivityDate] datetime,
[OwnerAssignedDate] datetime,
[DealStage] nvarchar(max),
[NumberofContacts] int,
[OriginalSourceData1] nvarchar(max),
[OriginalSourceData2] nvarchar(max),
[HubSpotTeam] nvarchar(max),
[DealName] nvarchar(max),
[FTE] nvarchar(max),
[Amount] float,
[OfficeLocation] nvarchar(max),
[AssignedBDM] nvarchar(max),
[DealDescription] nvarchar(max),
[AssociatedCompanyID] int,
[AssociatedCompany] nvarchar(max),
[AssociatedContactID] int,
[AssociatedContacts] nvarchar(max),
[NewDefaultContactWMail] nvarchar(max),
[NewContactID] int PRIMARY KEY,
[DefaultFirstNameWithMail] nvarchar(max),
[DefaultLastNameWithMail] nvarchar(max)
)

--Create new contact added based on DealSales -> NewDefaultContact sheet
CREATE TABLE [dbo].[NewDefaultContact] (
[DealID] int,
[DealStage] nvarchar(max),
[AssociatedCompanyID] int,
[AssociatedCompany] nvarchar(max),
[newDefaultContactID] int PRIMARY KEY,
[NewDefaultFirstname] nvarchar(max),
[NewDefaultLastname] nvarchar(max)
)

--PRODUCTION jobs
CREATE TABLE [dbo].[ClosedWon] (
[JobID] int PRIMARY KEY,
[JobName] nvarchar(max),
[VCCompanyID] int,
[VCCompanyName] nvarchar(max),
[VCContactID] int,
[VCContactFirstname] nvarchar(max),
[VCContactLastname] nvarchar(max),
[VCContactEmail] nvarchar(max)
)
