import pandas as pd
country_codes = {
    'AF': ('afghanistan', 'af', 'Afghan'),
    'AX': ('aland islands', 'ax'),
    'AL': ('albania', 'al', 'Albanian'),
    'DZ': ('algeria', 'algerian'),
    'AS': ('american samoa',),
    'AD': ('andorra',),
    'AO': ('angola', 'Angolan'),
    'AI': ('anguilla',),
    'AQ': ('antarctica',),
    'AG': ('antigua and barbuda',),
    'AR': ('argentina', 'Argintena', 'Argentinean'),
    'AM': ('armenia',),
    'AW': ('aruba',),
    'AU': ('australia', 'australian', 'Australian (with British Passport)', 'Australians'),
    'AT': ('austria', 'Austrian'),
    'AZ': ('azerbaijan', 'Azeris', 'Azerbaijani'),
    'BS': ('bahamas',),
    'BH': ('bahrain', 'Bahraini', ),
    'BD': ('bangladesh', 'Bangladeshi'),
    'BB': ('barbados',),
    'BY': ('belarus', 'Belarusian'),
    'BE': ('belgium', 'Belgian'),
    'BZ': ('belize',),
    'BJ': ('benin', 'Beninese'),
    'BM': ('bermuda',),
    'BT': ('bhutan',),
    'BO': ('bolivia',),
    'BA': ('bosnia and herzegovina',),
    'BW': ('botswana',),
    'BV': ('bouvet island',),
    'BR': ('brazil', 'Brazilian', ),
    'VG': ('british virgin islands',),
    'IO': ('british indian ocean territory',),
    'BN': ('brunei darussalam',),
    'BG': ('bulgaria', 'bulgarian'),
    'BF': ('burkina faso',),
    'BI': ('burundi',),
    'KH': ('cambodia', 'Cambodian'),
    'CM': ('cameroon', 'Cameroonian'),
    'CA': ('canada', 'EU / Canadian', 'Canadian (UK Ancestry Visa)', 'Canadian'),
    'CV': ('cape verde',),
    'KY': ('cayman islands',),
    'CF': ('central african republic',),
    'TD': ('chad',),
    'CL': ('chile', 'Chilean'),
    'CN': ('china', 'chinese'),
    'HK': ('hong kong , sar china', 'hong kong', 'Hong Konger'),
    'MO': ('macao , sar china',),
    'CX': ('christmas island',),
    'CC': ('cocos (keeling) islands',),
    'CO': ('colombia', 'Colombian'),
    'KM': ('comoros',),
    'CG': ('congo (brazzaville)', 'Congolese'),
    'CD': ('congo , (kinshasa)',),
    'CK': ('cook islands',),
    'CR': ('costa rica', 'Costa Rican'),
    'CI': ("côte d'ivoire", 'Ivorian'),
    'HR': ('croatia', 'Croatian'),
    'CU': ('cuba',),
    'CY': ('cyprus', 'Cypriot'),
    'CZ': ('czech republic', 'Czech'),
    'DK': ('denmark', 'Danish'),
    'DJ': ('djibouti',),
    'DM': ('dominica',),
    'DO': ('dominican republic', 'Dominican'),
    'EC': ('ecuador', 'Ecuadorean'),
    'EG': ('egypt', 'Egyptian'),
    'SV': ('el salvador', 'Salvadoran'),
    'GQ': ('equatorial guinea',),
    'ER': ('eritrea',),
    'EE': ('estonia', 'Estonian'),
    'ET': ('ethiopia', 'Ethiopian'),
    'FK': ('falkland islands (malvinas)',),
    'FO': ('faroe islands',),
    'FJ': ('fiji', 'Fijian'),
    'FI': ('finland', 'Finnish'),
    'FR': ('france', 'French (EU Passport Holder)', 'french'),
    'GF': ('french guiana',),
    'PF': ('french polynesia',),
    'TF': ('french southern territories',),
    'GA': ('gabon',),
    'GM': ('gambia', 'Gambian'),
    'GE': ('georgia', 'Georgian'),
    'DE': ('germany', 'german',),
    'GH': ('ghana', 'Ghanaian', 'Ghanaians'),
    'GI': ('gibraltar',),
    'GR': ('greece', 'greek', ),
    'GL': ('greenland',),
    'GD': ('grenada',),
    'GP': ('guadeloupe',),
    'GU': ('guam',),
    'GT': ('guatemala', 'Guatemalan'),
    'GG': ('guernsey', 'Guernsey Resident', 'Local Market Guernsey Resident'),
    'GN': ('guinea',),
    'GW': ('guinea-bissau',),
    'GY': ('guyana',),
    'HT': ('haiti',),
    'HM': ('heard and mcdonald islands',),
    'VA': ('holy see (vatican city state)',),
    'HN': ('honduras',),
    'HU': ('hungary', 'Hungarian'),
    'IS': ('iceland', 'Icelander'),
    'IN': ('india', 'indian', 'Indians'),
    'ID': ('indonesia', 'Indonesian', ),
    'IR': ('iran, islamic republic of', 'Iranian'),
    'IQ': ('iraq', 'Iraqi'),
    'IE': ('ireland', 'irish', 'eire', 'Dublin'),
    'IM': ('isle of man',),
    'IL': ('israel', 'Israeli', 'Israelis'),
    'IT': ('italy', 'italian', 'Italians'),
    'JM': ('jamaica', 'Jamaica (Caricom National)'),
    'JP': ('japan', 'Japanese'),
    'JE': ('jersey',),
    'JO': ('jordan', 'Jordanian'),
    'KZ': ('kazakhstan', 'Kazakhstani'),
    'KE': ('kenya', 'Kenyan'),
    'KI': ('kiribati',),
    'KP': ('korea (north)',),
    'KR': ('korea (south)', 'south korea', 'Korean', 'South Korean',),
    'KW': ('kuwait',),
    'KG': ('kyrgyzstan',),
    'LA': ('lao pdr', 'lao', 'laos'),
    'LV': ('latvia', 'Latvian'),
    'LB': ('lebanon', 'Lebanese'),
    'LS': ('lesotho',),
    'LR': ('liberia',),
    'LY': ('libya', 'LIBYAN ARAB JAMAHIRIYA', 'Libyan'),
    'LI': ('liechtenstein',),
    'LT': ('lithuania', 'lithuanian'),
    'LU': ('luxembourg',),
    'MK': ('macedonia, republic of', 'Macedonian', 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF'),
    'MG': ('madagascar', 'Malagasy'),
    'MW': ('malawi',),
    'MY': ('malaysia', 'malaysian'),
    'MV': ('maldives',),
    'ML': ('mali',),
    'MT': ('malta',),
    'MH': ('marshall islands',),
    'MQ': ('martinique',),
    'MR': ('mauritania',),
    'MU': ('mauritius', 'Mauritian'),
    'YT': ('mayotte',),
    'MX': ('mexico', 'Mexican'),
    'FM': ('micronesia, federated states of',),
    'MD': ('moldova', 'MOLDOVA, REPUBLIC OF'),
    'MC': ('monaco',),
    'MN': ('mongolia', 'Mongolian'),
    'ME': ('montenegro',),
    'MS': ('montserrat',),
    'MA': ('morocco', 'moroccan'),
    'MZ': ('mozambique',),
    'MM': ('myanmar', 'Burmese'),
    'NA': ('namibia',),
    'NR': ('nauru',),
    'NP': ('nepal', 'Nepalese'),
    'NL': ('netherlands', 'dutch'),
    'AN': ('netherlands antilles',),
    'NC': ('new caledonia',),
    'NZ': ('new zealand', 'New Zealander'),
    'NI': ('nicaragua',),
    'NE': ('niger',),
    'NG': ('nigeria', 'Nigerian', 'Nigerien'),
    'NU': ('niue',),
    'NF': ('norfolk island',),
    'MP': ('northern mariana islands',),
    'NO': ('norway', 'Norwegian'),
    'OM': ('oman', 'Omani'),
    'PK': ('pakistan','pakistani'),
    'PW': ('palau',),
    'PS': ('palestinian territory',),
    'PA': ('panama', 'Panamanian', 'Panamanian'),
    'PG': ('papua new guinea', 'Papua New Guinean', 'Guinean'),
    'PY': ('paraguay',),
    'PE': ('peru', 'Peruvian'),
    'PH': ('philippines', 'Filipino', 'Filipinos'),
    'PN': ('pitcairn',),
    'PL': ('poland', 'polish'),
    'PT': ('portugal', 'Portuguese'),
    'PR': ('puerto rico', 'Puerto Rican'),
    'QA': ('qatar',),
    'RE': ('réunion',),
    'RO': ('romania', 'Romanian'),
    'RU': ('russian federation', 'russian'),
    'RW': ('rwanda', 'Rwandan', ),
    'BL': ('saint-barthélemy',),
    'SH': ('saint helena',),
    'KN': ('saint kitts and nevis',),
    'LC': ('saint lucia',),
    'MF': ('saint-martin (french part)',),
    'PM': ('saint pierre and miquelon',),
    'VC': ('saint vincent and grenadines',),
    'WS': ('samoa',),
    'SM': ('san marino',),
    'ST': ('sao tome and principe',),
    'SA': ('saudi arabia', 'Saudi Arabian'),
    'SN': ('senegal',),
    'RS': ('serbia', 'SERBIA AND MONTENEGRO', 'Serbian'),
    'SC': ('seychelles',),
    'SL': ('sierra leone', 'Sierra Leonean'),
    'SG': ('singapore', 'Singaporean', 'Singaporeans'),
    'SK': ('slovakia', 'Slovakian', 'Slovak'),
    'SI': ('slovenia', 'Slovenian', 'Slovene'),
    'SB': ('solomon islands',),
    'SO': ('somalia',),
    'ZA': ('south africa', 'South African', 'South Africa/Irish', 'Namibian', 'South Africans'),
    'GS': ('south georgia and the south sandwich islands',),
    'SS': ('south sudan',),
    'ES': ('spain', 'Spanish'),
    'LK': ('sri lanka', 'sri lankan'),
    'SD': ('sudan', 'Sudanese'),
    'SR': ('suriname', 'Surinamer',),
    'SJ': ('svalbard and jan mayen islands',),
    'SZ': ('swaziland',),
    'SE': ('sweden', 'swedish'),
    'CH': ('switzerland', 'Swiss'),
    'SY': ('syrian arab republic (syria)', 'Syrian', 'Syrian'),
    'TW': ('taiwan , republic of china', 'taiwan', 'Taiwanese', 'TAIWAN, PROVINCE OF CHINA'),
    'TJ': ('tajikistan',),
    'TZ': ('tanzania , united republic of', 'Tanzanian'),
    'TH': ('thailand', 'thai', 'Thais'),
    'TL': ('timor-leste',),
    'TG': ('togo',),
    'TK': ('tokelau',),
    'TO': ('tonga',),
    'TT': ('trinidad and tobago',),
    'TN': ('tunisia', 'Tunisian'),
    'TR': ('turkey', 'Turkish'),
    'TM': ('turkmenistan',),
    'TC': ('turks and caicos islands',),
    'TV': ('tuvalu',),
    'UG': ('uganda', 'Ugandan'),
    'UA': ('ukraine', 'ukrainian'),
    'AE': ('united arab emirates', 'Emirati'),
    'GB': ('united kingdom', 'unitedkingdom', 'london', 'derby', 'uk', 'british', 'british/egyptian', 'british/belfast', 'english', 'British Citizen - Licence Required', 'British (Local)', 'British Citizen (Local Market Guernsey Resident)', 'Brtish Citizen (Local Guernsey Market Resident)', 'British and Turkish', 'British and Indian'),
    'US': ('united states of america', 'united states', 'american', 'US', 'USA (ILR in UK)', 'Americans'),
    'UM': ('us minor outlying islands',),
    'UY': ('uruguay', 'Uruguayan'),
    'UZ': ('uzbekistan',),
    'VU': ('vanuatu',),
    'VE': ('venezuela (bolivarian republic)', 'Venezuelan'),
    'VN': ('viet nam', 'Vietnamese'),
    'VI': ('virgin islands, us',),
    'WF': ('wallis and futuna islands',),
    'EH': ('western sahara',),
    'YE': ('yemen',),
    'ZM': ('zambia', 'Zambian'),
    'ZW': ('zimbabwe', 'Zimbabwean'),

}

ccode = []
cdes = []
for k, v in country_codes.items():
    ccode.append(k)
    cdes.append(';'.join(v))

df_country_codes = pd.DataFrame({'country_code': ccode, 'country_name_desc': cdes})
