import pandas as pd
country_codes = {
    'AF': ('afghanistan', 'af'),
    'AX': ('aland islands', 'ax'),
    'AL': ('albania', 'al'),
    'DZ': ('algeria', 'algerian'),
    'AS': ('american samoa',),
    'AD': ('andorra',),
    'AO': ('angola',),
    'AI': ('anguilla',),
    'AQ': ('antarctica',),
    'AG': ('antigua and barbuda',),
    'AR': ('argentina', 'Argintena'),
    'AM': ('armenia',),
    'AW': ('aruba',),
    'AU': ('australia', 'australian', 'Australian (with British Passport)','AU','Aitutaki'),
    'AT': ('austria', 'Austrian'),
    'AZ': ('azerbaijan', 'Azeris', 'Azerbajan'),
    'BS': ('bahamas',),
    'BH': ('bahrain',),
    'BD': ('bangladesh', 'Bangladeshi'),
    'BB': ('barbados',),
    'BY': ('belarus',),
    'BE': ('belgium', 'Belgian','Belguim'),
    'BZ': ('belize',),
    'BJ': ('benin',),
    'BM': ('bermuda',),
    'BT': ('bhutan',),
    'BO': ('bolivia',),
    'BA': ('bosnia and herzegovina','Bosnia-Herzegovina'),
    'BW': ('botswana',),
    'BV': ('bouvet island',),
    'BR': ('brazil','Brazilian'),
    'VG': ('british virgin islands',),
    'IO': ('british indian ocean territory',),
    'BN': ('brunei darussalam',),
    'BG': ('bulgaria', 'bulgarian'),
    'BF': ('burkina faso',),
    'BI': ('burundi',),
    'KH': ('cambodia',),
    'CM': ('cameroon',),
    'CA': ('canada', 'EU / Canadian', 'Canadian (UK Ancestry Visa)', 'Canadian'),
    'CV': ('cape verde',),
    'KY': ('cayman islands',),
    'CF': ('central african republic',),
    'TD': ('chad',),
    'CL': ('chile',),
    'CN': ('china', 'chinese'),
    'HK': ('hong kong , sar china', 'hong kong'),
    'MO': ('macao , sar china',),
    'CX': ('christmas island',),
    'CC': ('cocos (keeling) islands',),
    'CO': ('colombia', 'Colombian'),
    'KM': ('comoros',),
    'CG': ('congo (brazzaville)','Congo','Zaire'),
    'CD': ('congo , (kinshasa)',),
    'CK': ('cook islands',),
    'CR': ('costa rica',),
    'CI': ("côte d'ivoire","Cote d'Ivoire",'Ivory Coast'),
    'HR': ('croatia', 'Croatian','Kroatien'),
    'CU': ('cuba',),
    'CY': ('cyprus', 'Cypriot'),
    'CZ': ('czech republic','Czech'),
    'DK': ('denmark', 'Danish'),
    'DJ': ('djibouti',),
    'DM': ('dominica',),
    'DO': ('dominican republic',),
    'EC': ('ecuador',),
    'EG': ('egypt','Egypy'),
    'SV': ('el salvador',),
    'GQ': ('equatorial guinea',),
    'ER': ('eritrea',),
    'EE': ('estonia', 'Estonian'),
    'ET': ('ethiopia',),
    'FK': ('falkland islands (malvinas)',),
    'FO': ('faroe islands',),
    'FJ': ('fiji',),
    'FI': ('finland', 'Finnish'),
    'FR': ('france', 'French (EU Passport Holder)', 'french', 'French','Frankreich','Reunion'),
    'GF': ('french guiana',),
    'PF': ('french polynesia',),
    'TF': ('french southern territories',),
    'GA': ('gabon',),
    'GM': ('gambia', 'Gambian'),
    'GE': ('georgia', 'Georgian','Georgia  Republic of'),
    'DE': ('germany', 'german','Deutschland','Germany, Deutschland'),
    'GH': ('ghana','Ghanaian'),
    'GI': ('gibraltar',),
    'GR': ('greece', 'greek', ),
    'GL': ('greenland',),
    'GD': ('grenada',),
    'GP': ('guadeloupe',),
    'GU': ('guam',),
    'GT': ('guatemala',),
    'GG': ('guernsey', 'Guernsey Resident', 'Local Market Guernsey Resident'),
    'GN': ('guinea','République de Guinée'),
    'GW': ('guinea-bissau','Guine-bissau'),
    'GY': ('guyana',),
    'HT': ('haiti',),
    'HM': ('heard and mcdonald islands',),
    'VA': ('holy see (vatican city state)',),
    'HN': ('honduras',),
    'HU': ('hungary', 'Hungarian'),
    'IS': ('iceland',),
    'IN': ('india', 'indian'),
    'ID': ('indonesia',),
    'IR': ('iran, islamic republic of','Iran'),
    'IQ': ('iraq',),
    'IE': ('ireland', 'irish', 'eire', 'Dublin', 'Republic of Ireland'),
    'IM': ('isle of man',),
    'IL': ('israel', 'Israeli'),
    'IT': ('italy', 'italian', ),
    'JM': ('jamaica', 'Jamaica (Caricom National)','Jamaica','Jamaican'),
    'JP': ('japan',),
    'JE': ('jersey',),
    'JO': ('jordan',),
    'KZ': ('kazakhstan','Kazachstan'),
    'KE': ('kenya',),
    'KI': ('kiribati',),
    'KP': ('korea (north)',),
    'KR': ('korea (south)', 'south korea', 'Korean','Korea, Republic of','Korea','Korea South'),
    'KW': ('kuwait',),
    'KG': ('kyrgyzstan','Kyrgystan'),
    'LA': ('lao pdr','Laos'),
    'LV': ('latvia', 'Latvian'),
    'LB': ('lebanon', 'Lebanese','Libanon'),
    'LS': ('lesotho',),
    'LR': ('liberia',),
    'LY': ('libya', 'LIBYAN ARAB JAMAHIRIYA'),
    'LI': ('liechtenstein',),
    'LT': ('lithuania', 'lithuanian'),
    'LU': ('luxembourg',),
    'MK': ('macedonia, republic of', 'Macedonian', 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','Macedonia  Republic of'),
    'MG': ('madagascar',),
    'MW': ('malawi','Malawian'),
    'MY': ('malaysia', 'malaysian'),
    'MV': ('maldives',),
    'ML': ('mali',),
    'MT': ('malta',),
    'MH': ('marshall islands',),
    'MQ': ('martinique',),
    'MR': ('mauritania',),
    'MU': ('mauritius', 'Mauritian'),
    'YT': ('mayotte',),
    'MX': ('mexico',),
    'FM': ('micronesia, federated states of','Micronesia'),
    'MD': ('moldova', 'MOLDOVA, REPUBLIC OF'),
    'MC': ('monaco',),
    'MN': ('mongolia',),
    'ME': ('montenegro',),
    'MS': ('montserrat',),
    'MA': ('morocco', 'moroccan','Marokko'),
    'MZ': ('mozambique',),
    'MM': ('myanmar',),
    'NA': ('namibia','Namibian'),
    'NR': ('nauru',),
    'NP': ('nepal',),
    'NL': ('netherlands', 'dutch','The Netherlands','Niederlande','Holland'),
    'AN': ('netherlands antilles',),
    'BQ': ('Bonaire, Sint Eustatius and Saba',),
    'NC': ('new caledonia',),
    'NZ': ('new zealand', 'New Zealander','NZ','Nz','New Zealand '),
    'NI': ('nicaragua',),
    'NE': ('niger',),
    'NG': ('nigeria', 'Nigerian'),
    'NU': ('niue',),
    'NF': ('norfolk island',),
    'MP': ('northern mariana islands',),
    'NO': ('norway', 'Norwegian'),
    'OM': ('oman', 'Omani'),
    'PK': ('pakistan','pakistani'),
    'PW': ('palau',),
    'PS': ('palestinian territory','Palästinensische Autonomiegebiete'),
    'PA': ('panama',),
    'PG': ('papua new guinea',),
    'PY': ('paraguay',),
    'PE': ('peru','Peruvian'),
    'PH': ('philippines', 'Filipino'),
    'PN': ('pitcairn',),
    'PL': ('poland', 'polish'),
    'PT': ('portugal', 'Portuguese','Portugese'),
    'PR': ('puerto rico',),
    'QA': ('qatar',),
    'RE': ('réunion',),
    'RO': ('romania', 'Romanian'),
    'RU': ('russian federation', 'russian', 'Russia','USSR'),
    'RW': ('rwanda',),
    'BL': ('saint-barthélemy',),
    'SH': ('saint helena',),
    'KN': ('saint kitts and nevis',),
    'LC': ('saint lucia',),
    'MF': ('saint-martin (french part)',),
    'PM': ('saint pierre and miquelon',),
    'VC': ('saint vincent and grenadines',),
    'WS': ('samoa',),
    'SM': ('san marino',),
    'ST': ('sao tome and principe',),
    'SA': ('saudi arabia','SA','sa','Rep of S.A.','Rep of SA '),
    'SN': ('senegal',),
    'RS': ('serbia', 'SERBIA AND MONTENEGRO','Yugoslavia','Serbien'),
    'SC': ('seychelles',),
    'SL': ('sierra leone',),
    'SG': ('singapore', 'Singaporean'),
    'SK': ('slovakia', 'Slovakian'),
    'SI': ('slovenia', 'Slovenian'),
    'SB': ('solomon islands',),
    'SO': ('somalia',),
    'ZA': ('south africa', 'South African', 'South Africa/Irish','South Africa','RSA','Johannesburg','Sout Africa','Soutyh Africa','Jhb','Rep of South Africa'),
    'GS': ('south georgia and the south sandwich islands',),
    'SS': ('south sudan',),
    'ES': ('spain', 'Spanish','Spanien'),
    'LK': ('sri lanka', 'sri lankan'),
    'SD': ('sudan',),
    'SR': ('suriname',),
    'SJ': ('svalbard and jan mayen islands',),
    'SZ': ('swaziland',),
    'SE': ('sweden', 'swedish'),
    'CH': ('switzerland', 'Swiss','Switzerlsnd'),
    'SY': ('syrian arab republic (syria)','Syrian Arab Republic','Syria'),
    'TW': ('taiwan , republic of china', 'taiwan', 'Taiwanese', 'TAIWAN, PROVINCE OF CHINA'),
    'TJ': ('tajikistan',),
    'TZ': ('tanzania , united republic of','Tanzania'),
    'TH': ('thailand',),
    'TL': ('timor-leste',),
    'TG': ('togo',),
    'TK': ('tokelau',),
    'TO': ('tonga',),
    'TT': ('trinidad and tobago','Trinidad & Tobago','Trinidad'),
    'TN': ('tunisia','Tunisian'),
    'TR': ('turkey', 'Turkish','Türkei'),
    'TM': ('turkmenistan',),
    'TC': ('turks and caicos islands',),
    'TV': ('tuvalu',),
    'UG': ('uganda','Ugandan'),
    'UA': ('ukraine', 'ukrainian'),
    'AE': ('united arab emirates','UAE','Dubai','Vereinigte Arabische Emirate','KSA','Saudi Arabia (KSA)','Abu Dhabi'),
    'GB': ('united kingdom', 'unitedkingdom', 'london', 'derby', 'uk', 'british', 'british/egyptian', 'british/belfast', 'British Citizen - Licence Required', 'British (Local)', 'British Citizen (Local Market Guernsey Resident)', 'Brtish Citizen (Local Guernsey Market Resident)'
           , 'British and Turkish', 'British and Indian', 'UK', 'Scotland', 'Wales', 'england', 'England','Northern Ireland','South Wales','Großbritannien','Alderney','British Antarctic Territory','Ascension Island'),
    'US': ('united states of america', 'united states', 'american', 'US', 'USA (ILR in UK)', 'USA','AMerica','america','U.S.A.','America','Virgin Islands'),
    'UM': ('us minor outlying islands',),
    'UY': ('uruguay',),
    'UZ': ('uzbekistan',),
    'VU': ('vanuatu',),
    'VE': ('venezuela (bolivarian republic)','Venezuela'),
    'VN': ('viet nam', 'Vietnamese', 'Vietnam','HCMC'),
    'VI': ('virgin islands, us',),
    'WF': ('wallis and futuna islands',),
    'EH': ('western sahara',),
    'YE': ('yemen',),
    'ZM': ('zambia',),
    'ZW': ('zimbabwe',),
    'en': ('english',),

}

ccode = []
cdes = []
for k, v in country_codes.items():
    ccode.append(k)
    cdes.append(';'.join(v))

df_country_codes = pd.DataFrame({'country_code': ccode, 'country_name_desc': cdes})
