select et.CREATEDDATE, *
from ENTITY_TABLE et
INNER JOIN PROP_PERSON_GEN AS person_gen ON et.ENTITY_ID = person_gen.REFERENCE
LEFT OUTER JOIN PROP_CAND_GEN on PROP_CAND_GEN.REFERENCE = person_gen.REFERENCE
INNER JOIN LK_ENTITY_ROLE AS lk_er ON et.ENTITY_ID = lk_er.ENTITY_ID AND lk_er.DEFAULT_ROLE = 'D' AND lk_er.ROLE_ID IN (108, 110, 6920556, 111) 
INNER JOIN MD_ROLES AS md_r ON lk_er.ROLE_ID = md_r.ROLE_ID
where PROP_CAND_GEN.STATUS in (8249174,1306760,8249176,8257080,1306780)
and et.CREATEDDATE > '2017-04-30'
and md_r.CONFIG_ROLE_NAME in ('PERM_CAND','TEMP_CAND','CONTR_CAND','CONTACT')

/*
Candidate from 01/05/2017: 1051 rows including

OK 	STATUS	DESCRIPTION
OK 	1306760	Registered
	1306766	Registration Incomplete
	1306772	Uncontactable
	1306775	Do not use
OK 	1306780	Self Suited
OK 	8249174	Active
	8249175	Unsuitable
OK 	8249176	Placed by Us
OK 	8257080	Temping for Us
	8257111	Working for a Competitor
	8257112	Found Own Role
	8257113	Not Available

CONFIG_ROLE_NAME	(No of candidates)
CONTACT			10
CONTR_CAND		28
PERM_CAND		911
TEMP_CAND		102

*/

---Item 20 & 21: Salary reference: 1051 results
PROP_CAND_PREF	SALARY_DES
PROP_CAND_PREF	SALARY_REQ

select person_gen.REFERENCE, md_r.CONFIG_ROLE_NAME, PROP_CAND_PREF.SALARY_DES, PROP_CAND_PREF.SALARY_REQ, PROP_CAND_PREF.OTE_REQ, PROP_CAND_PREF.RATE_DES
, PROP_CAND_PREF.RATE_REQ, PROP_CAND_PREF.LOOK_FOR, PROP_CAND_PREF.P_PERM, PROP_CAND_PREF.P_TEMP, PROP_CAND_PREF.P_CONTR
from ENTITY_TABLE et
INNER JOIN PROP_PERSON_GEN AS person_gen ON et.ENTITY_ID = person_gen.REFERENCE
LEFT OUTER JOIN PROP_CAND_GEN on PROP_CAND_GEN.REFERENCE = person_gen.REFERENCE
INNER JOIN LK_ENTITY_ROLE AS lk_er ON et.ENTITY_ID = lk_er.ENTITY_ID AND lk_er.DEFAULT_ROLE = 'D' AND lk_er.ROLE_ID IN (108, 110, 6920556, 111) 
INNER JOIN MD_ROLES AS md_r ON lk_er.ROLE_ID = md_r.ROLE_ID
LEFT JOIN PROP_CAND_PREF on PROP_CAND_PREF.REFERENCE = PROP_CAND_GEN.REFERENCE
where PROP_CAND_GEN.STATUS in (8249174,1306760,8249176,8257080,1306780)
and et.CREATEDDATE > '2017-04-30'
and md_r.CONFIG_ROLE_NAME in ('PERM_CAND','TEMP_CAND','CONTR_CAND','CONTACT')


---PLACED candidates after 01/05/2018
-----NO DATE FILTER: 37 RESULTS
select SHORT_CAND.CANDIDATE, PROP_PERSON_GEN.FULLNAME, SHORT_CAND.JOB, PROP_JOB_GEN.JOB_TITLE, SHORTLIST, DESCRIPTION 
from PROP_X_SHORT_CAND SHORT_CAND
INNER JOIN PROP_SHORT_GEN SHORT_GEN ON SHORT_GEN.REFERENCE = SHORT_CAND.SHORTLIST 
INNER JOIN MD_MULTI_NAMES MN ON MN.ID = SHORT_GEN.STATUS
INNER JOIN PROP_PERSON_GEN ON PROP_PERSON_GEN.REFERENCE = SHORT_CAND.CANDIDATE
INNER JOIN PROP_JOB_GEN ON PROP_JOB_GEN.REFERENCE = SHORT_CAND.JOB
WHERE MN.LANGUAGE = 1
and DESCRIPTION = 'Placed By Us'
--and exists (select REFERENCE from PROP_CAND_GEN where PROP_CAND_GEN.REFERENCE = SHORT_CAND.CANDIDATE and PROP_CAND_GEN.STATUS = 8249176)


----DATE FILTER: 14 RESULTS
select SHORT_CAND.CANDIDATE, PROP_PERSON_GEN.FULLNAME, SHORT_CAND.JOB, PROP_JOB_GEN.JOB_TITLE, SHORTLIST, DESCRIPTION 
from PROP_X_SHORT_CAND SHORT_CAND
INNER JOIN PROP_SHORT_GEN SHORT_GEN ON SHORT_GEN.REFERENCE = SHORT_CAND.SHORTLIST 
INNER JOIN MD_MULTI_NAMES MN ON MN.ID = SHORT_GEN.STATUS
INNER JOIN PROP_PERSON_GEN ON PROP_PERSON_GEN.REFERENCE = SHORT_CAND.CANDIDATE
INNER JOIN PROP_JOB_GEN ON PROP_JOB_GEN.REFERENCE = SHORT_CAND.JOB
INNER JOIN ENTITY_TABLE ET ON ET.ENTITY_ID = PROP_PERSON_GEN.REFERENCE
WHERE MN.LANGUAGE = 1
AND DESCRIPTION = 'Placed By Us'
AND ET.CREATEDDATE > '2017-04-30'