
with t as (
select --top 20
 c.CVID as 'candidate-ExternalId'
, c.FirstName as 'candidate-FirstName'
, c.MiddleName as 'candidate-MiddleName'
, c.Surname as 'candidate-Lastname'
, c.Nationality
, case 
		when c.Nationality like 'African%' then 'ZA'
		when c.Nationality like 'America%' then 'US'
		when c.Nationality like 'Angolan%' then 'AO'
		when c.Nationality like 'Austral%' then 'AU'
		when c.Nationality like 'Austria%' then 'AT'
		when c.Nationality like 'Belgium%' then 'BE'
		when c.Nationality like 'Botswan%' then 'BW'
		when c.Nationality like 'British%' then 'GB'
		when c.Nationality like 'Camaroo%' then 'CM'
		when c.Nationality like 'Canadia%' then 'CA'
		when c.Nationality like 'Chinese%' then 'MO'
		when c.Nationality like 'Congole%' then 'CD'
		when c.Nationality like 'Cuban%' then 'CU'
		when c.Nationality like 'Czech%' then 'CZ'
		when c.Nationality like 'Dutch%' then 'NL'
		when c.Nationality like 'Eritrea%' then 'ER'
		when c.Nationality like 'French%' then 'FR'
		when c.Nationality like 'German%' then 'DE'
		when c.Nationality like 'Ghanaia%' then 'GH'
		when c.Nationality like 'Indian%' then 'IN'
		when c.Nationality like 'Irish%' then 'IE'
		when c.Nationality like 'Italian%' then 'IT'
		when c.Nationality like 'Kenyan%' then 'KE'
		when c.Nationality like 'Malagas%' then 'MG'
		when c.Nationality like 'Maurita%' then 'MR'
		when c.Nationality like 'Mauriti%' then 'MU'
		when c.Nationality like 'Mozambi%' then 'MZ'
		when c.Nationality like 'Namibia%' then 'NA'
		when c.Nationality like 'Nigeria%' then 'NG'
		when c.Nationality like 'Pakista%' then 'PK'
		when c.Nationality like 'Philipp%' then 'PH'
		when c.Nationality like 'Polish%' then 'PL'
		when c.Nationality like 'Portuge%' then 'PT'
		when c.Nationality like 'Russian%' then 'RU'
		when c.Nationality like 'Saudi%' then 'SA'
		when c.Nationality like 'Somali%' then 'SO'
		when c.Nationality like 'Swazi%' then 'SZ'
		when c.Nationality like 'Swiss%' then 'CH'
		when c.Nationality like 'Tanzani%' then 'TZ'
		when c.Nationality like 'Ugandan%' then 'UG'
		when c.Nationality like 'Zaïre%' then 'ZR'
		when c.Nationality like 'Zambian%' then 'ZM'
		when c.Nationality like 'Zealand%' then 'NZ'
		when c.Nationality like 'Zimbabw%' then 'ZW'
		when c.Nationality like '%UNITED%ARAB%' then 'AE'
		when c.Nationality like '%UAE%' then 'AE'
		when c.Nationality like '%U.A.E%' then 'AE'
		when c.Nationality like '%UNITED%KINGDOM%' then 'GB'
		when c.Nationality like '%UNITED%STATES%' then 'US'
		when c.Nationality like '%US%' then 'US'
       else '' end as 'candidate-Citizenship'
from candidates c
--where Nationality <> 'South African'
--c.CVID = 2147399424
)

select distinct "candidate-Citizenship" from t