
select top 10 * from PROP_X_CLIENT_CON order by CONTACT
select top 10 * from PROP_PERSON_GEN order by REFERENCE

--select CLIENT from PROP_X_CLIENT_CON where client = 394865
--select CONTACT from PROP_X_CLIENT_CON order by CONTACT
--select LAST_NAME from PROP_PERSON_GEN
--select FIRST_NAME from PROP_PERSON_GEN
--select top 1000 * from PROP_EMAIL  order by REFERENCE

--select JOB_TITLE,REFERENCE from PROP_PERSON_GEN
select top 10 * from PROP_PERSON_GEN  order by REFERENCE


--select LINKED_IN from PROP_PERSON_GEN
select top 10 *  from PROP_PERSON_GEN order by REFERENCE


SELECT * FROM DOCUMENTS
where DOC_CATEGORY =6532841 --and OWNER_ID = <<PROP_PERSON_GEN.REFERENCE>>

select top 10 * from PROP_TELEPHONE

select  *
from PROP_TELEPHONE TEL INNER JOIN
MD_NAMED_OCCS OCC ON OCC.OCC_ID= TEL.OCC_ID
where CONFIG_NAME = 'Mobile' --and TEL.REFERENCE = <<PROP_PERSON_GEN.REFERENCE>>

select  *
from PROP_ADDRESS ADDRESS 
INNER JOIN MD_NAMED_OCCS OCC ON OCC.OCC_ID= ADDRESS.OCC_ID
--where CONFIG_NAME = 'Primary' --and ADDRESS.REFERENCE = <<PROP_CLIENT_GEN.REFERENCE>>

select top 10 * from PROP_ADDRESS order by REFERENCE
select top 10 * from MD_NAMED_OCCS order by OCC_ID


select * EMPLOYEE.NAME as ConsName
from PROP_PERSON_GEN PERSON_GEN INNER JOIN
PROP_OWN_CONS CONS ON PERSON_GEN.REFERENCE = CONS.REFERENCE INNER JOIN
MD_NAMED_OCCS OCC ON OCC.OCC_ID= CONS.OCC_ID INNER JOIN
PROP_EMPLOYEE_GEN EMPLOYEE ON EMPLOYEE.USER_REF = CONS.CONSULTANT
where CONFIG_NAME = 'Permanent' and CONS.REFERENCE = 10629 --AND PERSON_GEN.REFERENCE = <<PROP_PERSON_GEN.REFERENCE>>

select  *
from PROP_TELEPHONE TEL INNER JOIN
MD_NAMED_OCCS OCC ON OCC.OCC_ID= TEL.OCC_ID
where CONFIG_NAME = 'Work' --and TEL.REFERENCE = <<PROP_PERSON_GEN.REFERENCE>>