select CONTACT from PROP_X_CLIENT_JOB where contact = 10014 --order by CONTACT 
select top 10 * from PROP_X_CLIENT_JOB order by JOB
select top 10 *  from PROP_JOB_GEN order by RATE_TYPE desc
select JOB from PROP_X_CLIENT_JOB
select JOB_TITLE from PROP_JOB_GEN

--select * EMPLOYEE.NAME as ConsName
select top 50 *
from PROP_JOB_GEN JOB_GEN 
INNER JOIN PROP_OWN_CONS CONS ON JOB_GEN.REFERENCE = CONS.REFERENCE 
INNER JOIN MD_NAMED_OCCS OCC ON OCC.OCC_ID= CONS.OCC_ID 
INNER JOIN PROP_EMPLOYEE_GEN EMPLOYEE ON EMPLOYEE.USER_REF = CONS.CONSULTANT
where CONFIG_NAME = 'Permanent' --and CONS.REFERENCE = 10629 --AND JOB_GEN.REFERENCE = <<PROP_JOB_GEN.REFERENCE>>

select distinct CONSULTANT from PROP_OWN_CONS --order by CONSULTANT

select CURRENCY from PROP_JOB_GEN

select * from PROP_PJOB_GEN
select SAL_FROM from PROP_PJOB_GEN

SELECT top 200 * FROM DOCUMENTS
--where DOC_CATEGORY =6532862 --and OWNER_ID = <<PROP_JOB_GEN.REFERENCE>>


select START_DT from PROP_JOB_GEN order by START_DT desc
select END_DT from PROP_JOB_GEN order by END_DT desc
select CLIENT from PROP_X_CLIENT_JOB
