CREATE TABLE [dbo].[Company] (
[DynamicDataId] int,
[LastUpdatedByuserId] int,
[LastUpdatedByEmail] nvarchar(max),
[LastUpdatedDate] date,
[CompanyName] nvarchar(max),
[OfficeTelNo] nvarchar(max),
[Website] nvarchar(max),
[Add1] nvarchar(max),
[Add2] nvarchar(max),
[Town] nvarchar(max),
[Country] nvarchar(max),
[Postcode] nvarchar(max),
[Division] nvarchar(max),
[Industry] nvarchar(max),
[CompStatus] nvarchar(max),
[NoofEmp] nvarchar(max),
[AgreedRate] nvarchar(max),
[TermsSent] nvarchar(max),
[TermsSigned] nvarchar(max),
[AdditionalInfo] nvarchar(max),
[BuildingName] nvarchar(max),
[CompanyRegNo] nvarchar(max),
[altbuilding] nvarchar(max),
[altadd1] nvarchar(max),
[altadd2] nvarchar(max),
[alttown] nvarchar(max),
[altpostcode] nvarchar(max),
[altcountry] nvarchar(max),
[branchbuilding] nvarchar(max),
[branchadd1] nvarchar(max),
[branchadd2] nvarchar(max),
[branchtown] nvarchar(max),
[branchpostcode] nvarchar(max),
[branchcountry] nvarchar(max),
[FurtherInfo] nvarchar(max),
[CreatedDate] nvarchar(max)
)

CREATE TABLE [dbo].[Contact] (
[DynamicDataId] int,
[LastUpdatedByuserId] int,
[LastUpdatedByEmail] nvarchar(max),
[LastUpdatedDate] date,
[Name] nvarchar(max),
[FirstName] nvarchar(max),
[LastName] nvarchar(max),
[Company] nvarchar(max),
[CompayId] nvarchar(max),
[Tel] nvarchar(max),
[Mobile] nvarchar(max),
[Fax] nvarchar(max),
[Email] nvarchar(max),
[Position] nvarchar(max),
[Extn] nvarchar(max),
[knownAs] nvarchar(max),
[Division] nvarchar(max),
[CreatedDate] nvarchar(max)
)

CREATE TABLE [dbo].[Vacancy] (
[DynamicDataId] int,
[LastUpdatedByuserId] int,
[LastUpdatedByEmail] nvarchar(max),
[LastUpdatedDate] date,
[JobTitle] nvarchar(max),
[Consultant] nvarchar(max),
[Company] nvarchar(max),
[CompanyId] nvarchar(max),
[Contact] nvarchar(max),
[ContactId] nvarchar(max),
[VacancyStatus] nvarchar(max),
[VacancyType] nvarchar(max),
[Description] nvarchar(max),
[SkillSet] nvarchar(max),
[JobSpecNotes] nvarchar(max),
[Other] nvarchar(max),
[Source] nvarchar(max),
[NumberofPositions] int,
[RateTo] nvarchar(max),
[CurrencyCode] nvarchar(max),
[IssuedOn] nvarchar(max),
[BuildingName] nvarchar(max),
[Add1] nvarchar(max),
[Add2] nvarchar(max),
[Town] nvarchar(max),
[City] nvarchar(max),
[County] nvarchar(max),
[PostCode] nvarchar(max),
[Country] nvarchar(max),
[ContractRate] nvarchar(max),
[ContractLength] nvarchar(max),
[Hours] nvarchar(max),
[Fee] nvarchar(max),
[checkeddate] nvarchar(max),
[checked] nvarchar(max),
[QAinfo] nvarchar(max),
[CreatedDate] nvarchar(max)
)

CREATE TABLE [dbo].[Candidate] (
[DynamicDataId] int,
[LastUpdatedByuserId] int,
[LastUpdatedBy] nvarchar(max),
[LastUpdatedDate] date,
[VCTitle] nvarchar(max),
[Name] nvarchar(max),
[FirstName] nvarchar(max),
[LastName] nvarchar(max),
[Nationality] nvarchar(max),
[HomeTel] nvarchar(max),
[Mobile] nvarchar(max),
[Email] nvarchar(max),
[Source] nvarchar(max),
[CurrentCompany] nvarchar(max),
[Salary] int,
[ReasonforLeaving] nvarchar(max),
[LookingFor] nvarchar(max),
[CurrentJobTitle] nvarchar(max),
[Started] nvarchar(max),
[ResponsibilitiesandAchievements] nvarchar(max),
[RolesHistory] nvarchar(max),
[InterviewNotes] nvarchar(max),
[References] nvarchar(max),
[Locations] nvarchar(max),
[Qualifications] nvarchar(max),
[JobFunction] nvarchar(max),
[Industry] nvarchar(max),
[Add1] nvarchar(max),
[Add2] nvarchar(max),
[Town] nvarchar(max),
[HomeProvince] nvarchar(max),
[Postcode] nvarchar(max),
[LinkedIn] nvarchar(max),
[DateofBirth] nvarchar(max),
[WorkPermit] nvarchar(max),
[Email2] nvarchar(max),
[Add3] nvarchar(max),
[City] nvarchar(max),
[Mobile2] nvarchar(max),
[FixedTermContract] int,
[Contract] int,
[Permanent] int,
[CreatedDate] nvarchar(max),
[IndustrySkills] nvarchar(max),
[JobFunctions] nvarchar(max)
)

CREATE TABLE [dbo].[Note] (
[Id] int,
[ParentId] int,
[Text] nvarchar(max),
[CreatedBy] int
)


CREATE TABLE [dbo].[Users] (
[Id] int,
[EmailAddress] nvarchar(max),
[FirstName] nvarchar(max),
[LastName] nvarchar(max)
)

CREATE TABLE [dbo].[Document] (
[Id] int,
[Folder] nvarchar(max),
[Filename] nvarchar(max),
[Description] nvarchar(max),
[CreatedByUserId] int,
[CreatedByEmail] nvarchar(max),
[DynamicDataId] int,
[PrimaryIndicator] int,
[CreatedDate] date
)


CREATE TABLE [dbo].[Interview] (
	[DynamicDataId] int,
	[LastUpdatedByuserId] int,
	[LastUpdatedByEmail] nvarchar(max),
	[LastUpdatedDate] date,
	[Reference] nvarchar(max),
	[Candidate] nvarchar(max),
	[CandidateID] int,
	[Vacancy] nvarchar(max),
	[VacancyID] int,
	[Consultant] nvarchar(max),
	[InterviewDate] nvarchar(max),
	[IntStatus] nvarchar(max),
	[LoggedBy] nvarchar(max),
	[Outcome] nvarchar(max),
	[Time_hh] int,
	[Time_mm] int,
	[CreatedDate] nvarchar(max)
)

