---CORRECT DATA FOR _Contacts_Part1.csv
select replace([ContactID],'"','') as [ContactID]
, replace([ContactStatus],'"','') as [ContactStatus]
, replace([FirstName],'"','') as [FirstName]
, replace([Surname],'"','') as [Surname]
, replace([HomeArea],'"','') as [HomeArea]
, replace([HomePhone],'"','') as [HomePhone]
, replace([MobileArea],'"','') as [MobileArea]
, replace([MobilePhone],'"','') as [MobilePhone]
, replace([HomeFax],'"','') as [HomeFax]
, replace([HomePhone1],'"','') as [HomePhone1]
, replace([PreferredName],'"','') as [PreferredName]
, replace([Email],'"','') as [Email]
, replace([DateOfBirth],'"','') as [DateOfBirth]
, replace([PostalAddress],'"','') as [PostalAddress]
, replace([HomeAddress],'"','') as [HomeAddress]
, replace([Suburb],'"','') as [Suburb]
, replace([State],'"','') as [State]
, replace([PostCode],'"','') as [PostCode]
, replace([StreetCountry],'"','') as [StreetCountry]
, replace([BranchID],'"','') as [BranchID]
, replace([Comments],'"','') as [Comments]
into ContactsInfo
from Contacts_Part1

---CORECT DATA FOR ActionHistory_Part1.csv
select replace([ActionCode],'"','') as [ActionCode]
, replace([BusinessProcess],'"','') as [BusinessProcess]
, replace([ActionID],'"','') as [ActionID]
, replace([Branch],'"','') as [Branch]
, replace([ClientID],'"','') as [ClientID]
, replace([ContactID],'"','') as [ContactID]
, replace([CandidateID],'"','') as [CandidateID]
, replace([JobID],'"','') as [JobID]
, replace([ConsultantID],'"','') as [ConsultantID]
, replace([DateOfAction],'"','') as [DateOfAction]
, replace([TimeOfAction],'"','') as [TimeOfAction]
, replace([Regarding],'"','') as [Regarding]
, replace([DateCommencing],'"','') as [DateCommencing]
, replace([PeriodEnding],'"','') as [PeriodEnding]
, replace([Salary],'"','') as [Salary]
, replace([InvoiceAmount],'"','') as [InvoiceAmount]
, replace([GST],'"','') as [GST]
, replace([InvoiceTotal],'"','') as [InvoiceTotal]
, replace([PayRate],'"','') as [PayRate]
, replace([ChargeRate],'"','') as [ChargeRate]
, replace([DateOfInterView],'"','') as [DateOfInterView]
, replace([TimeOfInterview],'"','') as [TimeOfInterview]
, replace([EmailAddress],'"','') as [EmailAddress]
, replace([Subject],'"','') as [Subject]
, replace([CC_EmailAddress],'"','') as [CC_EmailAddress]
, replace([Comments],'"','') as [Comments]
, replace([EmailBody],'"','') as [EmailBody]
into ActionHistoryPart1
from ActionHistory_Part1

--CORECT DATA FOR ActionHistory_Part2.csv
/* SPECIAL NOTES - FORMAT TYPE FOR THOSE COLUMNS
Regarding
CommencingDate
PeriodEnding
*/
select replace([ActionCode],'"','') as [ActionCode]
, replace([BusinessProcess],'"','') as [BusinessProcess]
, replace([ActionID],'"','') as [ActionID]
, replace([Branch],'"','') as [Branch]
, replace([ClientID],'"','') as [ClientID]
, replace([ContactID],'"','') as [ContactID]
, replace([CandidateID],'"','') as [CandidateID]
, replace([JobID],'"','') as [JobID]
, replace([ConsultantID],'"','') as [ConsultantID]
, replace([DateOfAction],'"','') as [DateOfAction]
, replace([TimeOfAction],'"','') as [TimeOfAction]
, replace([Regarding],'"','') as [Regarding]
, replace([DateCommencing],'"','') as [DateCommencing]
, replace([PeriodEnding],'"','') as [PeriodEnding]
, replace([Salary],'"','') as [Salary]
, replace([InvoiceAmount],'"','') as [InvoiceAmount]
, replace([GST],'"','') as [GST]
, replace([InvoiceTotal],'"','') as [InvoiceTotal]
, replace([PayRate],'"','') as [PayRate]
, replace([ChargeRate],'"','') as [ChargeRate]
, replace([DateOfInterView],'"','') as [DateOfInterView]
, replace([TimeOfInterview],'"','') as [TimeOfInterview]
, replace([EmailAddress],'"','') as [EmailAddress]
, replace([Subject],'"','') as [Subject]
, replace([CC_EmailAddress],'"','') as [CC_EmailAddress]
, replace([Comments],'"','') as [Comments]
, replace([EmailBody],'"','') as [EmailBody]
into ActionHistoryPart2
from ActionHistory_Part2
