SELECT
	TBL_COMPANY.COMPANYID AS 'COMPANYID',
	TBL_ADDRESS0.LINE1 AS 'ADDRESS_1',
	TBL_ADDRESS0.LINE2 AS 'ADDRESS_2',
	TBL_ADDRESS0.LINE3 AS 'ADDRESS_3',
	TBL_ADDRESS1.LINE1 AS 'BILLING_ADDRESS_1',
	TBL_ADDRESS1.LINE2 AS 'BILLING_ADDRESS_2',
	TBL_ADDRESS1.LINE3 AS 'BILLING_ADDRESS_3',
	TBL_ADDRESS1.CITY AS 'BILLING_CITY',
	TBL_ADDRESS1.COUNTRYNAME AS 'BILLING_COUNTRY',
	TBL_ADDRESS1.STATE AS 'BILLING_STATE',
	TBL_ADDRESS1.POSTALCODE AS 'BILLING_ZIP_CODE',
	TBL_ADDRESS0.CITY AS 'CITY',
	TBL_COMPANY.NAME AS 'COMPANY',
	TBL_COMPANY.DESCRIPTION AS 'COMPANY_DESCRIPTION',
	TBL_ADDRESS0.COUNTRYNAME AS 'COUNTRY',
	TBL_COMPANY.CREATEDATE AS 'CREATE_DATE',
	TBL_COMPANY.DIVISION AS 'DIVISION',
	TBL_COMPANY.EDITDATE AS 'EDIT_DATE',
	TBL_PHONE2.SUFFIX AS 'EXTENSION',
	TBL_PHONE3.SUFFIX AS 'FAX_EXTENSION',
	TBL_PHONE3.NUMBERDISPLAY AS 'FAX_PHONE',
	TBL_COMPANY.HASSUBCOMPANY AS 'HAS_DIVISIONS',
	TBL_COMPANY.HIERLEVEL AS 'HIERARCHY_LEVEL',
	TBL_COMPANY.CATEGORY AS 'ID/STATUS',
	TBL_COMPANY.IMPORTDATE AS 'IMPORT_DATE',
	TBL_COMPANY.INDUSTRY AS 'INDUSTRY',
	TBL_ACCESSOR4.NAME AS 'LAST_EDITED_BY',
	TBL_COMPANY.NUMEMPLOYEES AS 'NUMBER_OF_EMPLOYEES',
	TBL_COMPANY.PARENTCOMPANYID AS 'PARENTCOMPANYID',
	TBL_PHONE2.NUMBERDISPLAY AS 'PHONE',
	TBL_COMPANY.ISPRIVATE AS 'IS_PRIVATE',
	TBL_COMPANY.QUERYVERSIONID AS 'QUERYVERSIONID',
	TBL_ACCESSOR5.NAME AS 'RECORD_CREATOR',
	TBL_ACCESSOR6.NAME AS 'RECORD_MANAGER',
	TBL_COMPANY.REFERREDBY AS 'REFERRED_BY',
	TBL_COMPANY.REGION AS 'REGION',
	TBL_COMPANY.REVENUE AS 'REVENUE',
	TBL_ADDRESS7.LINE1 AS 'SHIPPING_ADDRESS_1',
	TBL_ADDRESS7.LINE2 AS 'SHIPPING_ADDRESS_2',
	TBL_ADDRESS7.LINE3 AS 'SHIPPING_ADDRESS_3',
	TBL_ADDRESS7.CITY AS 'SHIPPING_CITY',
	TBL_ADDRESS7.COUNTRYNAME AS 'SHIPPING_COUNTRY',
	TBL_ADDRESS7.STATE AS 'SHIPPING_STATE',
	TBL_ADDRESS7.POSTALCODE AS 'SHIPPING_ZIP_CODE',
	TBL_COMPANY.SICCODE AS 'SIC_CODE',
	TBL_ADDRESS0.STATE AS 'STATE',
	TBL_COMPANY.TERRITORY AS 'TERRITORY',
	TBL_COMPANY.TICKERSYMBOL AS 'TICKER_SYMBOL',
	TBL_PHONE8.SUFFIX AS 'TOLL_FREE_EXTENSION',
	TBL_PHONE8.NUMBERDISPLAY AS 'TOLL_FREE_PHONE',
	TBL_COMPANY.WEBADDRESS AS 'WEB_SITE',
	TBL_ADDRESS0.POSTALCODE AS 'ZIP_CODE'
FROM 	dbo.TBL_COMPANY
		LEFT OUTER JOIN dbo.TBL_ADDRESS TBL_ADDRESS0 ON (TBL_COMPANY.COMPANYID = TBL_ADDRESS0.COMPANYID AND TBL_ADDRESS0.TYPEID = '31BD07D5-4CB7-4038-9505-D2347AA530A1')
		LEFT OUTER JOIN dbo.TBL_ADDRESS TBL_ADDRESS1 ON (TBL_COMPANY.COMPANYID = TBL_ADDRESS1.COMPANYID AND TBL_ADDRESS1.TYPEID = '99E19E51-0C31-44EE-A9CD-2B55FB401384')
		LEFT OUTER JOIN dbo.TBL_PHONE TBL_PHONE2 ON (TBL_COMPANY.COMPANYID = TBL_PHONE2.COMPANYID AND TBL_PHONE2.TYPEID = 'C3AE9586-6158-4D0D-9FAF-253CB0152F18')
		LEFT OUTER JOIN dbo.TBL_PHONE TBL_PHONE3 ON (TBL_COMPANY.COMPANYID = TBL_PHONE3.COMPANYID AND TBL_PHONE3.TYPEID = '2870C5A5-7B3B-49DE-AD57-763EA3BF41D0')
		LEFT OUTER JOIN dbo.TBL_ACCESSOR TBL_ACCESSOR4 ON (TBL_COMPANY.EDITUSERID = TBL_ACCESSOR4.ACCESSORID)
		INNER JOIN dbo.TBL_ACCESSOR TBL_ACCESSOR5 ON (TBL_COMPANY.CREATEUSERID = TBL_ACCESSOR5.ACCESSORID)
		INNER JOIN dbo.TBL_ACCESSOR TBL_ACCESSOR6 ON (TBL_COMPANY.MANAGEUSERID = TBL_ACCESSOR6.ACCESSORID)
		LEFT OUTER JOIN dbo.TBL_ADDRESS TBL_ADDRESS7 ON (TBL_COMPANY.COMPANYID = TBL_ADDRESS7.COMPANYID AND TBL_ADDRESS7.TYPEID = 'ABECED80-4C4F-410E-949D-612C311AF3E6')
		LEFT OUTER JOIN dbo.TBL_PHONE TBL_PHONE8 ON (TBL_COMPANY.COMPANYID = TBL_PHONE8.COMPANYID AND TBL_PHONE8.TYPEID = '17057633-4B31-4AE8-BE33-ED27C7FD1B12')
order by TBL_COMPANY.COMPANYID
