select top 50 * from PROP_ADDRESS ADDRESS INNER JOIN MD_NAMED_OCCS OCC ON OCC.OCC_ID= ADDRESS.OCC_ID --where ADDRESS.REFERENCE = 394866 and CONFIG_NAME = 'Primary'

select * from PROP_TELEPHONE TEL INNER JOIN MD_NAMED_OCCS OCC ON OCC.OCC_ID= TEL.OCC_ID where CONFIG_NAME = 'Work2' and TEL.REFERENCE = 394899
select * from PROP_TELEPHONE TEL INNER JOIN MD_NAMED_OCCS OCC ON OCC.OCC_ID= TEL.OCC_ID where CONFIG_NAME = 'Work' and TEL.REFERENCE = 394899
select * from PROP_TELEPHONE TEL INNER JOIN MD_NAMED_OCCS OCC ON OCC.OCC_ID= TEL.OCC_ID where CONFIG_NAME = 'Fax' and TEL.REFERENCE = 394899

SELECT * FROM DOCUMENTS where DOC_CATEGORY =31185 --and OWNER_ID = <<PROP_CLIENT_GEN.REFERENCE>>
select * EMPLOYEE.NAME as ConsName from PROP_CLIENT_GEN CLIENT_GEN INNER JOIN PROP_OWN_CONS CONS ON CLIENT_GEN.REFERENCE = CONS.REFERENCE INNER JOIN MD_NAMED_OCCS OCC ON OCC.OCC_ID= CONS.OCC_ID INNER JOIN PROP_EMPLOYEE_GEN EMPLOYEE ON EMPLOYEE.USER_REF = CONS.CONSULTANT where CONFIG_NAME = 'Permanent' and CONS.REFERENCE = 10629 --AND PERSON_GEN.REFERENCE = <<PROP_CLIENT_GEN.REFERENCE>>

select * from PROP_EMPLOYEE_GEN order by reference
select top 100 * from PROP_CLIENT_GEN

select top 50 * from PROP_CLIENT_GEN cg
select distinct status from PROP_CLIENT_GEN cg order by status


select * EMPLOYEE.NAME as ConsName
from PROP_CLIENT_GEN CLIENT_GEN INNER JOIN
PROP_OWN_CONS CONS ON CLIENT_GEN.REFERENCE = CONS.REFERENCE INNER JOIN
MD_NAMED_OCCS OCC ON OCC.OCC_ID= CONS.OCC_ID INNER JOIN
PROP_EMPLOYEE_GEN EMPLOYEE ON EMPLOYEE.USER_REF = CONS.CONSULTANT
where CONFIG_NAME = 'Permanent' and CONS.REFERENCE = 10629 --AND PERSON_GEN.REFERENCE = <<PROP_CLIENT_GEN.REFERENCE>>"
