select  *
from PROP_ADDRESS ADDRESS INNER JOIN
MD_NAMED_OCCS OCC ON OCC.OCC_ID= ADDRESS.OCC_ID
where CONFIG_NAME = 'Primary' --and ADDRESS.REFERENCE = <<PROP_PERSON_GEN.REFERENCE>>

select top 1000 * from PROP_CAND_PREF .SALARY.CURR

 PROP_PERSON_GEN

select *
from DOCUMENTS
where DOC_CATEGORY = 6532839 --and OWNER_ID = <<PROP_PERSON_GEN.REFERENCE>>

select *
from PROP_ADDRESS ADDRESS INNER JOIN
MD_NAMED_OCCS OCC ON OCC.OCC_ID= ADDRESS.OCC_ID
where CONFIG_NAME = 'Primary' --and ADDRESS.REFERENCE = <<PROP_PERSON_GEN.REFERENCE>>

SELECT MN.DESCRIPTION as Currency FROM PROP_PERSON_GEN PERSON_GEN INNER JOIN
MD_MULTI_NAMES MN ON MN.ID = PERSON_GEN.CURRENCY

select *
from PROP_TELEPHONE TEL INNER JOIN
MD_NAMED_OCCS OCC ON OCC.OCC_ID= TEL.OCC_ID
where CONFIG_NAME = 'Home' --and TEL.REFERENCE = <<PROP_PERSON_GEN.REFERENCE>>

select  *
from PROP_TELEPHONE TEL INNER JOIN
MD_NAMED_OCCS OCC ON OCC.OCC_ID= TEL.OCC_ID
where CONFIG_NAME = 'Mobile' --and TEL.REFERENCE = <<PROP_PERSON_GEN.REFERENCE>>

select *
from DOCUMENTS
where DOC_CATEGORY = 6532840 --and OWNER_ID = <<PROP_PERSON_GEN.REFERENCE>>

select  *
from PROP_TELEPHONE TEL INNER JOIN
MD_NAMED_OCCS OCC ON OCC.OCC_ID= TEL.OCC_ID
where CONFIG_NAME = 'Work' --and TEL.REFERENCE = <<PROP_PERSON_GEN.REFERENCE>>

SELECT * FROM DOCUMENTS
where DOC_CATEGORY = 6532918 --and OWNER_ID = <<PROP_PERSON_GEN.REFERENCE>>

SELECT * FROM DOCUMENTS
where DOC_CATEGORY = 31159 --and OWNER_ID = <<PROP_PERSON_GEN.REFERENCE>>

SELECT * FROM PROP_SKILLS SKILL INNER JOIN
PROP_PERSON_GEN PERSON_GEN ON PERSON_GEN.REFERENCE = SKILL.REFERENCE --WHERE PERSON_GEN.REFERENCE = PROP_PERSON_GEN.REFERENCE
select * from PROP_PERSON_GEN

select  *
from PROP_TELEPHONE TEL INNER JOIN
MD_NAMED_OCCS OCC ON OCC.OCC_ID= TEL.OCC_ID
where CONFIG_NAME = 'Work' --and TEL.REFERENCE = <<PROP_PERSON_GEN.REFERENCE>>

select  *
from PROP_ADDRESS ADDRESS INNER JOIN
MD_NAMED_OCCS OCC ON OCC.OCC_ID= ADDRESS.OCC_ID
where CONFIG_NAME = 'Primary' --and ADDRESS.REFERENCE = <<PROP_PERSON_GEN.REFERENCE>>

select * EMPLOYEE.NAME as ConsName
from PROP_PERSON_GEN PERSON_GEN INNER JOIN
PROP_OWN_CONS CONS ON PERSON_GEN.REFERENCE = CONS.REFERENCE INNER JOIN
MD_NAMED_OCCS OCC ON OCC.OCC_ID= CONS.OCC_ID INNER JOIN
PROP_EMPLOYEE_GEN EMPLOYEE ON EMPLOYEE.USER_REF = CONS.CONSULTANT
where CONFIG_NAME = 'Permanent' and CONS.REFERENCE = 10629 --AND PERSON_GEN.REFERENCE = <<PROP_PERSON_GEN.REFERENCE>>
