
with note as (
	select can.contactid
	, Stuff( 
	        Coalesce('CandNo: ' + NULLIF(cast(c.candidateref as varchar(max)), '') + char(10), '')
--	      + Coalesce('Owner: ' + NULLIF(cast( iif(u.email is null, c.username, '') as varchar(max)), '') + char(10), '')
--             + Coalesce('Contact Type: ' + NULLIF(cast(c.type as varchar(max)), '') + char(10), '')
+ Coalesce('Department: ' + NULLIF(cast(c.department as varchar(max)), '') + char(10), '')
--             --+ Coalesce('Relocation: ' + NULLIF(cast(c.relocationstatus as varchar(max)), '') + char(10), '')
--             --+ Coalesce('Relocation: ' + NULLIF(cast(can.canrelocate as varchar(max)), '') + char(10), '')
--             + Coalesce('Relocation: ' + NULLIF(case when can.canrelocate = 1 then 'Yes' when can.canrelocate = 0 then '' else '' end, '') + char(10), '')
--             + Coalesce('CV Date: ' + NULLIF(cast(c.DateCVAdded as varchar(max)), '') + char(10), '') 
--             + Coalesce('Availability: ' + NULLIF(cast(can.availability as varchar(max)), '') + char(10), '') 
--             + Coalesce('Status: ' + NULLIF(cast(c.ContactStatus as varchar(max)), '') + char(10), '')
--             + Coalesce('Location: ' + NULLIF(cast(c.location as varchar(max)), '') + char(10), '')
--	      + Coalesce('Sub Location: ' + NULLIF(cast(c.sublocation as varchar(max)), '') + char(10), '')
--	      + Coalesce('Source: ' + NULLIF(cast(c.ContactSource as varchar(max)), '') + char(10), '')
--+ Coalesce('RS Ref: ' + NULLIF(cast(can.contactid as varchar(max)), '') + char(10), '')
--	      + Coalesce('Sector: ' + NULLIF(cast(c.sector as varchar(max)), '') + char(10), '')
--	      + Coalesce('Job Wanted > Salary Req''d (Range): ' + NULLIF(cast( concat(can.currency2,' ',can.SalaryWanted,' ',can.SalaryWanted2) as varchar(max)), '') + char(10), '')
--	      + Coalesce(char(10) + 'Registration Notes: ' + NULLIF(cast(c.comments as varchar(max)), '') + char(10), '')
--	      --+ Coalesce('About: ' + NULLIF(cast(c.comments as varchar(max)), '') + char(10), '')
       + Coalesce('Contact Type: ' + NULLIF(convert(nvarchar(max),c.type), '') + char(10), '')
       + Coalesce('Relocation: ' + NULLIF(convert(nvarchar(max),c.relocationstatus), '') + char(10), '')
       + Coalesce('URL: ' + NULLIF(convert(nvarchar(max),c.website), '') + char(10), '')
       + Coalesce('Fax: ' + NULLIF(convert(nvarchar(max),c.fax), '') + char(10), '')
       + Coalesce('Last User: ' + NULLIF(convert(nvarchar(max),u1.username), '') + char(10), '')
       + Coalesce('Home City: ' + NULLIF(convert(nvarchar(max),c.homecity), '') + char(10), '')
       + Coalesce('Reg Date (date): ' + NULLIF(convert(nvarchar(max),c.regdate), '') + char(10), '')
       + Coalesce('Updated (date): ' + NULLIF(convert(nvarchar(max),c.lastupdate), '') + char(10), '')
       + Coalesce('Reviewed (date): ' + NULLIF(convert(nvarchar(max),c.lastreviewdate), '') + char(10), '')
       + Coalesce('Emailed (date): ' + NULLIF(convert(nvarchar(max),c.dateemailed), '') + char(10), '')
       + Coalesce('Last Call (date): ' + NULLIF(convert(nvarchar(max),c.datelastcalled), '') + char(10), '')
       + Coalesce('Email 2: ' + NULLIF(convert(nvarchar(max),c.email2), '') + char(10), '')
       + Coalesce('Email 3: ' + NULLIF(convert(nvarchar(max),c.Email3), '') + char(10), '')
       + Coalesce('Years of Experiencing: ' + NULLIF(convert(nvarchar(max),c.experienceinyears), '') + char(10), '')
       + Coalesce('Date Experience Entered: ' + NULLIF(convert(nvarchar(max),c.dateexperienceset), '') + char(10), '')
       + Coalesce('Start year in Industry / Sector: ' + NULLIF(convert(nvarchar(max),c.StartYear), '') + char(10), '')
       + Coalesce('Date started at current company: ' + NULLIF(convert(nvarchar(max),c.CompanyStartDate), '') + char(10), '')
       + Coalesce('Date Last Called: ' + NULLIF(convert(nvarchar(max),c.datelastcalled), '') + char(10), '')
       --+ Coalesce('Select how often you want to call this contact (radio button): ' + NULLIF(convert(nvarchar(max),c.Select how often you want to call this contact (radio button)), '') + char(10), '')
       --+ Coalesce('Year Qualified: ' + NULLIF(convert(nvarchar(max),c.), '') + char(10), '')
       + Coalesce('CV Date: ' + NULLIF(convert(nvarchar(max),c.datecvadded), '') + char(10), '')
       + Coalesce('Availability: ' + NULLIF(convert(nvarchar(max),can.availability), '') + char(10), '')
       + Coalesce('Time Zone: ' + NULLIF(convert(nvarchar(max),c.timezonename), '') + char(10), '')
       + Coalesce('Status: ' + NULLIF(convert(nvarchar(max),c.contactstatus), '') + char(10), '')
       + Coalesce('Discipline: ' + NULLIF(convert(nvarchar(max),c.discipline), '') + char(10), '')
       + Coalesce('Location: ' + NULLIF(convert(nvarchar(max),c.location), '') + char(10), '')
       + Coalesce('Sub Loc: ' + NULLIF(convert(nvarchar(max),c.sublocation), '') + char(10), '')
       + Coalesce('Source: ' + NULLIF(convert(nvarchar(max),c.source), '') + char(10), '')
       --+ Coalesce('Clearances: ' + NULLIF(convert(nvarchar(max),c.Clearances), '') + char(10), '')
       --+ Coalesce('Langs: ' + NULLIF(convert(nvarchar(max),c.Langs), '') + char(10), '')
       
       + Coalesce('Coverage: ' + NULLIF(convert(nvarchar(max),mm.coverage), '') + char(10), '')
       + Coalesce('Preferred Locations: ' + NULLIF(convert(nvarchar(max),mm.locations), '') + char(10), '')
       + Coalesce('Reporting To: ' + NULLIF(convert(nvarchar(max),mm.reportingto), '') + char(10), '')
       + Coalesce('Hire Authority: ' + NULLIF(convert(nvarchar(max),mm.hireauthority), '') + char(10), '')
       + Coalesce('Key Buying Condition: ' + NULLIF(convert(nvarchar(max),c.importkey), '') + char(10), '')
       + Coalesce('Assessed: ' + NULLIF(convert(nvarchar(max),mm.assessed), '') + char(10), '')
       + Coalesce('Exam Status: ' + NULLIF(convert(nvarchar(max),mm.examstatus), '') + char(10), '')
       + Coalesce('Contract: ' + NULLIF(convert(nvarchar(max),mm.Contract), '') + char(10), '')
       + Coalesce('Sector: ' + NULLIF(convert(nvarchar(max),c.sector), '') + char(10), '')
       + Coalesce('Sub Sector: ' + NULLIF(convert(nvarchar(max),mm.subsector), '') + char(10), '')
       + Coalesce('Last Update: ' + NULLIF(convert(nvarchar(max),mm.lastupdate), '') + char(10), '')
       
       --+ Coalesce('Connected (checkbox): ' + NULLIF(convert(nvarchar(max),c.Connected (checkbox)), '') + char(10), '')
       + Coalesce('Embargo (checkbox): ' + NULLIF(case when c.Embargoed = 1 then 'Yes' when c.Embargoed = 0 then 'No' else '' end, '') + char(10), '')
       + Coalesce('Hotlist (checkbox): ' + NULLIF(case when c.hotlist = 1 then 'Yes' when c.hotlist = 0 then 'No' else '' end, '') + char(10), '')
       + Coalesce('Can Email (checkbox): ' + NULLIF(case when c.AgreedToEmail = 1 then 'Yes' when c.AgreedToEmail = 0 then 'No' else '' end, '') + char(10), '')
       + Coalesce('Email (checkbox): ' + NULLIF(case when c.CanText = 1 then 'Yes' when c.CanText = 0 then 'No' else '' end, '') + char(10), '')
       --+ Coalesce('Add Picture ?: ' + NULLIF(convert(nvarchar(max),c.Add Picture ?), '') + char(10), '')
       + Coalesce('Company Status: ' + NULLIF(cast(c.ContactStatus as varchar(max)), '') + char(10), '')
       + Coalesce('Stars: ' + NULLIF(convert(nvarchar(max),c.starrating), '') + char(10), '')
       
       + Coalesce('Personal Check List > Work Permit Required (Checkbox): ' + NULLIF(case when can.workpermitrequired = 1 then 'Yes' when can.WorkPermitRequired = 0 then 'No' else '' end, '') + char(10), '')
       + Coalesce('Personal Check List > Eligible to Work: ' + NULLIF(case when can.hasworkpermit = 1 then 'Yes' when can.hasworkpermit = 0 then 'No' else '' end, '') + char(10), '')
       + Coalesce('Personal Check List > Can Relocate: ' + NULLIF(case when can.canrelocate = 1 then 'Yes' when can.CanRelocate = 0 then 'No' else '' end, '') + char(10), '')
       + Coalesce('Personal Check List > Can Work Abroad: ' + NULLIF(case when can.CanWorkAbroad = 1 then 'Yes' when can.CanWorkAbroad = 0 then 'No' else '' end, '') + char(10), '')
       + Coalesce('Personal Check List > Driving License: ' + NULLIF(case when can.DriveLicence = 1 then 'Yes' when can.drivelicence = 0 then 'No' else '' end, '') + char(10), '')
       + Coalesce('Personal Check List > Contractor: ' + NULLIF(case when can.IsContractor = 1 then 'Yes' when can.IsContractor = 0 then 'No' else '' end, '') + char(10), '')
       
       + Coalesce('Date/Salary (Date): ' + NULLIF(convert(nvarchar(max),can.datesalaryentered), '') + char(10), '')
       + Coalesce('Bonus: ' + NULLIF(convert(nvarchar(max),can.bonus), '') + char(10), '')
       + Coalesce('Social / NI: ' + NULLIF(convert(nvarchar(max),can.NINumber), '') + char(10), '')
       + Coalesce('Notice (dropdown): ' + NULLIF(convert(nvarchar(max),can.noticeperiod), '') + char(10), '')
       + Coalesce('Availability (date): ' + NULLIF(convert(nvarchar(max),can.availability), '') + char(10), '')
       + Coalesce('Avail Status: ' + NULLIF(convert(nvarchar(max),can.availabilitystatus), '') + char(10), '')
       
       + Coalesce('Job Wanted > Sector: ' + NULLIF(convert(nvarchar(max),can.sectorwanted), '') + char(10), '')
       + Coalesce('Job Wanted > Sub Sector: ' + NULLIF(convert(nvarchar(max),can.segmentwanted), '') + char(10), '')
       + Coalesce('Job Wanted > Position: ' + NULLIF(convert(nvarchar(max),can.positionwanted), '') + char(10), '')
       + Coalesce('Job Wanted > Job Type: ' + NULLIF(convert(nvarchar(max),can.jobtype), '') + char(10), '')
       + Coalesce('Job Wanted > Location Wanted: ' + NULLIF(convert(nvarchar(max),can.locationwanted), '') + char(10), '')
       + Coalesce('Job Wanted > Sublocation (dropdown): ' + NULLIF(convert(nvarchar(max),can.sublocation), '') + char(10), '')
       + Coalesce('Job Wanted > Salary Req''d (Range) (dropdown): ' + NULLIF(convert(nvarchar(max),can.StartingSalary), '') + char(10), '')
       + Coalesce('Job Wanted > Salary Req''d (Range) (text) 1: ' + NULLIF(convert(nvarchar(max),can.SalaryWanted), '') + char(10), '')
       + Coalesce('Job Wanted > Salary Req''d (Range) (text) 2: ' + NULLIF(convert(nvarchar(max),can.SalaryWanted2), '') + char(10), '')
       
       + Coalesce('Negotiable (checkbox): '  + NULLIF(case when can.negotiable = 1 then 'Yes' when can.negotiable = 0 then 'No' else '' end, '') + char(10), '')
       + Coalesce('Benefits: ' + NULLIF(convert(nvarchar(max),can.benefits), '') + char(10), '')
       --+ Coalesce('Remark: ' + NULLIF(convert(nvarchar(max),c), '') + char(10), '')
       --+ Coalesce('Preferred Company: ' + NULLIF(convert(nvarchar(max),c.source), '') + char(10), '')
       + Coalesce('References: ' + NULLIF(convert(nvarchar(max),c.candidateref), '') + char(10), '')
       --+ Coalesce('Bank: ' + NULLIF(convert(nvarchar(max),can.ba), '') + char(10), '')
       --+ Coalesce('Registration Notes: ' + NULLIF(convert(nvarchar(max),c.Registration Notes), '') + char(10), '')
       + Coalesce('Job Check List > Refs Checked (checkbox): '  + NULLIF(case when can.refschecked = 1 then 'Yes' when can.refschecked = 0 then 'No' else '' end, '') + char(10), '')
       + Coalesce('Job Check List > Placed (checkbox): '  + NULLIF(case when can.placed = 1 then 'Yes' when can.placed = 0 then 'No' else '' end, '') + char(10), '')
       
       + Coalesce('Company Name: ' + NULLIF(convert(nvarchar(max),Contractors.companyname), '') + char(10), '')
       + Coalesce('Company Type: ' + NULLIF(convert(nvarchar(max),Contractors.companytype), '') + char(10), '')
       + Coalesce('Company Reg No: ' + NULLIF(convert(nvarchar(max),Contractors.companyregno), '') + char(10), '')
       + Coalesce('VAT No: ' + NULLIF(convert(nvarchar(max),Contractors.companyvatno), '') + char(10), '')
       + Coalesce('Tel No: ' + NULLIF(convert(nvarchar(max),Contractors.companytel), '') + char(10), '')
       + Coalesce('E-Mail: ' + NULLIF(convert(nvarchar(max),Contractors.companyemail), '') + char(10), '')
       --+ Coalesce('Company Address > Line 1: ' + NULLIF(convert(nvarchar(max),Contractors.), '') + char(10), '')
       --+ Coalesce('Company Address > Line 2: ' + NULLIF(convert(nvarchar(max),c.Company Address > Line 2), '') + char(10), '')
       --+ Coalesce('Company Address > Line 3: ' + NULLIF(convert(nvarchar(max),c.Company Address > Line 3), '') + char(10), '')
       --+ Coalesce('Company Address > City: ' + NULLIF(convert(nvarchar(max),c.Company Address > City), '') + char(10), '')
       --+ Coalesce('Company Address > County: ' + NULLIF(convert(nvarchar(max),c.Company Address > County), '') + char(10), '')
       --+ Coalesce('Company Address > TelNo: ' + NULLIF(convert(nvarchar(max),c.Company Address > TelNo), '') + char(10), '')
       --+ Coalesce('Company Address > Email: ' + NULLIF(convert(nvarchar(max),c.Company Address > Email), '') + char(10), '')
       
       + Coalesce('Name of Bank: ' + NULLIF(convert(nvarchar(max),b.bankname), '') + char(10), '')
       + Coalesce('Bank Address 1: ' + NULLIF(convert(nvarchar(max),b.bankaddr1), '') + char(10), '')
       + Coalesce('Bank Address 2: ' + NULLIF(convert(nvarchar(max),b.bankaddr2), '') + char(10), '')
       + Coalesce('Bank Address 3: ' + NULLIF(convert(nvarchar(max),b.bankaddr3), '') + char(10), '')
       + Coalesce('Postcode: ' + NULLIF(convert(nvarchar(max),b.bankpostcode), '') + char(10), '')
       + Coalesce('Swift Address: ' + NULLIF(convert(nvarchar(max),b.swiftaddress), '') + char(10), '')
       + Coalesce('Tax Status: ' + NULLIF(convert(nvarchar(max),b.taxstatus), '') + char(10), '')
       + Coalesce('UTR (Personal): ' + NULLIF(convert(nvarchar(max),b.utrpersonal), '') + char(10), '')
       + Coalesce('UTR (Company): ' + NULLIF(convert(nvarchar(max),b.utrcompany), '') + char(10), '')
       + Coalesce('Account Details > Account Name: ' + NULLIF(convert(nvarchar(max),b.accountname), '') + char(10), '')
       + Coalesce('Account Details > Account No: ' + NULLIF(convert(nvarchar(max),b.accountno), '') + char(10), '')
       + Coalesce('Account Details > Sort Code: ' + NULLIF(convert(nvarchar(max),b.sortcode), '') + char(10), '')
       + Coalesce('Account Details > Other References > Roll No: ' + NULLIF(convert(nvarchar(max),b.rollno), '') + char(10), '')
       + Coalesce('Account Details > CIS No: ' + NULLIF(convert(nvarchar(max),b.cisno), '') + char(10), '')
                     , 1, 0, '') as note
       -- select count(*)
       from dbo.candidates can
       left join dbo.contacts c on c.contactid = can.contactid --where c.type in ('Candidate')
       --left join dbo.users u on u.userid = c.userid
       left join (select userid, username from dbo.users) u1 on u1.userid = c.lastuser
       left join MarketMap mm on mm.contactid = c.contactid
       left join Contractors on Contractors.contactid = can.contactid
       left join dbo.bankdetails b on b.accountno = can.contactid
       where c.type in ('Candidate')
)

select * from note where contactid = '828087-8837-17213'
--select * from dbo.contacts where contactid = '828087-8837-17213'

/*
select top 10 *
from dbo.candidates can
left join dbo.contacts c on c.contactid = can.contactid
*/
