WITH split_fe AS (
	SELECT
	id_person person_id,
	LOWER(TRIM(s.functional_expertise_id)) functional_expertise_id
	FROM person_x px, UNNEST(string_to_array(px.id_job_function_string_list, ',')) s(functional_expertise_id)
),
cte_functional_expertise AS (
	SELECT
	person_id,
	sf.functional_expertise_id,
	jf.id_job_function,
	jf.value functional_expertise
	FROM split_fe sf
	LEFT JOIN job_function jf ON sf.functional_expertise_id = jf.id_job_function
),
map_fe AS (
SELECT
	person_id,
	CASE
		WHEN functional_expertise = 'AIM INTERIM' THEN NULL
		WHEN functional_expertise = 'CHIEF - CEO' THEN 'Chief'
		WHEN functional_expertise = 'CHIEF - MD' THEN 'Chief'
		WHEN functional_expertise = 'CHIEF - OWNER' THEN 'Chief'
		WHEN functional_expertise = 'COMMERCIAL - ACCOUNT DIRECTOR' THEN 'Commercial'
		WHEN functional_expertise = 'COMMERCIAL - BDD' THEN 'Commercial'
		WHEN functional_expertise = 'COMMERCIAL - DIRECTOR' THEN 'Commercial'
		WHEN functional_expertise = 'COMMERCIAL - SALES CONTROLLER' THEN 'Commercial'
		WHEN functional_expertise = 'COMMERCIAL - SALES DIRECTOR' THEN 'Commercial'
		WHEN functional_expertise = 'COMMERCIAL - HEAD OF SALES' THEN 'Commercial'
		WHEN functional_expertise = 'COMMERCIAL - BDM' THEN 'Commercial'
		WHEN functional_expertise = 'COMMERCIAL - CATEGORY MANAGER' THEN 'Commercial'
		WHEN functional_expertise = 'COMMERCIAL - COMMERCIAL MANAGE' THEN 'Commercial'
		WHEN functional_expertise = 'COMMERCIAL - S&M MANAGER' THEN 'Commercial'
		WHEN functional_expertise = 'COMMERCIAL - SALES MANAGER' THEN 'Commercial'
		WHEN functional_expertise = 'COMMERCIAL - ACCOUNT MANAGER' THEN 'Commercial'
		WHEN functional_expertise = 'COMMERCIAL - ANALYST' THEN 'Commercial'
		WHEN functional_expertise = 'COMMERCIAL - BDE' THEN 'Commercial'
		WHEN functional_expertise = 'COMMERCIAL - FIELD SALES EXEC' THEN 'Commercial'
		WHEN functional_expertise = 'COMMERCIAL - KAM' THEN 'Commercial'
		WHEN functional_expertise = 'COMMERCIAL - LOWER' THEN 'Commercial'
		WHEN functional_expertise = 'COMMERCIAL - NAE' THEN 'Commercial'
		WHEN functional_expertise = 'COMMERCIAL - NAM' THEN 'Commercial'
		WHEN functional_expertise = 'COMMERCIAL - SALES EXEC' THEN 'Commercial'
		WHEN functional_expertise = 'COMMERCIAL - SNAM' THEN 'Commercial'
		WHEN functional_expertise = 'COMMERCIAL - TRADER' THEN 'Commercial'
		WHEN functional_expertise = 'ENGINEERING - CONTRACTOR' THEN 'Engineering'
		WHEN functional_expertise = 'ENGINEERING - DIRECTOR' THEN 'Engineering'
		WHEN functional_expertise = 'ENGINEERING - ENGINEER' THEN 'Engineering'
		WHEN functional_expertise = 'ENGINEERING - MAINTENANCE MANAGER' THEN 'Engineering'
		WHEN functional_expertise = 'ENGINEERING - MANAGER' THEN 'Engineering'
		WHEN functional_expertise = 'ENGINEERING - PROJECT MANAGER' THEN 'Engineering'
		WHEN functional_expertise = 'ENGINEERING - PROJECTS' THEN 'Engineering'
		WHEN functional_expertise = 'FINANCE - DIRECTOR' THEN 'Finance'
		WHEN functional_expertise = 'FINANCE - MANGT ACCOUNTANT' THEN 'Finance'
		WHEN functional_expertise = 'FINANCE - MANAGER' THEN 'Finance'
		WHEN functional_expertise = 'HR - DIRECTOR' THEN 'HR'
		WHEN functional_expertise = 'HR - LOWER' THEN 'HR'
		WHEN functional_expertise = 'HR - MANAGER' THEN 'HR'
		WHEN functional_expertise = 'HR - RECRUITMENT MANAGER' THEN 'HR'
		WHEN functional_expertise = 'HR - RESOURCING' THEN 'HR'
		WHEN functional_expertise = 'HR-BUSINESS PARTNER' THEN 'HR'
		WHEN functional_expertise = 'HR-L&D TRAINER/MAANGER' THEN 'HR'
		WHEN functional_expertise = 'H&S MANAGER' THEN 'HSE'
		WHEN functional_expertise = 'HSE - ADVISOR' THEN 'HSE'
		WHEN functional_expertise = 'HSE - DIRECTOR' THEN 'HSE'
		WHEN functional_expertise = 'HSE - MANAGER' THEN 'HSE'
		WHEN functional_expertise = 'INTERIM MANAGER' THEN 'Interim Manager'
		WHEN functional_expertise = 'INTERNATIONAL' THEN 'International'
		WHEN functional_expertise = 'LEAN MANUFACTURING' THEN 'Lean Manufacturing'
		WHEN functional_expertise = 'COMMERCIAL - MARKETING DIRECTOR' THEN 'Marketing'
		WHEN functional_expertise = 'COMMERCIAL - MARLETING EXEC' THEN 'Marketing'
		WHEN functional_expertise = 'COMMERCIAL - BRAND MANAGER' THEN 'Marketing'
		WHEN functional_expertise = 'COMMERCIAL - HEAD OF BRAND' THEN 'Marketing'
		WHEN functional_expertise = 'COMMERCIAL - HEAD OF CATEGORY' THEN 'Marketing'
		WHEN functional_expertise = 'COMMERCIAL - HEAD OF MARKETING' THEN 'Marketing'
		WHEN functional_expertise = 'COMMERCIAL - MARKETING MANAGER' THEN 'Marketing'
		WHEN functional_expertise = 'COMMERCIAL - INSIGHTS MANAGER' THEN 'Marketing'
		WHEN functional_expertise = 'NPD - DEV CHEF' THEN 'NPD'
		WHEN functional_expertise = 'NPD - DIRECTOR' THEN 'NPD'
		WHEN functional_expertise = 'INNOVATION MANAGER' THEN 'NPD'
		WHEN functional_expertise = 'NPD - MANAGER' THEN 'NPD'
		WHEN functional_expertise = 'NPD - PROJECT MANAGER' THEN 'NPD'
		WHEN functional_expertise = 'NPD - TECHNOLGIST' THEN 'NPD'
		WHEN functional_expertise = 'OPS - CI' THEN 'Ops'
		WHEN functional_expertise = 'OPS - DIRECTOR' THEN 'Ops'
		WHEN functional_expertise = 'OPS - GENERAL MANAGER' THEN 'Ops'
		WHEN functional_expertise = 'OPS -  LOW UP TO 30k' THEN 'Ops'
		WHEN functional_expertise = 'OPS - MID 30 to 45k' THEN 'Ops'
		WHEN functional_expertise = 'OPS - MID 30 TO 50k' THEN 'Ops'
		WHEN functional_expertise = 'OPS - MID 45 TO 60k' THEN 'Ops'
		WHEN functional_expertise = 'OPS - SENIOR 50 TO 70k' THEN 'Ops'
		WHEN functional_expertise = 'OPS - SENIOR 60 TO 80k' THEN 'Ops'
		WHEN functional_expertise = 'OPS - TOP LEVEL 70k UP' THEN 'Ops'
		WHEN functional_expertise = 'OPS - TOP LEVEL 80k UP' THEN 'Ops'
		WHEN functional_expertise = 'OPS - WHAT LEVEL' THEN 'Ops'
		WHEN functional_expertise = 'OTHER - COST REDUCTION' THEN 'Other'
		WHEN functional_expertise = 'OTHER - FRANCHISE' THEN 'Other'
		WHEN functional_expertise = 'OTHER - INDUSTRIAL ENG' THEN 'Other'
		WHEN functional_expertise = 'PROGRAMME MANAGER' THEN 'Other'
		WHEN functional_expertise = 'OTHER - TRAINER' THEN 'Other'
		WHEN functional_expertise = 'OTHER-' THEN 'Other'
		WHEN functional_expertise = 'PACKAGING MAN' THEN 'Packaging'
		WHEN functional_expertise = 'PACKAGING TECH' THEN 'Packaging'
		WHEN functional_expertise = 'PLANNING - ANALYST' THEN 'Planning'
		WHEN functional_expertise = 'PLANNING - DEMAND PLANNER' THEN 'Planning'
		WHEN functional_expertise = 'PLANNING - DIRECTOR' THEN 'Planning'
		WHEN functional_expertise = 'PLANNING - MATERIAL PLANNER' THEN 'Planning'
		WHEN functional_expertise = 'PLANNING - PLANNER' THEN 'Planning'
		WHEN functional_expertise = 'PLANNING - PLANNING MANAGER' THEN 'Planning'
		WHEN functional_expertise = 'PLANNING - PRODUCTION PLANNER' THEN 'Planning'
		WHEN functional_expertise = 'PROCESS - LOWER' THEN 'Process'
		WHEN functional_expertise = 'PROCESS - MANAGER' THEN 'Process'
		WHEN functional_expertise = 'PROCESS - TECH' THEN 'Process'
		WHEN functional_expertise = 'PURCHASING - DIRECTOR' THEN 'Purchasing'
		WHEN functional_expertise = 'PURCHASING - MANAGER' THEN 'Purchasing'
		WHEN functional_expertise = 'RECRUITER' THEN 'Recruitment Consultant'
		WHEN functional_expertise = 'RECRUITMENT CONSULTANT' THEN 'Recruitment Consultant'
		WHEN functional_expertise = 'RETIRED' THEN 'Retired'
		WHEN functional_expertise = 'SUPPLY CHAIN - DESPATCH MANAGER' THEN 'Supply Chain'
		WHEN functional_expertise = 'SUPPLY CHAIN - DIRECTOR' THEN 'Supply Chain'
		WHEN functional_expertise = 'SUPPLY CHAIN - DISTRIB MAN' THEN 'Supply Chain'
		WHEN functional_expertise = 'SUPPLY CHAIN - LOWER' THEN 'Supply Chain'
		WHEN functional_expertise = 'SUPPLY CHAIN - MANAGER' THEN 'Supply Chain'
		WHEN functional_expertise = 'MATERIALS - MANAGER' THEN 'Supply Chain'
		WHEN functional_expertise = 'SUPPLY CHAIN - TRANSPORT  MANAGER' THEN 'Supply Chain'
		WHEN functional_expertise = 'SUPPLY CHAIN - W/HOUSE MANAGER' THEN 'Supply Chain'
		WHEN functional_expertise = 'TECHNICAL - AUDITOR' THEN 'Technical'
		WHEN functional_expertise = 'TECHNICAL - COMPLIANCE - LOWER' THEN 'Technical'
		WHEN functional_expertise = 'TECHNICAL - COMPLIANCE - MANAGER' THEN 'Technical'
		WHEN functional_expertise = 'TECHNICAL - DIRECTOR' THEN 'Technical'
		WHEN functional_expertise = 'TECHNICAL - GROUP HYGIENE MANAGER' THEN 'Technical'
		WHEN functional_expertise = 'TECHNICAL - GROUP TECH MANAGER' THEN 'Technical'
		WHEN functional_expertise = 'TECHNICAL - GROUP TECH SERVICES MANAGER' THEN 'Technical'
		WHEN functional_expertise = 'TECHNICAL - HEAD OF TECHNICAL' THEN 'Technical'
		WHEN functional_expertise = 'TECHNICAL - HYGIENE MANAGER' THEN 'Technical'
		WHEN functional_expertise = 'TECH - HYGIENE MANAGER' THEN 'Technical'
		WHEN functional_expertise = 'TECHNICAL - HYGIENE SUPERVISOR' THEN 'Technical'
		WHEN functional_expertise = 'TECHNICAL - LAB MANAGER' THEN 'Technical'
		WHEN functional_expertise = 'TECHNICAL - LOWER' THEN 'Technical'
		WHEN functional_expertise = 'TECH - TECH MANAGER' THEN 'Technical'
		WHEN functional_expertise = 'TECHNICAL - SITE TECH MANAGER' THEN 'Technical'
		WHEN functional_expertise = 'TECHNICAL - TECH MANAGER' THEN 'Technical'
		WHEN functional_expertise = 'TECHNICAL - TECH MANAGER LOW LEVEL' THEN 'Technical'
		WHEN functional_expertise = 'TECHNICAL - QA MANAGER' THEN 'Technical'
		WHEN functional_expertise = 'TECHNICAL - QA SUPERVISOR' THEN 'Technical'
		WHEN functional_expertise = 'TECHNICAL - RAW MATERIALS MANAGER' THEN 'Technical'
		WHEN functional_expertise = 'TECHNICAL - RAW MATERIALS TECH' THEN 'Technical'
		WHEN functional_expertise = 'TECHNICAL - SCIENTIST' THEN 'Technical'
		WHEN functional_expertise = 'TECHNICAL - SPEC TECH' THEN 'Technical'
		WHEN functional_expertise = 'SYSTEMS MANAGER' THEN 'Technical'
		WHEN functional_expertise = 'TECHNICAL - SYSTEMS MANAGER' THEN 'Technical'
		WHEN functional_expertise = 'TECHNICAL - TECHNICAL SERVICES MANAGER' THEN 'Technical'
	END functional_expertise
FROM cte_functional_expertise
),
map_sub_fe AS (
	SELECT
		person_id,
		CASE
			WHEN functional_expertise = 'AIM INTERIM' THEN ''
			WHEN functional_expertise = 'CHIEF - CEO' THEN 'CEO'
			WHEN functional_expertise = 'CHIEF - MD' THEN 'MD'
			WHEN functional_expertise = 'CHIEF - OWNER' THEN 'Owner'
			WHEN functional_expertise = 'COMMERCIAL - ACCOUNT DIRECTOR' THEN 'Director'
			WHEN functional_expertise = 'COMMERCIAL - BDD' THEN 'Director'
			WHEN functional_expertise = 'COMMERCIAL - DIRECTOR' THEN 'Director'
			WHEN functional_expertise = 'COMMERCIAL - SALES CONTROLLER' THEN 'Director'
			WHEN functional_expertise = 'COMMERCIAL - SALES DIRECTOR' THEN 'Director'
			WHEN functional_expertise = 'COMMERCIAL - HEAD OF SALES' THEN 'Manager'
			WHEN functional_expertise = 'COMMERCIAL - BDM' THEN 'Manager'
			WHEN functional_expertise = 'COMMERCIAL - CATEGORY MANAGER' THEN 'Manager'
			WHEN functional_expertise = 'COMMERCIAL - COMMERCIAL MANAGE' THEN 'Manager'
			WHEN functional_expertise = 'COMMERCIAL - S&M MANAGER' THEN 'Manager'
			WHEN functional_expertise = 'COMMERCIAL - SALES MANAGER' THEN 'Manager'
			WHEN functional_expertise = 'COMMERCIAL - ACCOUNT MANAGER' THEN 'NAM/other'
			WHEN functional_expertise = 'COMMERCIAL - ANALYST' THEN 'NAM/other'
			WHEN functional_expertise = 'COMMERCIAL - BDE' THEN 'NAM/other'
			WHEN functional_expertise = 'COMMERCIAL - FIELD SALES EXEC' THEN 'NAM/other'
			WHEN functional_expertise = 'COMMERCIAL - KAM' THEN 'NAM/other'
			WHEN functional_expertise = 'COMMERCIAL - LOWER' THEN 'NAM/other'
			WHEN functional_expertise = 'COMMERCIAL - NAE' THEN 'NAM/other'
			WHEN functional_expertise = 'COMMERCIAL - NAM' THEN 'NAM/other'
			WHEN functional_expertise = 'COMMERCIAL - SALES EXEC' THEN 'NAM/other'
			WHEN functional_expertise = 'COMMERCIAL - SNAM' THEN 'NAM/other'
			WHEN functional_expertise = 'COMMERCIAL - TRADER' THEN 'NAM/other'
			WHEN functional_expertise = 'ENGINEERING - CONTRACTOR' THEN 'Contractor'
			WHEN functional_expertise = 'ENGINEERING - DIRECTOR' THEN 'Director'
			WHEN functional_expertise = 'ENGINEERING - ENGINEER' THEN 'Engineer'
			WHEN functional_expertise = 'ENGINEERING - MAINTENANCE MANAGER' THEN 'Maintenance Manager'
			WHEN functional_expertise = 'ENGINEERING - MANAGER' THEN 'Manager'
			WHEN functional_expertise = 'ENGINEERING - PROJECT MANAGER' THEN 'Project Manager'
			WHEN functional_expertise = 'ENGINEERING - PROJECTS' THEN 'Projects'
			WHEN functional_expertise = 'FINANCE - DIRECTOR' THEN 'Director'
			WHEN functional_expertise = 'FINANCE - MANGT ACCOUNTANT' THEN 'Management Accountant'
			WHEN functional_expertise = 'FINANCE - MANAGER' THEN 'Manager'
			WHEN functional_expertise = 'HR - DIRECTOR' THEN 'Director'
			WHEN functional_expertise = 'HR - LOWER' THEN 'Lower'
			WHEN functional_expertise = 'HR - MANAGER' THEN 'Manager'
			WHEN functional_expertise = 'HR - RECRUITMENT MANAGER' THEN 'Recruitment Manager'
			WHEN functional_expertise = 'HR - RESOURCING' THEN 'Resourcing'
			WHEN functional_expertise = 'HR-BUSINESS PARTNER' THEN 'Business Partner'
			WHEN functional_expertise = 'HR-L&D TRAINER/MAANGER' THEN 'L&D Trainer'
			WHEN functional_expertise = 'H&S MANAGER' THEN 'Manager'
			WHEN functional_expertise = 'HSE - ADVISOR' THEN 'Advisor'
			WHEN functional_expertise = 'HSE - DIRECTOR' THEN 'Director'
			WHEN functional_expertise = 'HSE - MANAGER' THEN 'Manager'
			WHEN functional_expertise = 'INTERIM MANAGER' THEN ''
			WHEN functional_expertise = 'INTERNATIONAL' THEN ''
			WHEN functional_expertise = 'LEAN MANUFACTURING' THEN ''
			WHEN functional_expertise = 'COMMERCIAL - MARKETING DIRECTOR' THEN 'Director'
			WHEN functional_expertise = 'COMMERCIAL - MARLETING EXEC' THEN 'Lower'
			WHEN functional_expertise = 'COMMERCIAL - BRAND MANAGER' THEN 'Manager'
			WHEN functional_expertise = 'COMMERCIAL - HEAD OF BRAND' THEN 'Manager'
			WHEN functional_expertise = 'COMMERCIAL - HEAD OF CATEGORY' THEN 'Manager'
			WHEN functional_expertise = 'COMMERCIAL - HEAD OF MARKETING' THEN 'Manager'
			WHEN functional_expertise = 'COMMERCIAL - MARKETING MANAGER' THEN 'Manager'
			WHEN functional_expertise = 'COMMERCIAL - INSIGHTS MANAGER' THEN 'Manager'
			WHEN functional_expertise = 'NPD - DEV CHEF' THEN 'Dev Chef'
			WHEN functional_expertise = 'NPD - DIRECTOR' THEN 'Director'
			WHEN functional_expertise = 'INNOVATION MANAGER' THEN 'Innovation Manager'
			WHEN functional_expertise = 'NPD - MANAGER' THEN 'Manager'
			WHEN functional_expertise = 'NPD - PROJECT MANAGER' THEN 'Project Manager'
			WHEN functional_expertise = 'NPD - TECHNOLGIST' THEN 'Technolgist'
			WHEN functional_expertise = 'OPS - CI' THEN 'CI'
			WHEN functional_expertise = 'OPS - DIRECTOR' THEN 'Director'
			WHEN functional_expertise = 'OPS - GENERAL MANAGER' THEN 'General Manager'
			WHEN functional_expertise = 'OPS -  LOW UP TO 30k' THEN 'Low Up To 30K'
			WHEN functional_expertise = 'OPS - MID 30 to 45k' THEN 'Mid 30 To 45K'
			WHEN functional_expertise = 'OPS - MID 30 TO 50k' THEN 'Mid 30 To 50K'
			WHEN functional_expertise = 'OPS - MID 45 TO 60k' THEN 'Mid 45 To 60K'
			WHEN functional_expertise = 'OPS - SENIOR 50 TO 70k' THEN 'Senior 50 To 70K'
			WHEN functional_expertise = 'OPS - SENIOR 60 TO 80k' THEN 'Senior 60 To 80K'
			WHEN functional_expertise = 'OPS - TOP LEVEL 70k UP' THEN 'Top Level 70K Up'
			WHEN functional_expertise = 'OPS - TOP LEVEL 80k UP' THEN 'Top Level 80K Up'
			WHEN functional_expertise = 'OPS - WHAT LEVEL' THEN 'What Level'
			WHEN functional_expertise = 'OTHER - COST REDUCTION' THEN 'Cost Reduction'
			WHEN functional_expertise = 'OTHER - FRANCHISE' THEN 'Franchise'
			WHEN functional_expertise = 'OTHER - INDUSTRIAL ENG' THEN 'Industrial Eng'
			WHEN functional_expertise = 'PROGRAMME MANAGER' THEN 'Programme Manager'
			WHEN functional_expertise = 'OTHER - TRAINER' THEN 'Trainer'
			WHEN functional_expertise = 'OTHER-' THEN 'Unspecified'
			WHEN functional_expertise = 'PACKAGING MAN' THEN 'Manager'
			WHEN functional_expertise = 'PACKAGING TECH' THEN 'Technologist'
			WHEN functional_expertise = 'PLANNING - ANALYST' THEN 'Analyst'
			WHEN functional_expertise = 'PLANNING - DEMAND PLANNER' THEN 'Demand Planner'
			WHEN functional_expertise = 'PLANNING - DIRECTOR' THEN 'Director'
			WHEN functional_expertise = 'PLANNING - MATERIAL PLANNER' THEN 'Material Planner'
			WHEN functional_expertise = 'PLANNING - PLANNER' THEN 'Planner'
			WHEN functional_expertise = 'PLANNING - PLANNING MANAGER' THEN 'Manager'
			WHEN functional_expertise = 'PLANNING - PRODUCTION PLANNER' THEN 'Production Planner'
			WHEN functional_expertise = 'PROCESS - LOWER' THEN 'Lower'
			WHEN functional_expertise = 'PROCESS - MANAGER' THEN 'Manager'
			WHEN functional_expertise = 'PROCESS - TECH' THEN 'Tech'
			WHEN functional_expertise = 'PURCHASING - DIRECTOR' THEN 'Director'
			WHEN functional_expertise = 'PURCHASING - MANAGER' THEN 'Manager'
			WHEN functional_expertise = 'RECRUITER' THEN ''
			WHEN functional_expertise = 'RECRUITMENT CONSULTANT' THEN ''
			WHEN functional_expertise = 'RETIRED' THEN ''
			WHEN functional_expertise = 'SUPPLY CHAIN - DESPATCH MANAGER' THEN 'Despatch Manager'
			WHEN functional_expertise = 'SUPPLY CHAIN - DIRECTOR' THEN 'Director'
			WHEN functional_expertise = 'SUPPLY CHAIN - DISTRIB MAN' THEN 'Distrib Man'
			WHEN functional_expertise = 'SUPPLY CHAIN - LOWER' THEN 'Lower'
			WHEN functional_expertise = 'SUPPLY CHAIN - MANAGER' THEN 'Manager'
			WHEN functional_expertise = 'MATERIALS - MANAGER' THEN 'Materials Manager'
			WHEN functional_expertise = 'SUPPLY CHAIN - TRANSPORT  MANAGER' THEN 'Transport  Manager'
			WHEN functional_expertise = 'SUPPLY CHAIN - W/HOUSE MANAGER' THEN 'Warehouse Manager'
			WHEN functional_expertise = 'TECHNICAL - AUDITOR' THEN 'Auditor'
			WHEN functional_expertise = 'TECHNICAL - COMPLIANCE - LOWER' THEN 'Compliance - Lower'
			WHEN functional_expertise = 'TECHNICAL - COMPLIANCE - MANAGER' THEN 'Compliance Manager'
			WHEN functional_expertise = 'TECHNICAL - DIRECTOR' THEN 'Director'
			WHEN functional_expertise = 'TECHNICAL - GROUP HYGIENE MANAGER' THEN 'Group Hygiene Manager'
			WHEN functional_expertise = 'TECHNICAL - GROUP TECH MANAGER' THEN 'Group Technical Manager'
			WHEN functional_expertise = 'TECHNICAL - GROUP TECH SERVICES MANAGER' THEN 'Group Technical Services Manager'
			WHEN functional_expertise = 'TECHNICAL - HEAD OF TECHNICAL' THEN 'Head Of Technical'
			WHEN functional_expertise = 'TECHNICAL - HYGIENE MANAGER' THEN 'Hygiene Manager'
			WHEN functional_expertise = 'TECH - HYGIENE MANAGER' THEN 'Hygiene Manager'
			WHEN functional_expertise = 'TECHNICAL - HYGIENE SUPERVISOR' THEN 'Hygiene Supervisor'
			WHEN functional_expertise = 'TECHNICAL - LAB MANAGER' THEN 'Lab Manager'
			WHEN functional_expertise = 'TECHNICAL - LOWER' THEN 'Lower'
			WHEN functional_expertise = 'TECH - TECH MANAGER' THEN 'Manager'
			WHEN functional_expertise = 'TECHNICAL - SITE TECH MANAGER' THEN 'Manager'
			WHEN functional_expertise = 'TECHNICAL - TECH MANAGER' THEN 'Manager'
			WHEN functional_expertise = 'TECHNICAL - TECH MANAGER LOW LEVEL' THEN 'Manager Low Level'
			WHEN functional_expertise = 'TECHNICAL - QA MANAGER' THEN 'QA Manager'
			WHEN functional_expertise = 'TECHNICAL - QA SUPERVISOR' THEN 'QA Supervisor'
			WHEN functional_expertise = 'TECHNICAL - RAW MATERIALS MANAGER' THEN 'Raw Materials Manager'
			WHEN functional_expertise = 'TECHNICAL - RAW MATERIALS TECH' THEN 'Raw Materials Technologist'
			WHEN functional_expertise = 'TECHNICAL - SCIENTIST' THEN 'Scientist'
			WHEN functional_expertise = 'TECHNICAL - SPEC TECH' THEN 'Specifications Technologist'
			WHEN functional_expertise = 'SYSTEMS MANAGER' THEN 'Systems Manager'
			WHEN functional_expertise = 'TECHNICAL - SYSTEMS MANAGER' THEN 'Systems Manager'
			WHEN functional_expertise = 'TECHNICAL - TECHNICAL SERVICES MANAGER' THEN 'Technical Services Manager'
		END sub_functional_expertise
	FROM cte_functional_expertise
),
cte_contact AS (
	SELECT
	cp.id_person contact_id,
	ROW_NUMBER() OVER(PARTITION BY cp.id_person ORDER BY cp.sort_order ASC, cp.employment_from DESC, cp.is_default_role) rn
	FROM company_person cp
	LEFT JOIN selected_company sc ON cp.id_company = sc.idcompany
	JOIN person_x px ON cp.id_person = px.id_person AND px.is_deleted = 0
	JOIN person p ON cp.id_person = p.id_person AND p.is_deleted = 0
),
distinct_contact_fe AS (
	SELECT
	mfe.person_id contact_id,
	functional_expertise,
	NULLIF(sub_functional_expertise, '') sub_functional_expertise,
	CURRENT_TIMESTAMP insert_timestamp,
	ROW_NUMBER() OVER(PARTITION BY mfe.person_id, functional_expertise, sub_functional_expertise ORDER BY mfe.person_id) rn
	FROM map_fe mfe
	LEFT JOIN map_sub_fe msf ON mfe.person_id = msf.person_id
	JOIN cte_contact cc ON mfe.person_id = cc.contact_id AND cc.rn = 1
	WHERE functional_expertise IS NOT NULL
)
SELECT *
FROM distinct_contact_fe
WHERE rn = 1
AND sub_functional_expertise IS NOT NULL