INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Vatican City State','VA')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('French Guiana','GF')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Congo','CG')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Guernsey','GG')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Svalbard and Jan Mayen','SJ')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('United States Minor Outlying Islands','UM')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Virgin Islands, U.S.','VI')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Guadeloupe','GP')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Serbia','RS')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Spain','ES')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Åland Islands','AX')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Bouvet Island','BV')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('French Southern Territories','TF')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Heard Island and McDonald Islands','HM')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Jersey','JE')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Palestinian Territory, Occupied','PS')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Réunion','RE')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Martinique','MQ')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Aruba','AW')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Jordan','JO')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Andorra','AD')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('United Arab Emirates','AE')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Afghanistan','AF')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Antigua and Barbuda','AG')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Anguilla','AI')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Albania','AL')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Armenia','AM')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Angola','AO')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Antarctica','AQ')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Argentina','AR')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('American Samoa','AS')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Austria','AT')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Australia','AU')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Azerbaijan','AZ')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Bosnia and Herzegovina','BA')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Barbados','BB')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Bangladesh','BD')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Belgium','BE')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Burkina Faso','BF')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Bulgaria','BG')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Bahrain','BH')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Burundi','BI')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Benin','BJ')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Saint Barthélemy','BL')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Bermuda','BM')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Brunei Darussalam','BN')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Bolivia','BO')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Brazil','BR')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Bahamas','BS')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Bhutan','BT')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Botswana','BW')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Belarus','BY')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Belize','BZ')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Canada','CA')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Cocos (Keeling) Islands','CC')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Central African Republic','CF')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Switzerland','CH')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Côte d''Ivoire','CI')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Cook Islands','CK')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Chile','CL')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Cameroon','CM')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('China','CN')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Colombia','CO')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Costa Rica','CR')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Cuba','CU')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Cape Verde','CV')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Christmas Island','CX')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Cyprus','CY')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Czech Republic','CZ')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Germany','DE')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Djibouti','DJ')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Denmark','DK')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Dominica','DM')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Dominican Republic','DO')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Algeria','DZ')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Ecuador','EC')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Estonia','EE')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Egypt','EG')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Western Sahara','EH')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Eritrea','ER')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Ethiopia','ET')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Finland','FI')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Fiji','FJ')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Falkland Islands (Malvinas)','FK')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Micronesia','FM')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Faroe Islands','FO')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('France','FR')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Gabon','GA')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('United Kingdom','GB')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Grenada','GD')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Georgia','GE')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Ghana','GH')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Gibraltar','GI')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Greenland','GL')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Gambia','GM')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Guinea','GN')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Equatorial Guinea','GQ')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Greece','GR')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Guatemala','GT')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Guam','GU')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Guinea-Bissau','GW')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Guyana','GY')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Hong Kong','HK')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Honduras','HN')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Croatia','HR')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Haiti','HT')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Hungary','HU')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Indonesia','ID')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Ireland','IE')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Israel','IL')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Isle of Man','IM')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('India','IN')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Iraq','IQ')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Iran','IR')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Iceland','IS')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Italy','IT')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Jamaica','JM')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Japan','JP')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Kenya','KE')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Kyrgyzstan','KG')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Cambodia','KH')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Kiribati','KI')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Comoros','KM')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Saint Kitts and Nevis','KN')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('North Korea','KP')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('South Korea','KR')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Kuwait','KW')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Cayman Islands','KY')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Kazakhstan','KZ')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Lao','LA')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Lebanon','LB')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Saint Lucia','LC')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Liechtenstein','LI')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Sri Lanka','LK')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Liberia','LR')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Lesotho','LS')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Lithuania','LT')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Luxembourg','LU')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Latvia','LV')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Libyan Arab Jamahiriya','LY')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Morocco','MA')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Monaco','MC')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Moldova','MD')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Montenegro','ME')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Saint Martin (French part)','MF')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Madagascar','MG')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Marshall Islands','MH')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Macedonia','MK')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Mali','ML')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Myanmar','MM')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Mongolia','MN')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Macao','MO')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Northern Mariana Islands','MP')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Mauritania','MR')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Montserrat','MS')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Malta','MT')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Mauritius','MU')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Maldives','MV')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Malawi','MW')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Mexico','MX')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Malaysia','MY')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Mozambique','MZ')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Namibia','NA')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('New Caledonia','NC')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Niger','NE')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Norfolk Island','NF')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Nigeria','NG')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Nicaragua','NI')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Netherlands','NL')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Norway','NO')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Nepal','NP')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Nauru','NR')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Niue','NU')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('New Zealand','NZ')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Oman','OM')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Panama','PA')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Peru','PE')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('French Polynesia','PF')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Papua New Guinea','PG')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Philippines','PH')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Pakistan','PK')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Poland','PL')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Saint Pierre and Miquelon','PM')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Pitcairn','PN')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Puerto Rico','PR')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Portugal','PT')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Palau','PW')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Paraguay','PY')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Qatar','QA')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Romania','RO')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Russian Federation','RU')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Rwanda','RW')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Saudi Arabia','SA')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Solomon Islands','SB')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Seychelles','SC')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Sudan','SD')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Sweden','SE')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Singapore','SG')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Saint Helena','SH')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Slovenia','SI')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Slovakia','SK')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Sierra Leone','SL')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('San Marino','SM')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Senegal','SN')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Somalia','SO')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Suriname','SR')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Sao Tome and Principe','ST')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('El Salvador','SV')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Syrian Arab Republic','SY')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Swaziland','SZ')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Turks and Caicos Islands','TC')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Chad','TD')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Togo','TG')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Thailand','TH')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Tajikistan','TJ')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Tokelau','TK')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Timor-Leste','TL')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Turkmenistan','TM')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Tunisia','TN')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Tonga','TO')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Turkey','TR')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Trinidad and Tobago','TT')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Tuvalu','TV')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Taiwan','TW')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Tanzania','TZ')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Ukraine','UA')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Uganda','UG')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('United States','US')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Uruguay','UY')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Uzbekistan','UZ')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Saint Vincent and the Grenadines','VC')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Venezuela','VE')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Virgin Islands, British','VG')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Viet Nam','VN')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Vanuatu','VU')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Wallis and Futuna','WF')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Samoa','WS')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Yemen','YE')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Mayotte','YT')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('South Africa','ZA')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Zambia','ZM')
INSERT INTO [dbo].[tmp_country]([country_name] ,[country_code]) VALUES ('Zimbabwe','ZW')
