
/****** Object:  Table [dbo].[tmp_country]    Script Date: 12/22/2016 11:34:12 AM ******/
DROP TABLE [dbo].[tmp_currency]
GO
/****** Object:  Table [dbo].[tmp_country]    Script Date: 12/22/2016 11:34:12 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tmp_currency](
	[COUNTRY] [varchar](50) NULL,
	[ABBREVIATION] [varchar](50) NULL,
	[CODE] [varchar](50) NULL
)

GO
SET ANSI_PADDING OFF
GO
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('United States', 'US', '1');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Afghanistan', 'AF', '2185');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Albania', 'AL', '2186');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Algeria', 'DZ', '2187');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Andorra', 'AD', '2188');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Angola', 'AO', '2189');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Antartica', 'AQ', '2190');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Antigua and Barbuda', 'AG', '2191');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Argentina', 'AR', '2192');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Armenia', 'AM', '2193');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Australia', 'AU', '2194');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Austria', 'AT', '2195');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Azerbaijan', 'AZ', '2196');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Bahamas', 'BS', '2197');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Bahrain', 'BH', '2198');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Bangladesh', 'BD', '2199');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Barbados', 'BB', '2200');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Belarus', 'BY', '2201');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Belgium', 'BE', '2202');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Belize', 'BZ', '2203');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Benin', 'BJ', '2204');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Bhutan', 'BT', '2205');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Bolivia', 'BO', '2206');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Bosnia Hercegovina', 'BA', '2207');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Botswana', 'BW', '2208');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Brazil', 'BR', '2209');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Brunei Darussalam', 'BN', '2210');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Bulgaria', 'BG', '2211');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Burkina Faso', 'BF', '2212');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Burundi', 'BI', '2213');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Cambodia', 'KH', '2214');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Cameroon', 'CM', '2215');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Canada', 'CA', '2216');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Cape Verde', 'CV', '2217');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Central African Republic', 'CF', '2218');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Chad', 'TD', '2219');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Chile', 'CL', '2220');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('China', 'CN', '2221');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Columbia', 'CO', '2222');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Comoros', 'KM', '2223');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Costa Rica', 'CR', '2226');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Cote d''Ivoire', 'CO', '2227');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Croatia', 'HR', '2228');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Cuba', 'CU', '2229');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Cyprus', 'CY', '2230');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Czech Republic', 'CZ', '2231');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Denmark', 'DK', '2232');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Djibouti', 'DJ', '2233');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Dominica', 'DM', '2234');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Dominican Republic', 'DO', '2235');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Ecuador', 'EC', '2236');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Egypt', 'EG', '2237');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('El Salvador', 'SV', '2238');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Equatorial Guinea', 'GQ', '2239');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Eritrea', 'ER', '2240');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Estonia', 'EE', '2241');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Ethiopia', 'ET', '2242');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Fiji', 'FJ', '2243');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Finland', 'FI', '2244');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('France', 'FR', '2245');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Gabon', 'GA', '2246');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Georgia', 'GE', '2248');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Germany', 'DE', '2249');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Ghana', 'GH', '2250');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Greece', 'GR', '2251');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Greenland', 'GL', '2252');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Grenada', 'GD', '2253');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Guinea', 'GN', '2255');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Guinea-Bissau', 'GW', '2256');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Guyana', 'GY', '2257');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Haiti', 'HT', '2258');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Honduras', 'HN', '2259');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Hungary', 'HU', '2260');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Iceland', 'IS', '2261');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('India', 'IN', '2262');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Indonesia', 'ID', '2263');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Iran', 'IR', '2264');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Iraq', 'IQ', '2265');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Ireland', 'IE', '2266');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Israel', 'IL', '2267');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Italy', 'IT', '2268');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Jamaica', 'JM', '2269');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Japan', 'JP', '2270');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Jordan', 'JO', '2271');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Kazakhstan', 'KZ', '2272');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Kenya', 'KE', '2273');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Korea; Democratic People''s Republic Of (North)', 'KP', '2274');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Korea; Republic Of (South)', 'KR', '2275');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Kuwait', 'KW', '2276');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Kyrgyzstan', 'KG', '2277');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Lao People''s Democratic Republic', 'LA', '2278');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Latvia', 'LV', '2279');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Lebanon', 'LB', '2280');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Lesotho', 'LS', '2281');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Liberia', 'LR', '2282');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Liechtenstein', 'LI', '2284');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Lithuania', 'LT', '2285');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Luxembourg', 'LU', '2286');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Macau', 'MO', '2287');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Macedonia', 'MK', '2288');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Madagascar', 'MG', '2289');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Malawi', 'MW', '2290');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Malaysia', 'MY', '2291');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Mali', 'ML', '2292');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Malta', 'MT', '2293');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Mauritania', 'MR', '2294');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Mauritius', 'MU', '2295');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Mexico', 'MX', '2296');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Micronesia; Federated States of', 'FM', '2297');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Monaco', 'MC', '2299');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Mongolia', 'MN', '2300');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Morocco', 'MA', '2301');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Mozambique', 'MZ', '2302');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Myanmar', 'MM', '2303');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Namibia', 'NA', '2304');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Nepal', 'NP', '2305');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Netherlands', 'NL', '2306');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('New Zealand', 'NZ', '2307');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Nicaragua', 'NI', '2308');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Niger', 'NE', '2309');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Nigeria', 'NG', '2310');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Norway', 'NO', '2311');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Oman', 'OM', '2312');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Pakistan', 'PK', '2313');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Palau', 'PW', '2314');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Panama', 'PA', '2315');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Papua New Guinea', 'PG', '2316');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Paraguay', 'PY', '2317');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Peru', 'PE', '2318');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Philippines', 'PH', '2319');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Poland', 'PL', '2320');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Portugal', 'PT', '2321');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Qatar', 'QA', '2322');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Romania', 'RO', '2323');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Russian Federation', 'RU', '2324');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Rwanda', 'RW', '2325');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Saint Lucia', 'LC', '2326');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('San Marino', 'SM', '2327');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Saudi Arabia', 'SA', '2328');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Senegal', 'SN', '2329');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Seychelles', 'SC', '2331');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Sierra Leone', 'SL', '2332');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Singapore', 'SG', '2333');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Slovakia', 'SK', '2334');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Slovenia', 'SI', '2335');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Solomon Islands', 'SB', '2336');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Somalia', 'SO', '2337');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('South Africa', 'ZA', '2338');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Spain', 'ES', '2339');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Sri Lanka', 'LK', '2340');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Sudan', 'SD', '2341');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Suriname', 'SR', '2342');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Swaziland', 'SZ', '2343');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Sweden', 'SE', '2344');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Switzerland', 'CH', '2345');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Tajikistan', 'TJ', '2348');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Tanzania', 'TZ', '2349');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Thailand', 'TH', '2350');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Togo', 'TG', '2351');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Trinidad and Tobago', 'TT', '2352');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Tunisia', 'TN', '2353');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Turkey; Republic of', 'TR', '2354');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Turkmenistan', 'TM', '2355');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Uganda', 'UG', '2356');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Ukraine', 'UA', '2357');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('United Arab Emirates', 'AE', '2358');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('United Kingdom', 'GB', '2359');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Uruguay', 'UY', '2360');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Uzbekistan', 'UZ', '2361');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Vatican City', 'VA', '2362');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Venezuela', 'VE', '2363');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Vietnam', 'VN', '2364');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Yugoslavia', 'YU', '2367');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Zaire', 'ZR', '2368');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Zambia', 'ZM', '2369');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Zimbabwe', 'ZW', '2370');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Guatemala', 'GT', '2371');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Bermuda', 'BU', '2372');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Aruba', 'AB', '2373');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Puerto Rico', 'PR', '2374');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Taiwan', 'TW', '2375');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Guam', 'GU', '2376');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Hong Kong', 'CN', '2377');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('None Specified', 'NONE', '2378');
INSERT INTO tmp_currency (COUNTRY, ABBREVIATION, CODE) VALUES ('Cayman Islands', 'KY', '2379');
