create table company (
companyexternalId nvarchar(10),
companyname	nvarchar(500),
companylocationAddress nvarchar(1000),
companylocationName nvarchar(1000),
companylocationCountry nvarchar(500),
companylocationState nvarchar(500),
companylocationCity nvarchar(500),
companylocationZipCode nvarchar(500),
companyphone3 nvarchar(500),
companyphone2 nvarchar(500),
companyphone1 nvarchar(500),
companynote nvarchar(max),
companywebsite nvarchar(500)
)

create table contact (
contactcompanyId nvarchar(10),
contactexternalId nvarchar(10),
contactfirstName nvarchar(500),
contactlastName	nvarchar(500),
companyname nvarchar(500),
contactjobTitle nvarchar(500),
companylocationAddress nvarchar(1000),
companylocationCity	nvarchar(500),
companylocationState nvarchar(500),
companylocationZipCode nvarchar(500),
companylocationCountry nvarchar(500),
contactphone1 nvarchar(500),
contactphone2 nvarchar(500),
contactemail1 nvarchar(500),
contactemail2 nvarchar(500),
contactNote nvarchar(max)
);

create table candidate (
candidateexternalId	nvarchar(10),
candidatefirstName nvarchar(500),
candidateLastname nvarchar(500),
candidateemployer1 nvarchar(500),
candidatecompanyid nvarchar(10),
candidatejobTitle1 nvarchar(500),
candidateAddress nvarchar(1000),	
candidateCity nvarchar(500),
candidateState nvarchar(500),
candidatezipCode nvarchar(500),
candidateCountry nvarchar(500),
candidatephone3 nvarchar(500),
candidatephone2 nvarchar(500),
candidateworkphone nvarchar(500),
candidatemobile nvarchar(500),
candidateemail nvarchar(500),
candidateemailName nvarchar(500),
email1 nvarchar(500),
email2 nvarchar(500),
email3 nvarchar(500),
candidatenote nvarchar(max),
candidatecompanywebsite nvarchar(500),
);
