//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCDM2.Data.EF.OrcanIntelligence
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string Id { get; set; }
        public bool IsDeleted { get; set; }
        public string MasterRecordId { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string RecordTypeId { get; set; }
        public string ParentId { get; set; }
        public string BillingStreet { get; set; }
        public string BillingCity { get; set; }
        public string BillingState { get; set; }
        public string BillingPostalCode { get; set; }
        public string BillingCountry { get; set; }
        public string BillingLatitude { get; set; }
        public string BillingLongitude { get; set; }
        public string BillingGeocodeAccuracy { get; set; }
        public string ShippingStreet { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingState { get; set; }
        public string ShippingPostalCode { get; set; }
        public string ShippingCountry { get; set; }
        public string ShippingLatitude { get; set; }
        public string ShippingLongitude { get; set; }
        public string ShippingGeocodeAccuracy { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string AccountNumber { get; set; }
        public string Website { get; set; }
        public string Sic { get; set; }
        public string Industry { get; set; }
        public string AnnualRevenue { get; set; }
        public string NumberOfEmployees { get; set; }
        public string Ownership { get; set; }
        public string TickerSymbol { get; set; }
        public string Description { get; set; }
        public string Rating { get; set; }
        public string Site { get; set; }
        public string OwnerId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedById { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedById { get; set; }
        public System.DateTime SystemModstamp { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
        public string Jigsaw { get; set; }
        public string JigsawCompanyId { get; set; }
        public string AccountSource { get; set; }
        public string SicDesc { get; set; }
        public Nullable<System.DateTime> AVTRRT__Date_Established__c { get; set; }
        public string AVTRRT__Exchange__c { get; set; }
        public Nullable<System.DateTime> AVTRRT__Expiration_date__c { get; set; }
        public string AVTRRT__Fee__c { get; set; }
        public string AVTRRT__Flat_Fee__c { get; set; }
        public string AVTRRT__Guarantee_Information__c { get; set; }
        public string AVTRRT__Jobs_Website__c { get; set; }
        public string AVTRRT__Password__c { get; set; }
        public bool AVTRRT__Required__c { get; set; }
        public string AVTRRT__Revenue__c { get; set; }
        public string AVTRRT__Symbol__c { get; set; }
        public string AVTRRT__Terms__c { get; set; }
        public string AVTRRT__Time_Zone__c { get; set; }
        public string AVTRRT__User__c { get; set; }
        public string AVTRRT__VMS_Website__c { get; set; }
        public string AVTRRT__Year_Started__c { get; set; }
        public string AVTRRT__Lat__c { get; set; }
        public string AVTRRT__Lon__c { get; set; }
        public string AVTRRT__Map_Which_Address__c { get; set; }
        public string AVTRRT__Mapping_Status__c { get; set; }
        public string AVTRRT__External_ID__c { get; set; }
    }
}
