create table Assessments (
QuestionnaireId nvarchar(max),
AssessmentName nvarchar(max),
QuestionnaireOwnerId nvarchar(max),
CreatedBy nvarchar(max),
ModifiedBy nvarchar(max),
CreatedTime nvarchar(max),
ModifiedTime nvarchar(max),
LastActivityTime nvarchar(max),
Description nvarchar(max),
Category nvarchar(max),
NoofQuestions
nvarchar(max) )

create table Associated (
AssociateId nvarchar(max),
CandidateID nvarchar(max),
JobOpeningID nvarchar(max),
CandidateStatus nvarchar(max),
CreatedBy nvarchar(max),
ModifiedBy nvarchar(max),
CreatedTime nvarchar(max),
ModifiedTime
nvarchar(max) )

create table Attachments (
AttachmentId nvarchar(max),
AttachmentOwnerId nvarchar(max),
ModifiedBy nvarchar(max),
CreatedBy nvarchar(max),
CreatedTime nvarchar(max),
ModifiedTime nvarchar(max),
FileName nvarchar(max),
Size nvarchar(max),
ParentId nvarchar(max),
AttachmentType nvarchar(max),
Documents
nvarchar(max) )

create table Calls (
CallId nvarchar(max),
CallOwnerId nvarchar(max),
Subject nvarchar(max),
CallType nvarchar(max),
CallPurpose nvarchar(max),
ContactName nvarchar(max),
RelatedTo nvarchar(max),
CallStartTime nvarchar(max),
CallDuration nvarchar(max),
CallDuration_inseconds nvarchar(max),
Description nvarchar(max),
Billable nvarchar(max),
CallResult nvarchar(max),
CreatedBy nvarchar(max),
ModifiedBy nvarchar(max),
CreatedTime nvarchar(max),
ModifiedTime nvarchar(max),
Status nvarchar(max),
Reminder nvarchar(max),
Layout nvarchar(max),
CallStatus
nvarchar(max) )

------------------------

create table Candidates (
CandidateId nvarchar(max),
CandidateID_ nvarchar(max),
FirstName nvarchar(max),
LastName nvarchar(max),
FullName nvarchar(max),
Email nvarchar(max),
Phone nvarchar(max),
Fax nvarchar(max),
Mobile nvarchar(max),
Website nvarchar(max),
AssociatedTags nvarchar(max),
Street nvarchar(max),
City nvarchar(max),
State nvarchar(max),
ZipCode nvarchar(max),
Country nvarchar(max),
ExperienceinYears nvarchar(max),
CurrentEmployer nvarchar(max),
CurrentJobTitle nvarchar(max),
SkillSet nvarchar(max),
HighestQualificationHeld nvarchar(max),
ExpectedSalary nvarchar(max),
CurrentSalary nvarchar(max),
SkypeID nvarchar(max),
AdditionalInfo nvarchar(max),
CreatedBy nvarchar(max),
ModifiedBy nvarchar(max),
CreatedTime nvarchar(max),
UpdatedOn nvarchar(max),
Salutation nvarchar(max),
Currency nvarchar(max),
ExchangeRate nvarchar(max),
LastActivityTime nvarchar(max),
LastMailedTime nvarchar(max),
Twitter nvarchar(max),
AssociatedanySocialProfiles nvarchar(max),
CandidateOwnerId nvarchar(max),
Source nvarchar(max),
EmailOptOut nvarchar(max),
IsHotCandidate nvarchar(max),
IsLocked nvarchar(max),
IsUnqualified nvarchar(max),
IsAttachmentPresent nvarchar(max),
CandidateStatus nvarchar(max),
SupplyChainLogisticsSkills_ifapplicable nvarchar(max),
BankingInsurance nvarchar(max),
PreferredWorkLocation nvarchar(max),
ITSkills_ifapplicable nvarchar(max),
Industry_maxselect2 nvarchar(max),
PositionLevel nvarchar(max),
Discipline nvarchar(max),
Gender nvarchar(max),
ITQualification_ifapplicable nvarchar(max),
FinanceQualifications_ifapplicable nvarchar(max),
MaritalStatus nvarchar(max),
EngineeringSkills_ifapplicable nvarchar(max),
FinanceSkills_ifapplicable nvarchar(max),
ITSystems_ifapplicable nvarchar(max),
CandidateStatus2 nvarchar(max),
SalesMarketingSkills_ifapplicable nvarchar(max),
HRSkills_ifapplicable nvarchar(max),
DateofBirth nvarchar(max),
PrevEmploymentDate2 nvarchar(max),
MyFirstImpression nvarchar(max),
CandidatesreasonforLookingOut nvarchar(max),
Interviewer nvarchar(max),
OfficeNumber nvarchar(max),
PresentSalary nvarchar(max),
WhatPositionCandidateissuitable nvarchar(max),
Referredby nvarchar(max),
PreviousEmployer1 nvarchar(max),
ICPassportNumber nvarchar(max),
CandidatesKeyExperienceSkills nvarchar(max),
Nationality nvarchar(max),
CandidateSummaryforClient nvarchar(max),
EmploymentDate nvarchar(max),
Preferredname nvarchar(max),
PrevEmploymentDate1 nvarchar(max),
FixedAllowanceBenefits nvarchar(max),
HomePersonalNumber nvarchar(max),
ExpectedSalary2 nvarchar(max),
CurrentJobTitle2 nvarchar(max),
PreviousJobTitle1 nvarchar(max),
PreviousJobTitle2 nvarchar(max),
NoticePeriod nvarchar(max),
Previousemployer2 nvarchar(max),
Contactaddress nvarchar(max),
Totalworkexp_month nvarchar(max),
CareerPageInviteStatus nvarchar(max),
CurrentWorkLocation nvarchar(max),
Layout nvarchar(max),
Rating nvarchar(max),
VisitorScore
nvarchar(max) )

create table Candidates_Educational_Details (
TABULARROWID nvarchar(max),
LEADID nvarchar(max),
InstituteSchool nvarchar(max),
MajorDepartment nvarchar(max),
Degree nvarchar(max),
Duration_From nvarchar(max),
Duration_To nvarchar(max),
Currentlypursuing
nvarchar(max) )

create table Candidates_Experience_Details (
TABULARROWID nvarchar(max),
LEADID nvarchar(max),
OccupationTitle nvarchar(max),
Company nvarchar(max),
Summary nvarchar(max),
WorkDuration_From nvarchar(max),
WorkDuration_To nvarchar(max),
Icurrentlyworkhere
nvarchar(max) )

create table Clients (
ClientId nvarchar(max),
AccountManagerId nvarchar(max),
ClientName nvarchar(max),
ContactNumber nvarchar(max),
Fax nvarchar(max),
ParentClient nvarchar(max),
Website nvarchar(max),
Industry nvarchar(max),
About nvarchar(max),
CreatedBy nvarchar(max),
ModifiedBy nvarchar(max),
CreatedTime nvarchar(max),
ModifiedTime nvarchar(max),
Currency nvarchar(max),
ExchangeRate nvarchar(max),
LastActivityTime nvarchar(max),
LastMailedTime nvarchar(max),
Source nvarchar(max),
AssociatedTags nvarchar(max),
BillingStreet nvarchar(max),
ShippingStreet nvarchar(max),
BillingCity nvarchar(max),
ShippingCity nvarchar(max),
BillingState nvarchar(max),
ShippingState nvarchar(max),
BillingCode nvarchar(max),
ShippingCode nvarchar(max),
BillingCountry nvarchar(max),
ShippingCountry nvarchar(max),
IsAttachmentPresent nvarchar(max),
Industry_Selectmax2 nvarchar(max),
Remarks_egsellingpointofclient nvarchar(max),
Contactaddress nvarchar(max),
Layout
nvarchar(max) )

create table Contacts (
ContactId nvarchar(max),
FirstName nvarchar(max),
LastName nvarchar(max),
FullName nvarchar(max),
ClientId nvarchar(max),
Email nvarchar(max),
JobTitle nvarchar(max),
Department nvarchar(max),
WorkPhone nvarchar(max),
Fax nvarchar(max),
Mobile nvarchar(max),
SkypeID nvarchar(max),
CreatedBy nvarchar(max),
ModifiedBy nvarchar(max),
CreatedTime nvarchar(max),
ModifiedTime nvarchar(max),
Salutation nvarchar(max),
Currency nvarchar(max),
ExchangeRate nvarchar(max),
LastActivityTime nvarchar(max),
Twitter nvarchar(max),
LastMailedTime nvarchar(max),
AssociatedanySocialProfiles nvarchar(max),
AssociatedTags nvarchar(max),
MailingStreet nvarchar(max),
OtherStreet nvarchar(max),
MailingCity nvarchar(max),
OtherCity nvarchar(max),
MailingState nvarchar(max),
OtherState nvarchar(max),
MailingZip nvarchar(max),
OtherZip nvarchar(max),
MailingCountry nvarchar(max),
OtherCountry nvarchar(max),
ContactOwnerId nvarchar(max),
Source nvarchar(max),
Isprimarycontact nvarchar(max),
EmailOptOut nvarchar(max),
IsAttachmentPresent nvarchar(max),
Description nvarchar(max),
PersonalEmail nvarchar(max),
Preferredname nvarchar(max),
MeetingNotes nvarchar(max),
Layout nvarchar(max),
VisitorScore
nvarchar(max) )

create table Emails (
EmailId nvarchar(max),
EmailOwnerId nvarchar(max),
Subject nvarchar(max),
EntityId nvarchar(max),
CreatedBy nvarchar(max),
ModifiedBy nvarchar(max),
CreatedTime nvarchar(max),
ModifiedTime nvarchar(max),
LastOpened nvarchar(max),
LastClicked nvarchar(max),
FirstOpened nvarchar(max),
FirstClicked nvarchar(max),
NoofOpens nvarchar(max),
NoofClicks nvarchar(max),
BounceStatus
nvarchar(max) )

create table Events (
EventId nvarchar(max),
Title nvarchar(max),
Location nvarchar(max),
Allday nvarchar(max),
From1 nvarchar(max),
To1 nvarchar(max),
EventOwnerId nvarchar(max),
ContactName nvarchar(max),
RelatedTo nvarchar(max),
Repeat nvarchar(max),
Reminder nvarchar(max),
CreatedBy nvarchar(max),
ModifiedBy nvarchar(max),
CreatedTime nvarchar(max),
ModifiedTime nvarchar(max),
Currency nvarchar(max),
ExchangeRate nvarchar(max),
Participants nvarchar(max),
Description nvarchar(max),
Layout nvarchar(max),
CheckInTime nvarchar(max),
CheckInBy nvarchar(max),
CheckInComment nvarchar(max),
CheckInSubLocality nvarchar(max),
CheckInCity nvarchar(max),
CheckInState nvarchar(max),
CheckInCountry nvarchar(max),
Latitude nvarchar(max),
Longitude nvarchar(max),
ZIPCode nvarchar(max),
CheckInAddress nvarchar(max),
CheckInStatus nvarchar(max),
From2 nvarchar(max),
To2 nvarchar(max),
Uid nvarchar(max),
RecurrenceId
nvarchar(max) )

create table Forecasts (
ForecastId nvarchar(max),
Year nvarchar(max),
Month nvarchar(max),
ForecastName nvarchar(max),
ForecastOwnerId nvarchar(max),
CommitAmount nvarchar(max),
BestcaseAmount nvarchar(max),
StartDate nvarchar(max),
EndDate nvarchar(max),
CreatedBy nvarchar(max),
ModifiedBy nvarchar(max),
CreatedTime nvarchar(max),
ModifiedTime nvarchar(max),
Target nvarchar(max),
Currency nvarchar(max),
ExchangeRate nvarchar(max),
Role nvarchar(max),
ParentForecast nvarchar(max),
Targetexcludingchild nvarchar(max),
Targetachievedexcludingchild nvarchar(max),
Targetachievedpercentageexcludingchild nvarchar(max),
Pipelineexcludingchild nvarchar(max),
TargetAchieved nvarchar(max),
TargetAchievedPercentage nvarchar(max),
JobOpeningPipeline nvarchar(max),
LastComputedTime
nvarchar(max) )

create table Interviews (
InterviewId nvarchar(max),
InterviewOwnerId nvarchar(max),
InterviewName nvarchar(max),
Location nvarchar(max),
ClientId nvarchar(max),
Type nvarchar(max),
CandidateId nvarchar(max),
JobOpeningId nvarchar(max),
Interviewer nvarchar(max),
LastActivityTime nvarchar(max),
From_ nvarchar(max),
To_ nvarchar(max),
InterviewStatus nvarchar(max),
ScheduleComments nvarchar(max),
CreatedBy nvarchar(max),
ModifiedBy nvarchar(max),
CreatedTime nvarchar(max),
ModifiedTime nvarchar(max),
Currency nvarchar(max),
ExchangeRate nvarchar(max),
AssociatedTags nvarchar(max),
IsAttachmentPresent nvarchar(max),
Reminder nvarchar(max),
Layout
nvarchar(max) )

create table JobOpenings (
JobOpeningId nvarchar(max),
JobOpeningID_ nvarchar(max),
AccountManagerId nvarchar(max),
JobType nvarchar(max),
IsHotJobOpening nvarchar(max),
Publish nvarchar(max),
NoofCandidatesAssociated nvarchar(max),
AssociatedTags nvarchar(max),
Title nvarchar(max),
PostingTitle nvarchar(max),
Currency nvarchar(max),
ExchangeRate nvarchar(max),
LastActivityTime nvarchar(max),
JobOpeningStatus nvarchar(max),
DateOpened nvarchar(max),
TargetDate nvarchar(max),
ClientId nvarchar(max),
ContactId nvarchar(max),
AssignedRecruiter_s nvarchar(max),
City nvarchar(max),
State nvarchar(max),
Country nvarchar(max),
Industry nvarchar(max),
NumberofPositions nvarchar(max),
CreatedBy nvarchar(max),
ModifiedBy nvarchar(max),
CreatedTime nvarchar(max),
ModifiedTime nvarchar(max),
WorkExperience nvarchar(max),
Salary nvarchar(max),
Rate nvarchar(max),
Stage nvarchar(max),
Probability nvarchar(max),
ExpectedRevenue nvarchar(max),
JobDescription nvarchar(max),
IsAttachmentPresent nvarchar(max),
IsLocked nvarchar(max),
Discipline nvarchar(max),
JobInProgressStatus nvarchar(max),
Country_ nvarchar(max),
BillingAmtDetails nvarchar(max),
UpperSalaryRange nvarchar(max),
EstimatedBilling_RM nvarchar(max),
CommencingWork nvarchar(max),
ClientContact nvarchar(max),
Skillset nvarchar(max),
Layout nvarchar(max),
BDConsultantName nvarchar(max),
ActivationDate_inactiveclient nvarchar(max),
MissedRevenue nvarchar(max),
ActualRevenue nvarchar(max),
NoofCandidatesHired nvarchar(max),
ZipCode
nvarchar(max) )



create table Notes (
NoteId nvarchar(max),
NoteOwnerId nvarchar(max),
NoteTitle nvarchar(max),
NoteContent nvarchar(max),
ParentId nvarchar(max),
CreatedBy nvarchar(max),
ModifiedBy nvarchar(max),
CreatedTime nvarchar(max),
ModifiedTime
nvarchar(max) )

create table Tasks (
TaskId nvarchar(max),
TaskOwnerId nvarchar(max),
Subject nvarchar(max),
DueDate nvarchar(max),
ContactName nvarchar(max),
RelatedTo nvarchar(max),
Status nvarchar(max),
Priority nvarchar(max),
SendNotificationEmail nvarchar(max),
Repeat nvarchar(max),
Reminder nvarchar(max),
CreatedBy nvarchar(max),
ModifiedBy nvarchar(max),
CreatedTime nvarchar(max),
ModifiedTime nvarchar(max),
Currency nvarchar(max),
ExchangeRate nvarchar(max),
Description nvarchar(max),
Layout nvarchar(max),
ClosedTime
nvarchar(max) )

create table Users (
UserId nvarchar(max),
Email nvarchar(max),
FirstName nvarchar(max),
LastName nvarchar(max),
UserStatus nvarchar(max),
ConfirmationStatus nvarchar(max),
Alias nvarchar(max),
Phone nvarchar(max),
Mobile nvarchar(max),
Fax nvarchar(max),
Website nvarchar(max),
Street nvarchar(max),
City nvarchar(max),
State nvarchar(max),
Country nvarchar(max),
ZipCode nvarchar(max),
LanguageLocale nvarchar(max),
CountryLocale nvarchar(max),
TimeZone nvarchar(max),
TimeFormat
nvarchar(max) )


