CREATE TABLE [dbo].[Company] (
[DynamicDataId] int PRIMARY KEY,
[LastUpdatedByuserId] int,
[LastUpdatedByEmail] nvarchar(max),
[LastUpdatedDate] date,
[CompanyName] nvarchar(max),
[OfficeTelNo] nvarchar(max),
[Website] nvarchar(max),
[Add1] nvarchar(max),
[Add2] nvarchar(max),
[Town] nvarchar(max),
[Country] nvarchar(max),
[Postcode] nvarchar(max),
[Division] nvarchar(max),
[Industry] nvarchar(max),
[NoofEmp] nvarchar(max),
[Companyid] nvarchar(max),
[AgreedRate] nvarchar(max),
[TermsSent] nvarchar(max),
[TermsSigned] nvarchar(max),
[AdditionalInfo] nvarchar(max),
[BuildingName] nvarchar(max),
[CompanyRegNo] nvarchar(max),
[TaxNumber] nvarchar(max),
[AccPayableContact] nvarchar(max),
[BankName] nvarchar(max),
[AccountNumber] nvarchar(max),
[AccountName] nvarchar(max),
[FurtherInfo] nvarchar(max),
[alt_building] nvarchar(max),
[altAdd2] nvarchar(max),
[altTown] nvarchar(max),
[altAdd1] nvarchar(max),
[altCountry] nvarchar(max),
[altPostcode] nvarchar(max),
[br_Building] nvarchar(max),
[br_Add1] nvarchar(max),
[br_Postcode] nvarchar(max),
[br_Add2] nvarchar(max),
[br_Town] nvarchar(max),
[br_Country] nvarchar(max),
[CompStatus] nvarchar(max),
[CreatedDate] nvarchar(max)
)


CREATE TABLE [dbo].[Contact] (
[DynamicDataId] int PRIMARY KEY,
[LastUpdatedByuserId] int,
[LastUpdatedByEmail] nvarchar(max),
[LastUpdatedDate] date,
[Name] nvarchar(max),
[FirstName] nvarchar(max),
[LastName] nvarchar(max),
[Company] nvarchar(max),
[CompanyID] int,
[Tel] nvarchar(max),
[Mobile] nvarchar(max),
[Mobile2] nvarchar(max),
[MobileCon] nvarchar(max),
[Fax] nvarchar(max),
[Email] nvarchar(max),
[Email2] nvarchar(max),
[EmailCombine] nvarchar(max),
[Title] nvarchar(max),
[Position] nvarchar(max),
[Extn] nvarchar(max),
[knownAs] nvarchar(max),
[Division] nvarchar(max),
[CreatedDate] nvarchar(max)
)


CREATE TABLE [dbo].[Vacancy] (
[DynamicDataId] int PRIMARY KEY,
[LastUpdatedByuserId] int,
[LastUpdatedByEmail] nvarchar(max),
[LastUpdatedDate] date,
[JobTitle] nvarchar(max),
[Consultant] nvarchar(max),
[Company] nvarchar(max),
[CompanyID] nvarchar(max),
[Contact] nvarchar(max),
[ContactID] nvarchar(max),
[VacancyStatus] nvarchar(max),
[VacancyType] nvarchar(max),
[Hours] nvarchar(max),
[Requirements] nvarchar(max),
[SkillSet] nvarchar(max),
[JobSpecNotes] nvarchar(max),
[Other] nvarchar(max),
[Source] nvarchar(max),
[NumberofPositions] nvarchar(max),
[JobType] nvarchar(max),
[RateTo] nvarchar(max),
[CurrencyCode] nvarchar(max),
[IssuedOn] nvarchar(max),
[Country] nvarchar(max),
[BuildingName] nvarchar(max),
[Add1] nvarchar(max),
[Add2] nvarchar(max),
[Town] nvarchar(max),
[PostCode] nvarchar(max),
[ContractLength] nvarchar(max),
[ContractRate] nvarchar(max),
[Fee] nvarchar(max),
[qa_checkedBy] nvarchar(max),
[qa_dateChecked] date,
[qa_info] nvarchar(max),
[CreatedDate] nvarchar(max)
)


CREATE TABLE [dbo].[Candidate] (
[DynamicDataId] int PRIMARY KEY,
[LastUpdatedByuserId] int,
[LastUpdatedByEmail] nvarchar(max),
[LastUpdatedDate] date,
[Title] nvarchar(max),
[Name] nvarchar(max),
[FirstName] nvarchar(max),
[LastName] nvarchar(max),
[Nationality] nvarchar(max),
[HomeTel] nvarchar(max),
[Mobile] nvarchar(max),
[Email] nvarchar(max),
[Source] nvarchar(max),
[PrimaryContact] nvarchar(max),
[CurrentCompany] nvarchar(max),
[Salary] nvarchar(max),
[ReasonforLeaving] nvarchar(max),
[LookingFor] nvarchar(max),
[CurrentJobTitle] nvarchar(max),
[Started] nvarchar(max),
[ResponsibilitiesandAchievements] nvarchar(max),
[RolesHistory] nvarchar(max),
[InterviewNotes] nvarchar(max),
[References] nvarchar(max),
[Locations] nvarchar(max),
[Qualifications] nvarchar(max),
[JobFunction] nvarchar(max),
[Industry] nvarchar(max),
[Add1] nvarchar(max),
[Add2] nvarchar(max),
[Town] nvarchar(max),
[HomeProvince] nvarchar(max),
[Postcode] nvarchar(max),
[LinkedIn] nvarchar(max),
[DateofBirth] nvarchar(max),
[SecondaryContact] nvarchar(max),
[WorkPermit] nvarchar(max),
[FixedTermContract] nvarchar(max),
[Contract] nvarchar(max),
[Permanent] nvarchar(max),
[candidateid] int,
[Email2] nvarchar(max),
[City] nvarchar(max),
[Mobile2] nvarchar(max),
[IndustrySkills] nvarchar(max),
[CreatedDate] nvarchar(max),
[JobFunctions] nvarchar(max)
)

CREATE TABLE [dbo].[Notes] (
[Id] int PRIMARY KEY,
[ParentId] int,
[Text] nvarchar(max),
[CreatedBy] int,
[CreatedByEmail] nvarchar(max),
[CreatedDate] datetime
)

CREATE TABLE [dbo].[Users] (
[Id] int PRIMARY KEY,
[EmailAddress] nvarchar(max),
[FirstName] nvarchar(max),
[LastName] nvarchar(max)
)

CREATE TABLE [dbo].[Document] (
[Id] int PRIMARY KEY,
[Folder] nvarchar(max),
[Filename] nvarchar(max),
[Description] nvarchar(max),
[CreatedByUserId] int,
[CreatedByEmail] nvarchar(max),
[DynamicDataId] int,
[PrimaryIndicator] int,
[CreatedDate] date
)

CREATE TABLE [dbo].[Interview] (
[DynamicDataId] int PRIMARY KEY,
[LastUpdatedByuserId] int,
[LastUpdatedByEmail] nvarchar(max),
[LastUpdatedDate] date,
[Reference] nvarchar(max),
[Candidate] nvarchar(max),
[CandidateID] int,
[Vacancy] nvarchar(max),
[VacancyID] int,
[Consultant] nvarchar(max),
[InterviewDate] nvarchar(max),
[IntStatus] nvarchar(max),
[LoggedBy] nvarchar(max),
[Outcome] nvarchar(max),
[Time_hh] int,
[Time_mm] int,
[CreatedDate] nvarchar(max)
)