insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (2986,'Design Engineer', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (2987,'Applications Engineer', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (2987,'CAD Technician', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (2987,'Design Engineer', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (2987,'Electrical Design Engineer', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (2987,'Electrical Engineer', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (2987,'Electronic Design Engineer', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (2987,'Field Service Engineer', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (2987,'Mechanical Design Engineer', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (2988,'Managing Director', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (2988,'Sales Director', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (2988,'Sales Manager', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (2989,'Consultant', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (2989,'Contract Manager', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (2989,'General/Operations Manager', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (2989,'H_S Manager', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (2989,'Production Manager', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (2989,'Project Manager', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (2989,'Sales Manager', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (2989,'Service Manager', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (2989,'Technical Manager', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (2989,'Workshop/Depot Manager', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (2990,'Account Manager', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (2990,'Sales Engineer', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (2990,'Sales Executive', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (2990,'Sales Manager', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (2990,'Service Sales Manager', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (2991,'Administration', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (2991,'Adminstration', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (2991,'Admisitration', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (2991,'Coordinator', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (2991,'Coordinator/Controller', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (2991,'Customer Service', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (3097,'Commissiong Engineer', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (3097,'Commissioning Engineer', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (3097,'Controls Engineer', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (3097,'Electrical Design Engineer', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (3097,'Field Service Engineer', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (3097,'Mechanical Design Engineer', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (3097,'Operator', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (3097,'Production Engineer', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (3097,'Project Engineer', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (3097,'Quotations Engineer', now() );
insert into sub_functional_expertise (functional_expertise_id,name,insert_timestamp) values (3097,'Workshop/Depot Engineer', now() );
